# Generated by Django 6.0.8 on 2026-09-28 22:22

import core.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.CharField(help_text="L-<n> (core_sequence_counter LEAD).", max_length=24)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("HOME_ENQUIRY", "Home enquiry"),
                            ("ADVANCED_CALC", "Advanced calculator quote"),
                            ("GROUP_PURCHASE", "Group purchase"),
                            ("CONTACT", "Contact"),
                            ("REFERRAL", "Referral"),
                            ("QUOTE_REQUEST", "Quotation request"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("FOOTER", "Footer — Ready to go solar"),
                            ("HOME_BOOKING", "Book a consultation form"),
                            ("CONTACT_PAGE", "Contact Us page"),
                            ("GROUP_PURCHASE", "Group Purchase reservation"),
                            ("QUOTATION", "Quotation request (calculator)"),
                            ("QUOTE_REQUEST", "Quote request (advanced calculator)"),
                            ("REFERRAL_PARTNER", "Referral partner application"),
                            ("WARRANTY_SERVICE", "Warranty service request"),
                            ("OTHER", "Website form"),
                            ("STUDIO", "Entered in Studio"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_e164", models.CharField(blank=True, default="", max_length=16)),
                ("email", core.models.fields.CIEmailField(blank=True, default="", max_length=254)),
                ("pincode", models.CharField(blank=True, default="", max_length=6)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict, help_text="Validated form extras: details, calculator inputs/outputs, utm.")),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "New"), ("CONTACTED", "Contacted"), ("QUALIFIED", "Qualified"), ("CONVERTED", "Converted"), ("LOST", "Lost"), ("SPAM", "Spam")], default="NEW", max_length=12
                    ),
                ),
                ("lost_reason", models.TextField(blank=True, default="")),
                ("source_url", models.CharField(blank=True, default="", help_text="Site path or URL the form was submitted from.", max_length=500)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="customers.customer")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "leads_lead",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("IMPORTED", "Imported"),
                            ("UPDATED", "Updated"),
                            ("ASSIGNED", "Assigned"),
                            ("STATUS_CHANGED", "Status changed"),
                            ("NOTE_ADDED", "Note added"),
                            ("CONVERTED", "Converted"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="leads.lead")),
            ],
            options={
                "db_table": "leads_lead_event",
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("body", models.TextField()),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="leads.lead")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "leads_lead_note",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OtpRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phone_e164", models.CharField(max_length=16)),
                ("purpose", models.CharField(choices=[("LEAD", "Website enquiry"), ("APPROVAL", "Customer approval")], default="LEAD", max_length=16)),
                ("provider_sid", models.CharField(blank=True, default="", max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "leads_otp_request",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["phone_e164", "created_at"], name="leads_otp_request_phone_at")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("purpose__in", ["LEAD", "APPROVAL"])), name="leads_otp_request_purpose_valid"),
                    models.CheckConstraint(condition=models.Q(("phone_e164__regex", "^\\+[1-9][0-9]{7,14}$")), name="leads_otp_request_phone_e164_format"),
                    models.CheckConstraint(condition=models.Q(("expires_at__gt", models.F("created_at"))), name="leads_otp_request_expires_after_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarrantyRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_e164", models.CharField(max_length=16)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("LOW_GENERATION", "Low Generation"),
                            ("INVERTER_FAULT", "Inverter Fault"),
                            ("PANEL_DAMAGE", "Panel Damage"),
                            ("NET_METERING", "KSEB / Net Metering"),
                            ("WARRANTY_CLAIM", "Warranty Claim"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("system_details", models.JSONField(blank=True, default=dict, help_text="Validated system facts (capacity, inverter, installed on …).")),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "New"), ("IN_PROGRESS", "In progress"), ("RESOLVED", "Resolved"), ("CLOSED", "Closed"), ("REJECTED", "Rejected (not covered / spam)")],
                        default="NEW",
                        max_length=12,
                    ),
                ),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="customers.customer")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "leads_warranty_request",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_e164", models.CharField(max_length=16)),
                ("email", core.models.fields.CIEmailField(max_length=254)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("REAL_ESTATE_AGENT", "Real Estate Agent"),
                            ("BUILDER_DEVELOPER", "Builder / Developer"),
                            ("INFLUENCER", "Influencer / Content Creator"),
                            ("FINANCIAL_ADVISOR", "Financial Advisor"),
                            ("FREELANCER", "Freelancer / Gig Worker"),
                            ("SOCIETY_RWA", "Society / RWA Representative"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Kollam", "Kollam"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Alappuzha", "Alappuzha"),
                            ("Kottayam", "Kottayam"),
                            ("Idukki", "Idukki"),
                            ("Ernakulam", "Ernakulam"),
                            ("Thrissur", "Thrissur"),
                            ("Palakkad", "Palakkad"),
                            ("Malappuram", "Malappuram"),
                            ("Kozhikode", "Kozhikode"),
                            ("Wayanad", "Wayanad"),
                            ("Kannur", "Kannur"),
                            ("Kasaragod", "Kasaragod"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("NEW", "New"), ("CONTACTED", "Contacted"), ("APPROVED", "Approved (partner onboarded)"), ("REJECTED", "Rejected")], default="NEW", max_length=12),
                ),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "leads_affiliate_application",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["status", "created_at"], name="leads_affiliate_status_at"), models.Index(fields=["phone_e164"], name="leads_affiliate_phone")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("profession__in", ["REAL_ESTATE_AGENT", "BUILDER_DEVELOPER", "INFLUENCER", "FINANCIAL_ADVISOR", "FREELANCER", "SOCIETY_RWA", "OTHER"])),
                        name="leads_affiliate_application_profession_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "district__in",
                                [
                                    "Thiruvananthapuram",
                                    "Kollam",
                                    "Pathanamthitta",
                                    "Alappuzha",
                                    "Kottayam",
                                    "Idukki",
                                    "Ernakulam",
                                    "Thrissur",
                                    "Palakkad",
                                    "Malappuram",
                                    "Kozhikode",
                                    "Wayanad",
                                    "Kannur",
                                    "Kasaragod",
                                ],
                            )
                        ),
                        name="leads_affiliate_application_district_valid",
                    ),
                    models.CheckConstraint(condition=models.Q(("status__in", ["NEW", "CONTACTED", "APPROVED", "REJECTED"])), name="leads_affiliate_application_status_valid"),
                    models.CheckConstraint(condition=models.Q(("phone_e164__regex", "^\\+[1-9][0-9]{7,14}$")), name="leads_affiliate_application_phone_e164_format"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerInstallation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("customer_name", models.CharField(max_length=255)),
                ("phone_e164", models.CharField(blank=True, default="", max_length=16)),
                ("pincode", models.CharField(max_length=6)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("address", models.TextField(blank=True, default="")),
                ("capacity_kw", models.DecimalField(decimal_places=3, max_digits=8)),
                ("system_type", models.CharField(blank=True, choices=[("ON_GRID", "On-grid"), ("OFF_GRID", "Off-grid"), ("HYBRID", "Hybrid")], default="", max_length=10)),
                ("installed_on", models.DateField()),
                ("status", models.CharField(choices=[("COMPLETED", "Completed"), ("IN_PROGRESS", "In progress"), ("PLANNED", "Planned")], default="COMPLETED", max_length=12)),
                ("is_showcase", models.BooleanField(default=False)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("photo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "leads_customer_installation",
                "ordering": ["-installed_on", "-id"],
                "indexes": [
                    models.Index(fields=["pincode", "status"], name="leads_installation_pincode"),
                    models.Index(fields=["district", "status"], name="leads_installation_district"),
                    models.Index(fields=["installed_on"], name="leads_installation_date"),
                    models.Index(
                        condition=models.Q(("deleted_at__isnull", True), ("is_showcase", True), ("status", "COMPLETED")), fields=["pincode", "installed_on"], name="leads_installation_showcase"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("status__in", ["COMPLETED", "IN_PROGRESS", "PLANNED"])), name="leads_customer_installation_status_valid"),
                    models.CheckConstraint(condition=models.Q(("system_type__in", ["", "ON_GRID", "OFF_GRID", "HYBRID"])), name="leads_customer_installation_system_type_valid"),
                    models.CheckConstraint(
                        condition=models.Q(("phone_e164", ""), ("phone_e164__regex", "^\\+[1-9][0-9]{7,14}$"), _connector="OR"), name="leads_customer_installation_phone_e164_format"
                    ),
                    models.CheckConstraint(condition=models.Q(("capacity_kw__gt", 0)), name="leads_customer_installation_capacity_positive"),
                    models.CheckConstraint(condition=models.Q(("pincode", ""), _negated=True), name="leads_customer_installation_pincode_present"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status", "created_at"], name="leads_lead_status_created"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone_e164", "created_at"], name="leads_lead_phone_created"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["created_at"], name="leads_lead_created"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(fields=("number",), name="leads_lead_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["HOME_ENQUIRY", "ADVANCED_CALC", "GROUP_PURCHASE", "CONTACT", "REFERRAL", "QUOTE_REQUEST"])), name="leads_lead_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["NEW", "CONTACTED", "QUALIFIED", "CONVERTED", "LOST", "SPAM"])), name="leads_lead_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(("form__in", ["FOOTER", "HOME_BOOKING", "CONTACT_PAGE", "GROUP_PURCHASE", "QUOTATION", "QUOTE_REQUEST", "REFERRAL_PARTNER", "WARRANTY_SERVICE", "OTHER", "STUDIO"])),
                name="leads_lead_form_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(condition=models.Q(("phone_e164", ""), ("phone_e164__regex", "^\\+[1-9][0-9]{7,14}$"), _connector="OR"), name="leads_lead_phone_e164_format"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(condition=models.Q(("pincode", ""), ("pincode__regex", "^[1-9][0-9]{5}$"), _connector="OR"), name="leads_lead_pincode_format"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(condition=models.Q(("number", ""), _negated=True), name="leads_lead_number_present"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "LOST"), _negated=True), models.Q(("lost_reason", ""), _negated=True), _connector="OR"), name="leads_lead_lost_has_reason"
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "CONVERTED"), _negated=True), ("customer__isnull", False), _connector="OR"), name="leads_lead_converted_has_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="leadevent",
            index=models.Index(fields=["lead", "at"], name="leads_lead_event_lead_at"),
        ),
        migrations.AddConstraint(
            model_name="leadevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("event__in", ["CREATED", "IMPORTED", "UPDATED", "ASSIGNED", "STATUS_CHANGED", "NOTE_ADDED", "CONVERTED", "ARCHIVED"])), name="leads_lead_event_event_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="leadnote",
            index=models.Index(fields=["lead", "created_at"], name="leads_lead_note_lead_at"),
        ),
        migrations.AddConstraint(
            model_name="leadnote",
            constraint=models.CheckConstraint(condition=models.Q(("body", ""), _negated=True), name="leads_lead_note_body_present"),
        ),
        migrations.AddIndex(
            model_name="warrantyrequest",
            index=models.Index(fields=["status", "created_at"], name="leads_warranty_status_at"),
        ),
        migrations.AddIndex(
            model_name="warrantyrequest",
            index=models.Index(fields=["phone_e164"], name="leads_warranty_phone"),
        ),
        migrations.AddConstraint(
            model_name="warrantyrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("issue_type__in", ["LOW_GENERATION", "INVERTER_FAULT", "PANEL_DAMAGE", "NET_METERING", "WARRANTY_CLAIM", "OTHER"])), name="leads_warranty_request_issue_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="warrantyrequest",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["NEW", "IN_PROGRESS", "RESOLVED", "CLOSED", "REJECTED"])), name="leads_warranty_request_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="warrantyrequest",
            constraint=models.CheckConstraint(condition=models.Q(("phone_e164__regex", "^\\+[1-9][0-9]{7,14}$")), name="leads_warranty_request_phone_e164_format"),
        ),
    ]
