"""Media services: every write and non-trivial read of this app.

* ``assets`` — upload / store generated bytes / edit / usage-guarded delete, library queryset;
* ``policies`` — per-kind limits; ``sniffing`` — content-based type detection and EXIF;
* ``storage`` — public (Bunny or local) and private (local) backends; ``bunny`` — the Bunny client;
* ``signing`` — signed URLs for private files; ``delivery`` — serving them (X-Accel or streamed);
* ``thumbnails`` — WebP previews (Celery, after commit).
"""
