"""Upload limits per kind (PLAN §1.4 "upload limits per kind") and the visibility each kind may use."""

from __future__ import annotations

from dataclasses import dataclass

from media.models import MediaAsset

MB = 1024 * 1024
JPEG, PNG, WEBP, HEIC = "image/jpeg", "image/png", "image/webp", "image/heic"
PDF = "application/pdf"
DOC = "application/msword"
DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

EXTENSIONS = {JPEG: ".jpg", PNG: ".png", WEBP: ".webp", HEIC: ".heic", PDF: ".pdf", DOC: ".doc", DOCX: ".docx"}
IMAGE_TYPES = frozenset({JPEG, PNG, WEBP, HEIC})

Visibility = MediaAsset.Visibility
Kind = MediaAsset.Kind


@dataclass(frozen=True)
class KindPolicy:
    kind: str
    mime_types: frozenset[str]
    max_bytes: int
    visibilities: frozenset[str]

    @property
    def max_megabytes(self) -> int:
        return self.max_bytes // MB


BOTH = frozenset({Visibility.PUBLIC, Visibility.PRIVATE})
PRIVATE_ONLY = frozenset({Visibility.PRIVATE})

POLICIES: dict[str, KindPolicy] = {
    Kind.IMAGE: KindPolicy(Kind.IMAGE, IMAGE_TYPES, 15 * MB, BOTH),
    Kind.PHOTO: KindPolicy(Kind.PHOTO, IMAGE_TYPES, 15 * MB, BOTH),
    Kind.DOCUMENT: KindPolicy(Kind.DOCUMENT, frozenset({PDF}), 20 * MB, BOTH),
    # Personal data: never on the CDN (also a DB check constraint on media_asset).
    Kind.RESUME: KindPolicy(Kind.RESUME, frozenset({PDF, DOC, DOCX}), 10 * MB, PRIVATE_ONLY),
    Kind.SIGNATURE: KindPolicy(Kind.SIGNATURE, frozenset({PNG}), 2 * MB, PRIVATE_ONLY),
}
# Kinds that get a WebP thumbnail (generated by media.tasks.generate_thumbnail after commit).
THUMBNAIL_KINDS = frozenset({Kind.IMAGE, Kind.PHOTO, Kind.SIGNATURE})


def policy_for(kind: str) -> KindPolicy:
    return POLICIES[kind]
