"""Storage backends behind ``media_asset.file`` keys.

* **public**: Bunny (``MEDIA_PUBLIC_BACKEND="bunny"``, staging/prod) or the local filesystem under
  ``PUBLIC_MEDIA_ROOT`` (``"local"``, dev/test; served by Django under ``PUBLIC_MEDIA_URL`` only while ``DEBUG``).
* **private**: always the local filesystem under ``PRIVATE_MEDIA_ROOT`` — never the CDN. Served only after a
  signed-URL check (``media.services.delivery``).

Keys are relative POSIX paths generated by :func:`new_key` (``<folder>/<yyyy>/<mm>/<uuid><ext>``); the local backend
refuses anything that would escape its root.
"""

from __future__ import annotations

import os
import tempfile
import uuid
from pathlib import Path, PurePosixPath
from typing import BinaryIO, Protocol
from urllib.parse import quote

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.utils import timezone

from media.services import bunny

DEFAULT_FOLDER = "library"


class StorageError(RuntimeError):
    """The backend could not store, read or delete an object."""


class StorageNotFound(StorageError):
    pass


class Storage(Protocol):
    name: str

    def save(self, key: str, data: bytes) -> None: ...

    def read(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...

    def exists(self, key: str) -> bool: ...

    def url(self, key: str) -> str | None: ...


def new_key(folder: str, extension: str, *, now=None) -> str:
    now = now or timezone.now()
    return f"{folder or DEFAULT_FOLDER}/{now:%Y}/{now:%m}/{uuid.uuid4().hex}{extension}"


def thumbnail_key(key: str) -> str:
    return str(PurePosixPath(key).with_suffix("")) + ".thumb.webp"


def sibling_public_url(cdn_url: str, key: str, sibling_key: str) -> str | None:
    """Public URL of ``sibling_key`` stored beside ``key`` (e.g. its thumbnail), derived from ``key``'s URL.

    Both live in the same public backend under the same base URL, so no backend/configuration lookup is needed
    (listing 200 assets never reads the Bunny integration 200 times).
    """
    quoted = quote(key)
    if not cdn_url or not sibling_key or not cdn_url.endswith(quoted):
        return None
    return cdn_url[: -len(quoted)] + quote(sibling_key)


def _check_key(key: str) -> PurePosixPath:
    """A relative POSIX key whose every segment is a real name (no empty, ``.`` or ``..`` segments, no backslash)."""
    if not key or "\\" in key or "\x00" in key or any(segment in ("", ".", "..") for segment in key.split("/")):
        raise StorageError(f"Invalid storage key {key!r}.")
    return PurePosixPath(key)


class LocalStorage:
    """Filesystem backend. Writes are atomic (temp file + ``os.replace``); files are created ``0640``."""

    def __init__(self, root: Path | str, base_url: str | None, name: str):
        self.root = Path(root)
        self.base_url = base_url
        self.name = name

    def path(self, key: str) -> Path:
        return self.root.joinpath(*_check_key(key).parts)

    def save(self, key: str, data: bytes) -> None:
        target = self.path(key)
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=".upload-")
            try:
                with os.fdopen(fd, "wb") as handle:
                    handle.write(data)
                os.chmod(tmp, 0o640)
                os.replace(tmp, target)
            except BaseException:
                Path(tmp).unlink(missing_ok=True)
                raise
        except OSError as exc:
            raise StorageError(f"Cannot write {key}: {exc.__class__.__name__}") from exc

    def read(self, key: str) -> bytes:
        try:
            return self.path(key).read_bytes()
        except FileNotFoundError as exc:
            raise StorageNotFound(key) from exc
        except OSError as exc:
            raise StorageError(f"Cannot read {key}: {exc.__class__.__name__}") from exc

    def open(self, key: str) -> BinaryIO:
        try:
            return self.path(key).open("rb")
        except FileNotFoundError as exc:
            raise StorageNotFound(key) from exc

    def delete(self, key: str) -> None:
        try:
            self.path(key).unlink(missing_ok=True)
        except OSError as exc:
            raise StorageError(f"Cannot delete {key}: {exc.__class__.__name__}") from exc

    def exists(self, key: str) -> bool:
        return self.path(key).is_file()

    def url(self, key: str) -> str | None:
        if not self.base_url:
            return None
        return self.base_url.rstrip("/") + "/" + quote(str(_check_key(key)))


class BunnyStorage:
    name = "bunny"

    def __init__(self, client: bunny.BunnyClient):
        self.client = client

    def _wrap(self, fn, key, *args):
        try:
            return fn(str(_check_key(key)), *args)
        except bunny.BunnyNotFound as exc:
            raise StorageNotFound(key) from exc
        except bunny.BunnyError as exc:
            raise StorageError(str(exc)) from exc

    def save(self, key: str, data: bytes) -> None:
        self._wrap(self.client.put, key, data)

    def read(self, key: str) -> bytes:
        return self._wrap(self.client.get, key)

    def delete(self, key: str) -> None:
        self._wrap(self.client.delete, key)

    def exists(self, key: str) -> bool:
        try:
            self.read(key)
        except StorageNotFound:
            return False
        return True

    def url(self, key: str) -> str | None:
        return self.client.cdn_url(str(_check_key(key)))


def public_storage() -> Storage:
    backend = settings.MEDIA_PUBLIC_BACKEND
    if backend == "bunny":
        try:
            return BunnyStorage(bunny.client())
        except ImproperlyConfigured as exc:
            raise StorageError(str(exc)) from exc
    if backend == "local":
        return LocalStorage(settings.PUBLIC_MEDIA_ROOT, settings.PUBLIC_MEDIA_URL, name="local-public")
    raise ImproperlyConfigured(f"Unknown MEDIA_PUBLIC_BACKEND {backend!r} (expected 'bunny' or 'local').")


def private_storage() -> LocalStorage:
    return LocalStorage(settings.PRIVATE_MEDIA_ROOT, None, name="local-private")


def storage_for(visibility: str) -> Storage:
    from media.models import MediaAsset

    return public_storage() if visibility == MediaAsset.Visibility.PUBLIC else private_storage()
