# Generated by Django 6.0.8 on 2026-09-28 21:16

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True, default="", help_text="Short description shown on the careers page.")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "careers_department",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("position_label", models.CharField(default="General application", help_text="Legacy free-text `position`.", max_length=200)),
                ("position_title", models.CharField(blank=True, default="", help_text="Posting title snapshot at submission/assignment.", max_length=200)),
                ("department_name", models.CharField(blank=True, default="", help_text="Department snapshot (or area of interest).", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("SCREENING", "Screening"),
                            ("INTERVIEW", "Interview"),
                            ("OFFERED", "Offered"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="NEW",
                        max_length=12,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(choices=[("WEBSITE", "Website form"), ("IMPORT", "Legacy import")], default="WEBSITE", max_length=12)),
                ("ip", models.GenericIPAddressField(blank=True, help_text="Trusted client IP of the submission.", null=True)),
                ("name", models.CharField(help_text="Legacy `full_name`.", max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_e164", models.CharField(max_length=16)),
                ("location", models.CharField(max_length=255)),
                ("linkedin", models.URLField(max_length=300)),
                ("portfolio_website", models.URLField(blank=True, default="", max_length=300)),
                ("current_company", models.CharField(blank=True, default="", max_length=255)),
                ("current_role", models.CharField(blank=True, default="", max_length=255)),
                (
                    "total_experience",
                    models.CharField(blank=True, choices=[("0–1 years", "0–1 years"), ("1–3 years", "1–3 years"), ("3–5 years", "3–5 years"), ("5+ years", "5+ years")], default="", max_length=32),
                ),
                (
                    "relevant_experience",
                    models.CharField(blank=True, choices=[("0–1 years", "0–1 years"), ("1–3 years", "1–3 years"), ("3–5 years", "3–5 years"), ("5+ years", "5+ years")], default="", max_length=32),
                ),
                (
                    "current_salary",
                    models.CharField(
                        blank=True,
                        choices=[("Below ₹3 LPA", "Below ₹3 LPA"), ("₹3–5 LPA", "₹3–5 LPA"), ("₹5–8 LPA", "₹5–8 LPA"), ("₹8–12 LPA", "₹8–12 LPA"), ("₹12+ LPA", "₹12+ LPA")],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "expected_salary",
                    models.CharField(
                        blank=True,
                        choices=[("Below ₹3 LPA", "Below ₹3 LPA"), ("₹3–5 LPA", "₹3–5 LPA"), ("₹5–8 LPA", "₹5–8 LPA"), ("₹8–12 LPA", "₹8–12 LPA"), ("₹12+ LPA", "₹12+ LPA")],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "notice_period",
                    models.CharField(
                        blank=True, choices=[("Immediate", "Immediate"), ("15 days", "15 days"), ("1 month", "1 month"), ("2 months", "2 months"), ("3 months", "3 months")], default="", max_length=32
                    ),
                ),
                (
                    "heard_about_us",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LinkedIn", "LinkedIn"),
                            ("Job Portal", "Job Portal"),
                            ("Referral", "Referral"),
                            ("Company Website", "Company Website"),
                            ("Social Media", "Social Media"),
                            ("Other", "Other"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("availability", models.CharField(blank=True, default="", max_length=32)),
                ("cover_letter", models.TextField(blank=True, default="", help_text="Legacy `cover_note` ('Why Flarize?').")),
                ("declaration_accepted", models.BooleanField(default=False)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("portfolio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("resume", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "careers_job_application",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JobApplicationEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Application received"),
                            ("STATUS", "Status changed"),
                            ("ASSIGNED", "Linked to a position"),
                            ("ASSIGNEE", "Assignee changed"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("NOTE", "Note added"),
                        ],
                        max_length=12,
                    ),
                ),
                ("from_status", models.CharField(blank=True, default="", max_length=12)),
                ("to_status", models.CharField(blank=True, default="", max_length=12)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("actor_name", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("application", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="careers.jobapplication")),
            ],
            options={
                "db_table": "careers_job_application_event",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JobApplicationNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("author_name", models.CharField(blank=True, default="", max_length=150)),
                ("body", models.TextField()),
                ("application", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="careers.jobapplication")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "careers_job_application_note",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("seo_title", models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ("meta_description", models.TextField(blank=True, help_text="70–160 characters reads best in results")),
                ("canonical_url", models.URLField(blank=True, help_text="only when this URL duplicates another", max_length=1000)),
                ("og_title", models.CharField(blank=True, help_text="social share title; falls back to the SEO title", max_length=255)),
                ("og_description", models.TextField(blank=True, help_text="social share description; falls back to the meta description")),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("none", "No structured data"),
                            ("WebPage", "Web page"),
                            ("Article", "Article"),
                            ("FAQPage", "FAQ page"),
                            ("JobPosting", "Job posting"),
                            ("Organization", "Organization"),
                            ("BreadcrumbList", "Breadcrumb list"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("schema_extra", models.JSONField(blank=True, default=dict, help_text="only the structured fields the generator cannot infer from the record")),
                ("noindex", models.BooleanField(default=False, help_text="ask search engines not to index this URL")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(help_text="Public URL: /career/<slug>", max_length=220)),
                ("location", models.CharField(max_length=160)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("full_time", "Full-time"), ("part_time", "Part-time"), ("contract", "Contract"), ("internship", "Internship"), ("temporary", "Temporary")],
                        default="full_time",
                        max_length=16,
                    ),
                ),
                ("experience_required", models.CharField(blank=True, default="", help_text="e.g. '2–4 years' (PLAN: experience)", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("responsibilities", models.TextField(blank=True, default="", help_text="One per line.")),
                ("requirements", models.TextField(blank=True, default="", help_text="One per line.")),
                ("benefits", models.TextField(blank=True, default="", help_text="One per line.")),
                ("application_instructions", models.TextField(blank=True, default="")),
                ("opens_on", models.DateField(blank=True, help_text="First day applications are accepted (informational).", null=True)),
                ("application_deadline", models.DateField(blank=True, help_text="Last day to apply (PLAN: closes_on); JSON-LD validThrough.", null=True)),
                ("openings", models.PositiveSmallIntegerField(blank=True, help_text="Number of vacancies, when known.", null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("CLOSED", "Closed"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=12)),
                ("sort_order", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="positions", to="careers.department")),
                ("og_image", models.ForeignKey(blank=True, help_text="social share image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "careers_job_position",
                "ordering": ["sort_order", "-published_at", "-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="position",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="applications", to="careers.jobposition"),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True)), name="careers_department_name_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="careers_department_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.CheckConstraint(condition=models.Q(("slug__regex", "^[a-z0-9]+(?:-[a-z0-9]+)*$")), name="careers_department_slug_format"),
        ),
        migrations.AddIndex(
            model_name="jobapplicationevent",
            index=models.Index(fields=["application", "created_at"], name="careers_app_event_app_created"),
        ),
        migrations.AddConstraint(
            model_name="jobapplicationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["RECEIVED", "STATUS", "ASSIGNED", "ASSIGNEE", "ARCHIVED", "RESTORED", "NOTE"])), name="careers_job_application_event_kind_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplicationnote",
            index=models.Index(fields=["application", "created_at"], name="careers_app_note_app_created"),
        ),
        migrations.AddIndex(
            model_name="jobposition",
            index=models.Index(fields=["status", "sort_order"], name="careers_position_status_order"),
        ),
        migrations.AddIndex(
            model_name="jobposition",
            index=models.Index(fields=["department", "status"], name="careers_position_dept_status"),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="careers_job_position_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.CheckConstraint(condition=models.Q(("slug__regex", "^[a-z0-9]+(?:-[a-z0-9]+)*$")), name="careers_job_position_slug_format"),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "CLOSED", "ARCHIVED"])), name="careers_job_position_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("employment_type__in", ["full_time", "part_time", "contract", "internship", "temporary"])), name="careers_job_position_employment_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.CheckConstraint(condition=models.Q(("openings__isnull", True), ("openings__gte", 1), _connector="OR"), name="careers_job_position_openings_positive"),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("opens_on__isnull", True), ("application_deadline__isnull", True), ("application_deadline__gte", models.F("opens_on")), _connector="OR"),
                name="careers_job_position_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["status", "created_at"], name="careers_app_status_created"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["position", "status"], name="careers_app_position_status"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["email"], name="careers_app_email"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["phone_e164"], name="careers_app_phone"),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["NEW", "SCREENING", "INTERVIEW", "OFFERED", "HIRED", "REJECTED", "WITHDRAWN"])), name="careers_job_application_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(condition=models.Q(("source__in", ["WEBSITE", "IMPORT"])), name="careers_job_application_source_valid"),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(condition=models.Q(("phone_e164__regex", "^\\+[1-9][0-9]{6,14}$")), name="careers_job_application_phone_e164"),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_experience__in", ["", "0–1 years", "1–3 years", "3–5 years", "5+ years"])), name="careers_job_application_total_experience_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("relevant_experience__in", ["", "0–1 years", "1–3 years", "3–5 years", "5+ years"])), name="careers_job_application_relevant_experience_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_salary__in", ["", "Below ₹3 LPA", "₹3–5 LPA", "₹5–8 LPA", "₹8–12 LPA", "₹12+ LPA"])), name="careers_job_application_current_salary_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_salary__in", ["", "Below ₹3 LPA", "₹3–5 LPA", "₹5–8 LPA", "₹8–12 LPA", "₹12+ LPA"])), name="careers_job_application_expected_salary_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("notice_period__in", ["", "Immediate", "15 days", "1 month", "2 months", "3 months"])), name="careers_job_application_notice_period_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("heard_about_us__in", ["", "LinkedIn", "Job Portal", "Referral", "Company Website", "Social Media", "Other"])), name="careers_job_application_heard_about_us_valid"
            ),
        ),
    ]
