# Generated by Django 6.0.8 on 2026-09-28 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplicationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_status__in", ["", "NEW", "SCREENING", "INTERVIEW", "OFFERED", "HIRED", "REJECTED", "WITHDRAWN"])), name="careers_job_application_event_from_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplicationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("to_status__in", ["", "NEW", "SCREENING", "INTERVIEW", "OFFERED", "HIRED", "REJECTED", "WITHDRAWN"])), name="careers_job_application_event_to_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_type__in", ["none", "WebPage", "Article", "FAQPage", "JobPosting", "Organization", "BreadcrumbList"])), name="careers_job_position_schema_type_valid"
            ),
        ),
    ]
