# Generated by Django 6.0.8 on 2026-09-29 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_initial"),
        ("engineering", "0002_seed_rule_sets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.CharField(help_text="PROJ-<n> (core.sequences PROJ).", max_length=24)),
                ("quotation_version_uid", models.UUIDField(blank=True, help_text="quotations_version.uid (no FK, DV-128).", null=True)),
                ("agreement_uid", models.UUIDField(blank=True, help_text="agreements_agreement.uid (no FK, DV-128).", null=True)),
                ("site_inspection_uid", models.UUIDField(blank=True, help_text="site_inspections_inspection.uid (no FK, DV-128).", null=True)),
                ("lead_uid", models.UUIDField(blank=True, help_text="leads_lead.uid carried by the released inspection (no FK, DV-128).", null=True)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("PLANNED", "Planned"), ("IN_PROGRESS", "In progress"), ("COMMISSIONED", "Commissioned"), ("CLOSED", "Closed"), ("CANCELLED", "Cancelled")],
                        default="PLANNED",
                        max_length=14,
                    ),
                ),
                ("system_type", models.CharField(blank=True, choices=[("ON_GRID", "On-grid"), ("HYBRID", "Hybrid"), ("OFF_GRID", "Off-grid"), ("UNDECIDED", "Undecided")], default="", max_length=10)),
                ("tier", models.CharField(blank=True, default="", max_length=10)),
                ("size_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("phase", models.CharField(blank=True, choices=[("1P", "Single phase"), ("3P", "Three phase")], default="", max_length=4)),
                ("bom_lock", models.JSONField(blank=True, help_text="The locked BOM snapshot (lines, frozen prices, engineering verdict, acknowledgements).", null=True)),
                ("bom_locked_at", models.DateTimeField(blank=True, null=True)),
                ("cost_inputs", models.JSONField(blank=True, default=dict, help_text="Project cost inputs (pricing_internal).")),
                ("scheduled_on", models.DateField(blank=True, null=True)),
                ("commissioned_on", models.DateField(blank=True, null=True)),
                ("commissioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kseb_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("APPLIED", "Applied"),
                            ("FEASIBILITY_OK", "Feasibility approved"),
                            ("METER_INSTALLED", "Net meter installed"),
                            ("SYNCHRONISED", "Synchronised"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
                ("bom_locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="customers.customer")),
                ("engineering_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="engineering.run")),
                ("head", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "projects_project",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="projects_project_status_idx"),
                    models.Index(fields=["customer"], name="projects_project_customer_idx"),
                    models.Index(fields=["head"], name="projects_project_head_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("number",), name="projects_project_number_uniq"),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True), ("site_inspection_uid__isnull", False), models.Q(("status", "CANCELLED"), _negated=True)),
                        fields=("site_inspection_uid",),
                        name="projects_project_one_per_inspection",
                    ),
                    models.CheckConstraint(condition=models.Q(("status__in", ["PLANNED", "IN_PROGRESS", "COMMISSIONED", "CLOSED", "CANCELLED"])), name="projects_project_status_valid"),
                    models.CheckConstraint(condition=models.Q(("system_type__in", ["ON_GRID", "HYBRID", "OFF_GRID", "UNDECIDED", ""])), name="projects_project_system_type_valid"),
                    models.CheckConstraint(condition=models.Q(("phase__in", ["1P", "3P", ""])), name="projects_project_phase_valid"),
                    models.CheckConstraint(
                        condition=models.Q(("kseb_status__in", ["NOT_STARTED", "APPLIED", "FEASIBILITY_OK", "METER_INSTALLED", "SYNCHRONISED", "REJECTED"])), name="projects_project_kseb_status_valid"
                    ),
                    models.CheckConstraint(condition=models.Q(("size_kw__isnull", True), ("size_kw__gt", 0), _connector="OR"), name="projects_project_size_positive"),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["PLANNED", "CANCELLED"]), models.Q(("bom_lock__isnull", False), ("bom_locked_at__isnull", False)), _connector="OR"),
                        name="projects_project_started_has_bom_lock",
                    ),
                    models.CheckConstraint(condition=models.Q(models.Q(("status", "PLANNED"), _negated=True), ("bom_lock__isnull", True), _connector="OR"), name="projects_project_planned_unlocked"),
                    models.CheckConstraint(
                        condition=models.Q(models.Q(("status__in", ["COMMISSIONED", "CLOSED"]), _negated=True), ("commissioned_on__isnull", False), _connector="OR"),
                        name="projects_project_commissioned_on",
                    ),
                    models.CheckConstraint(condition=models.Q(models.Q(("status", "CLOSED"), _negated=True), ("closed_at__isnull", False), _connector="OR"), name="projects_project_closed_at"),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "CANCELLED"), _negated=True), models.Q(("cancelled_at__isnull", False), models.Q(("cancel_reason", ""), _negated=True)), _connector="OR"
                        ),
                        name="projects_project_cancel_reason",
                    ),
                ],
            },
        ),
    ]
