# Generated by Django 6.0.8 on 2026-09-29 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bom", "0001_initial"),
        ("catalog", "0001_initial"),
        ("pricing", "0003_current_price_view_and_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("PUBLISHED", "Published"), ("SUPERSEDED", "Superseded")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("config", models.JSONField(blank=True, help_text="flarize.pack-config/1 sections; NULL only for imported history versions (Flarize kept no copy).", null=True)),
                ("change_log", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_actor", models.CharField(blank=True, default="", help_text="Imported: the Flarize user id that approved the version when no platform user maps to it.", max_length=64)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("based_on", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="derived", to="packs.configversion")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "packs_config_version",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="ConfigPack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="ongrid-value-3, ongrid-base-3-up5sp, hybrid-value-3-b2 …", max_length=64)),
                ("system_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid")], max_length=8)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("size_key", models.CharField(max_length=10)),
                ("size_kw", models.DecimalField(decimal_places=2, max_digits=6)),
                ("phase", models.CharField(choices=[("1P", "Single phase"), ("3P", "Three phase")], max_length=2)),
                ("battery_config", models.CharField(blank=True, default="", help_text="'' on-grid; '0', '1', '2' hybrid.", max_length=4)),
                ("future_size_key", models.CharField(blank=True, default="", max_length=10)),
                ("future_size_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("is_future_ready", models.BooleanField(default=False)),
                ("battery_qty", models.PositiveSmallIntegerField(default=0)),
                ("profile_key", models.CharField(blank=True, default="", max_length=32)),
                ("market_rate_key", models.CharField(blank=True, default="", max_length=48)),
                ("display_name", models.CharField(blank=True, default="", max_length=120)),
                ("build_error", models.CharField(blank=True, default="", help_text="Why the BOM builder refused this pack (blank = built).", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("battery", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inverter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("pair_of", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="future_ready", to="packs.configpack")),
                ("panel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("structure_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="bom.structuretemplate")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("config_version", models.ForeignKey(db_column="version_id", on_delete=django.db.models.deletion.CASCADE, related_name="packs", to="packs.configversion")),
            ],
            options={
                "db_table": "packs_config_pack",
                "ordering": ["config_version_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.PositiveIntegerField()),
                ("content_release_uid", models.UUIDField(blank=True, help_text="The quotation ContentRelease (quotations_content_version) when one is published (DV).", null=True)),
                ("status", models.CharField(choices=[("PUBLISHED", "Published"), ("SUPERSEDED", "Superseded")], default="PUBLISHED", max_length=10)),
                ("published_at", models.DateTimeField()),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("publish_report", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("config_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="releases", to="packs.configversion")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("price_release", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pack_releases", to="pricing.pricerelease")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "packs_release",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="ReleasePack",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "release", "system_type", "tier", "size_key", "phase", "battery_config", "future_size_key", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("system_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid")], max_length=8)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("size_key", models.CharField(max_length=10)),
                ("size_kw", models.DecimalField(decimal_places=2, max_digits=6)),
                ("phase", models.CharField(choices=[("1P", "Single phase"), ("3P", "Three phase")], max_length=2)),
                ("battery_config", models.CharField(blank=True, default="", max_length=4)),
                ("future_size_key", models.CharField(blank=True, default="", max_length=10)),
                ("future_size_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("market_rate_key", models.CharField(max_length=48)),
                ("customer_price_incl_gst", models.DecimalField(decimal_places=2, max_digits=14)),
                ("customer_price_excl_gst", models.DecimalField(decimal_places=2, max_digits=14)),
                ("gst_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("landed_cost_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("gross_margin_pct", models.DecimalField(decimal_places=4, help_text="Fraction: (price excl. GST − landed cost) / price excl. GST.", max_digits=10)),
                ("bom", models.JSONField(help_text="Lines: sku, name, category, qty, unit list price, amount, GST rate/amount, source.")),
                ("pricing", models.JSONField(blank=True, default=dict, help_text="engines.pack_pricing result (FLAT roof, no transport); `internal` is internal data.")),
                ("display_name", models.CharField(max_length=120)),
                ("profile_key", models.CharField(blank=True, default="", max_length=32)),
                ("engineering_result", models.CharField(blank=True, default="", max_length=8)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="packs", to="packs.packrelease")),
            ],
            options={
                "db_table": "packs_release_pack",
                "ordering": ["release_id", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ConfigLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slot_key", models.CharField(help_text="The catalog category of the slot (panel, inverter …), 'fixed' or 'structure'.", max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("source", models.CharField(choices=[("SLOT", "Template slot"), ("MANUAL", "Pinned for this pack"), ("FIXED", "Fixed item"), ("STRUCTURE", "Structure (flat roof)")], max_length=10)),
                ("selection_method", models.CharField(blank=True, default="", max_length=40)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pack_config_lines", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="packs.configpack")),
            ],
            options={
                "db_table": "packs_config_line",
                "ordering": ["pack_id", "sort_order", "id"],
                "indexes": [models.Index(fields=["component"], name="packs_config_line_component")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("source__in", ["SLOT", "MANUAL", "FIXED", "STRUCTURE"])), name="packs_config_line_source_valid"),
                    models.CheckConstraint(condition=models.Q(("qty__gte", 0)), name="packs_config_line_qty_not_negative"),
                    models.CheckConstraint(
                        condition=models.Q(models.Q(("source__in", ["SLOT", "MANUAL"]), _negated=True), ("component__isnull", False), _connector="OR"), name="packs_config_line_slot_component"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfigPin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slot_key", models.CharField(max_length=32)),
                ("authoritative", models.BooleanField(default=True, help_text="Flarize derivedBy 'explicit' (an approved decision) vs a derived fallback.")),
                ("alternates", models.JSONField(blank=True, default=list, help_text="Component SKUs Sales may swap to when the slot lists none (registry approvedAlternates).")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pack_config_pins", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pins", to="packs.configpack")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "packs_config_pin",
                "ordering": ["pack_id", "slot_key"],
                "indexes": [models.Index(fields=["component"], name="packs_config_pin_component")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("pack", "slot_key"), name="packs_config_pin_slot_uniq")],
            },
        ),
        migrations.AddIndex(
            model_name="configversion",
            index=models.Index(fields=["status", "-number"], name="packs_config_version_status"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.UniqueConstraint(fields=("number",), name="packs_config_version_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.UniqueConstraint(models.Value(1), condition=models.Q(("status__in", ("DRAFT", "SUBMITTED")), ("deleted_at__isnull", True)), name="packs_config_version_one_open_draft"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.UniqueConstraint(models.Value(1), condition=models.Q(("status__in", ("APPROVED", "PUBLISHED")), ("deleted_at__isnull", True)), name="packs_config_version_one_current"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "PUBLISHED", "SUPERSEDED"])), name="packs_config_version_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="packs_config_version_number_positive"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.CheckConstraint(condition=models.Q(("config__isnull", False), ("status", "SUPERSEDED"), _connector="OR"), name="packs_config_version_config_required"),
        ),
        migrations.AddConstraint(
            model_name="configversion",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "REJECTED"), _negated=True), models.Q(("rejection_reason", ""), _negated=True), _connector="OR"), name="packs_config_version_rejection_reason"
            ),
        ),
        migrations.AddIndex(
            model_name="configpack",
            index=models.Index(fields=["config_version", "system_type", "tier"], name="packs_config_pack_lookup"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("config_version", "key"), name="packs_config_pack_key_uniq"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("config_version", "system_type", "tier", "size_key", "phase", "battery_config", "future_size_key"),
                name="packs_config_pack_natural_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID"])), name="packs_config_pack_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="packs_config_pack_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["1P", "3P"])), name="packs_config_pack_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("battery_config__in", ["", "0", "1", "2"])), name="packs_config_pack_battery_config_valid"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("size_key__regex", "^[0-9]+(\\.[0-9]{1,2})?(sp|tp)?$")), name="packs_config_pack_size_key_format"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(
                condition=models.Q(("future_size_key", ""), ("future_size_key__regex", "^[0-9]+(\\.[0-9]{1,2})?(sp|tp)?$"), _connector="OR"), name="packs_config_pack_future_size_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[a-z0-9][a-z0-9.-]{0,63}$")), name="packs_config_pack_key_format"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(condition=models.Q(("size_kw__gt", 0)), name="packs_config_pack_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="configpack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("future_size_key", ""), ("is_future_ready", False)), models.Q(("is_future_ready", True), models.Q(("future_size_key", ""), _negated=True)), _connector="OR"
                ),
                name="packs_config_pack_future_ready",
            ),
        ),
        migrations.AddConstraint(
            model_name="packrelease",
            constraint=models.UniqueConstraint(fields=("number",), name="packs_release_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="packrelease",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "PUBLISHED")), fields=("status",), name="packs_release_one_published"),
        ),
        migrations.AddConstraint(
            model_name="packrelease",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["PUBLISHED", "SUPERSEDED"])), name="packs_release_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="packrelease",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="packs_release_number_positive"),
        ),
        migrations.AddConstraint(
            model_name="packrelease",
            constraint=models.CheckConstraint(condition=models.Q(("payload_sha256__regex", "^[0-9a-f]{64}$")), name="packs_release_sha256_format"),
        ),
        migrations.AddIndex(
            model_name="releasepack",
            index=models.Index(fields=["release", "system_type", "tier", "size_kw"], name="packs_release_pack_lookup"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.UniqueConstraint(fields=("release", "key"), name="packs_release_pack_key_uniq"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID"])), name="packs_release_pack_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="packs_release_pack_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["1P", "3P"])), name="packs_release_pack_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("battery_config__in", ["", "0", "1", "2"])), name="packs_release_pack_battery_config_valid"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("size_key__regex", "^[0-9]+(\\.[0-9]{1,2})?(sp|tp)?$")), name="packs_release_pack_size_key_format"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[a-z0-9][a-z0-9.-]{0,63}$")), name="packs_release_pack_key_format"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(condition=models.Q(("customer_price_incl_gst__gt", 0)), name="packs_release_pack_price_positive"),
        ),
        migrations.AddConstraint(
            model_name="releasepack",
            constraint=models.CheckConstraint(
                condition=models.Q(("customer_price_excl_gst__gte", 0), ("gst_amount__gte", 0), ("landed_cost_total__gte", 0)), name="packs_release_pack_amounts_not_negative"
            ),
        ),
    ]
