# Generated by Django 6.0.8 on 2026-09-29 03:07
#
# devices_adms_request is a range-partitioned table (monthly on `received_at`), which Django cannot declare: the table,
# its DEFAULT partition, its indexes and the first monthly partitions are created with raw SQL at the end of this
# migration and the Django model is unmanaged (state only), like audit_log.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

ADMS_REQUEST_SQL = """
CREATE TABLE devices_adms_request (
    id bigserial NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    client_ip inet NULL,
    peer_ip inet NULL,
    method varchar(10) NOT NULL,
    path varchar(255) NOT NULL,
    raw_query text NOT NULL DEFAULT '',
    query jsonb NOT NULL DEFAULT '{}'::jsonb,
    headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    content_type varchar(160) NOT NULL DEFAULT '',
    device_serial varchar(80) NOT NULL DEFAULT '',
    -- the device the request resolved to; no FK (like the model's db_constraint=False): evidence is append-only and
    -- outlives its device, and a partitioned log must not block flushing or dropping devices
    device_id bigint NULL,
    request_kind varchar(30) NOT NULL DEFAULT 'UNKNOWN',
    table_name varchar(40) NOT NULL DEFAULT '',
    body bytea NULL,
    body_bytes integer NOT NULL DEFAULT 0,
    body_text text NOT NULL DEFAULT '',
    body_encoding varchar(30) NOT NULL DEFAULT '',
    body_truncated boolean NOT NULL DEFAULT false,
    response_status smallint NOT NULL DEFAULT 200,
    response_body text NOT NULL DEFAULT '',
    records_parsed integer NOT NULL DEFAULT 0,
    records_new integer NOT NULL DEFAULT 0,
    records_duplicate integer NOT NULL DEFAULT 0,
    records_invalid integer NOT NULL DEFAULT 0,
    parse_error text NOT NULL DEFAULT '',
    extra jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT devices_adms_request_pkey PRIMARY KEY (id, received_at),
    CONSTRAINT devices_adms_request_kind_valid CHECK (request_kind IN (
        'HANDSHAKE', 'ATTLOG', 'OPERLOG', 'USERINFO', 'ATTPHOTO', 'BIODATA', 'CDATA', 'GETREQUEST', 'DEVICECMD',
        'REGISTRY', 'PING', 'UNKNOWN', 'UNSTORABLE'
    )),
    -- the stored copy of a body is capped at 1 MiB (body_bytes keeps the size as received)
    CONSTRAINT devices_adms_request_body_capped CHECK (body IS NULL OR octet_length(body) <= 1048576),
    CONSTRAINT devices_adms_request_counts_valid CHECK (
        body_bytes >= 0 AND records_parsed >= 0 AND records_new >= 0 AND records_duplicate >= 0 AND records_invalid >= 0
    )
) PARTITION BY RANGE (received_at);

CREATE TABLE devices_adms_request_default PARTITION OF devices_adms_request DEFAULT;

-- The request log is read newest first, by serial, or by resolved device (GET devices/adms/requests/).
CREATE INDEX devices_adms_request_received_idx ON devices_adms_request (received_at);
CREATE INDEX devices_adms_request_serial_idx ON devices_adms_request (device_serial, received_at);
CREATE INDEX devices_adms_request_device_idx ON devices_adms_request (device_id, received_at);
"""

ADMS_REQUEST_DROP_SQL = "DROP TABLE IF EXISTS devices_adms_request CASCADE;"


def create_initial_partitions(apps, schema_editor):
    """The current UTC month and the next two; ``devices.tasks.purge_adms_evidence`` keeps the window moving."""
    today = django.utils.timezone.now().date()
    quote = schema_editor.connection.ops.quote_name
    for offset in range(3):
        index = today.year * 12 + today.month - 1 + offset
        start = (index // 12, index % 12 + 1)
        end = ((index + 1) // 12, (index + 1) % 12 + 1)
        name = f"devices_adms_request_y{start[0]:04d}m{start[1]:02d}"
        schema_editor.execute(
            f"CREATE TABLE IF NOT EXISTS {quote(name)} PARTITION OF devices_adms_request "
            f"FOR VALUES FROM ('{start[0]:04d}-{start[1]:02d}-01 00:00:00+00') TO ('{end[0]:04d}-{end[1]:02d}-01 00:00:00+00')"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_outbox_claim_lease_and_backoff"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmsRequest",
            fields=[
                ("pk", models.CompositePrimaryKey("id", "received_at", blank=True, editable=False, primary_key=True, serialize=False)),
                ("id", models.BigIntegerField(db_default=models.Func(models.Value("devices_adms_request_id_seq"), function="nextval", output_field=models.BigIntegerField()), editable=False)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("client_ip", models.GenericIPAddressField(blank=True, help_text="Trusted client address (X-Forwarded-For only through TRUSTED_PROXIES).", null=True)),
                ("peer_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(help_text="Request path with the device token redacted.", max_length=255)),
                ("raw_query", models.TextField(blank=True, default="")),
                ("query", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("content_type", models.CharField(blank=True, default="", max_length=160)),
                ("device_serial", models.CharField(blank=True, default="", help_text="The serial the request claimed (SN).", max_length=80)),
                (
                    "request_kind",
                    models.CharField(
                        choices=[
                            ("HANDSHAKE", "Handshake"),
                            ("ATTLOG", "Attendance log"),
                            ("OPERLOG", "Operation log"),
                            ("USERINFO", "User information"),
                            ("ATTPHOTO", "Attendance photo"),
                            ("BIODATA", "Biometric template"),
                            ("CDATA", "Other table"),
                            ("GETREQUEST", "Command poll"),
                            ("DEVICECMD", "Command result"),
                            ("REGISTRY", "Registry"),
                            ("PING", "Ping"),
                            ("UNKNOWN", "Unknown"),
                            ("UNSTORABLE", "Unstorable"),
                        ],
                        default="UNKNOWN",
                        max_length=30,
                    ),
                ),
                ("table_name", models.CharField(blank=True, default="", max_length=40)),
                ("body", models.BinaryField(blank=True, null=True)),
                ("body_bytes", models.PositiveIntegerField(default=0, help_text="Size of the body as received (the stored copy is capped at 1 MiB).")),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_encoding", models.CharField(blank=True, default="", max_length=30)),
                ("body_truncated", models.BooleanField(default=False)),
                ("response_status", models.PositiveSmallIntegerField(default=200)),
                ("response_body", models.TextField(blank=True, default="")),
                ("records_parsed", models.PositiveIntegerField(default=0)),
                ("records_new", models.PositiveIntegerField(default=0)),
                ("records_duplicate", models.PositiveIntegerField(default=0)),
                ("records_invalid", models.PositiveIntegerField(default=0)),
                ("parse_error", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "devices_adms_request",
                "ordering": ["-received_at", "-id"],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(help_text="Stable identity, e.g. OFFICE-001-AGENT (unique among live agents).", max_length=60)),
                ("name", models.CharField(max_length=120)),
                ("agent_version", models.CharField(blank=True, default="", max_length=40)),
                ("hostname", models.CharField(blank=True, default="", max_length=120)),
                ("platform", models.CharField(blank=True, default="", max_length=120)),
                ("local_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_device_contact_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("queued_records", models.PositiveIntegerField(default=0)),
                ("failed_uploads", models.PositiveIntegerField(default=0)),
                ("heartbeat_interval_seconds", models.PositiveIntegerField(default=60)),
                ("sync_interval_seconds", models.PositiveIntegerField(default=300)),
                ("offline_after_seconds", models.PositiveIntegerField(default=300)),
                ("degraded_queue_threshold", models.PositiveIntegerField(default=500)),
                ("settings", models.JSONField(blank=True, default=dict, help_text="Free agent settings returned with the configuration.")),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("credential", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="core.servicecredential")),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="device_agents", to="hr.office")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "devices_agent",
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=120)),
                ("serial_number", models.CharField(blank=True, help_text="The serial the hardware reported (unique among live devices).", max_length=80, null=True)),
                ("expected_serial", models.CharField(blank=True, help_text="The serial the terminal is required to report (identity pin).", max_length=80, null=True)),
                ("expected_mac", models.CharField(blank=True, default="", help_text="The MAC the terminal is required to report (aa:bb:cc:dd:ee:ff).", max_length=17)),
                ("mac_address", models.CharField(blank=True, default="", help_text="The MAC the hardware reported.", max_length=17)),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="LAN address; null until an agent discovers it.", null=True)),
                ("port", models.PositiveIntegerField(default=4370)),
                ("protocol", models.CharField(choices=[("ZK_TCP", "ZK over TCP"), ("ZK_UDP", "ZK over UDP")], default="ZK_TCP", max_length=6)),
                ("comm_password", models.PositiveIntegerField(default=0, help_text="The terminal's communication key (never returned by the API).")),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=15)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("firmware_version", models.CharField(blank=True, default="", max_length=120)),
                ("platform", models.CharField(blank=True, default="", max_length=120)),
                ("adms_enabled", models.BooleanField(default=False)),
                ("adms_token_hash", models.CharField(blank=True, help_text="sha256 of the /iclock/ path token.", max_length=64, null=True)),
                ("adms_allowed_ips", models.JSONField(blank=True, default=list, help_text="CIDRs the terminal may push from; empty = any address.")),
                ("adms_registration_state", models.CharField(choices=[("NEVER_SEEN", "Never seen"), ("REGISTERED", "Registered")], default="NEVER_SEEN", max_length=20)),
                ("adms_last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("adms_last_handshake_at", models.DateTimeField(blank=True, null=True)),
                ("adms_last_push_at", models.DateTimeField(blank=True, null=True)),
                ("adms_last_command_poll_at", models.DateTimeField(blank=True, null=True)),
                ("adms_source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("adms_request_count", models.PositiveIntegerField(default=0)),
                ("adms_options", models.JSONField(blank=True, default=dict, help_text="What the terminal volunteered at its last handshake.")),
                ("adms_server", models.CharField(blank=True, default="", max_length=120)),
                ("adms_port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "identity_status",
                    models.CharField(choices=[("VERIFIED", "Verified"), ("IDENTITY_MISMATCH", "Identity mismatch"), ("UNVERIFIED", "Unverified")], default="UNVERIFIED", max_length=20),
                ),
                ("identity_message", models.TextField(blank=True, default="")),
                ("identity_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, help_text="Last time an agent reached the terminal.", null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_punch_at", models.DateTimeField(blank=True, help_text="Newest punch received (device wall clock in the office zone).", null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("clock_offset_seconds", models.IntegerField(blank=True, help_text="Terminal clock minus real time, measured on each info read (A10; never corrected).", null=True)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("attendance_count", models.PositiveIntegerField(default=0)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("users_read_requested_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="devices", to="devices.agent")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="devices", to="hr.office")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "devices_device",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeviceUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("pin", models.CharField(help_text="The terminal's user id, always a string ('1' and 'EMP001' both occur).", max_length=80)),
                ("device_uid", models.IntegerField(blank=True, help_text="The terminal's internal row id.", null=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("privilege", models.SmallIntegerField(blank=True, help_text="The terminal's privilege byte (unrelated to platform roles).", null=True)),
                ("card", models.CharField(blank=True, default="", max_length=40)),
                ("group_id", models.CharField(blank=True, default="", max_length=40)),
                ("has_password", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="device_users", to="devices.device")),
                ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="device_users", to="hr.employee")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "devices_device_user",
                "ordering": ["device_id", "pin", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("device_platform", models.CharField(blank=True, default="", help_text="Empty = any platform.", max_length=120)),
                ("firmware_version", models.CharField(blank=True, default="", help_text="Empty = any firmware.", max_length=120)),
                ("field", models.CharField(choices=[("status", "status"), ("punch", "punch")], max_length=30)),
                ("raw_value", models.IntegerField()),
                ("meaning_type", models.CharField(choices=[("VERIFY_MODE", "Verify mode"), ("PUNCH_DIRECTION", "Punch direction")], max_length=30)),
                ("meaning_code", models.CharField(help_text="FACE, CARD, FINGERPRINT, PASSWORD, IN, OUT, …", max_length=40)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("confidence", models.CharField(choices=[("VERIFIED", "Verified (controlled test)"), ("ASSUMED", "Assumed"), ("UNKNOWN", "Unknown")], default="UNKNOWN", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "devices_protocol_mapping",
                "ordering": ["field", "raw_value", "device_platform", "firmware_version", "id"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sync_type", models.CharField(choices=[("INFO", "Device information"), ("USERS", "User table"), ("ATTENDANCE", "Attendance")], max_length=20)),
                ("status", models.CharField(choices=[("SUCCESS", "Success"), ("PARTIAL", "Partial"), ("FAILED", "Failed")], max_length=20)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("records_read", models.PositiveIntegerField(default=0)),
                ("records_new", models.PositiveIntegerField(default=0)),
                ("records_duplicate", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sync_logs", to="devices.agent")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sync_logs", to="devices.device")),
            ],
            options={
                "db_table": "devices_sync_log",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdmsUnknownDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("serial_number", models.CharField(max_length=80)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("last_source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_path", models.CharField(blank=True, default="", max_length=255)),
                ("last_body_excerpt", models.TextField(blank=True, default="")),
                (
                    "last_reason",
                    models.CharField(
                        choices=[("UNKNOWN_SERIAL", "No registered device has this serial"), ("TOKEN_MISMATCH", "The serial and the device token do not belong together")],
                        default="UNKNOWN_SERIAL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "devices_adms_unknown_device",
                "ordering": ["-last_seen_at", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("serial_number",), name="devices_adms_unknown_serial_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("serial_number", ""), _negated=True), name="devices_adms_unknown_serial_not_blank"),
                    models.CheckConstraint(condition=models.Q(("last_reason__in", ["UNKNOWN_SERIAL", "TOKEN_MISMATCH"])), name="devices_adms_unknown_reason_valid"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="devices_agent_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(condition=models.Q(("code", ""), _negated=True), name="devices_agent_code_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(condition=models.Q(("heartbeat_interval_seconds__gte", 10), ("heartbeat_interval_seconds__lte", 3600)), name="devices_agent_heartbeat_interval_range"),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(condition=models.Q(("sync_interval_seconds__gte", 30), ("sync_interval_seconds__lte", 86400)), name="devices_agent_sync_interval_range"),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(condition=models.Q(("offline_after_seconds__gte", models.F("heartbeat_interval_seconds"))), name="devices_agent_offline_after_heartbeat"),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(condition=models.Q(("degraded_queue_threshold__gte", 1)), name="devices_agent_degraded_threshold_positive"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["office", "is_active"], name="devices_device_office_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["agent", "is_active"], name="devices_device_agent_idx"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("serial_number__isnull", False)), fields=("serial_number",), name="devices_device_serial_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("expected_serial__isnull", False)), fields=("expected_serial",), name="devices_device_expected_serial_live_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(condition=models.Q(("adms_token_hash__isnull", False)), fields=("adms_token_hash",), name="devices_device_adms_token_uniq"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="devices_device_name_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("serial_number__isnull", True), models.Q(("serial_number", ""), _negated=True), _connector="OR"), name="devices_device_serial_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_serial__isnull", True), models.Q(("expected_serial", ""), _negated=True), _connector="OR"), name="devices_device_expected_serial_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_mac", ""), ("expected_mac__regex", "^[0-9a-f]{2}(:[0-9a-f]{2}){5}$"), _connector="OR"), name="devices_device_expected_mac_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("mac_address", ""), ("mac_address__regex", "^[0-9a-f]{2}(:[0-9a-f]{2}){5}$"), _connector="OR"), name="devices_device_mac_format"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("port__gte", 1), ("port__lte", 65535)), name="devices_device_port_range"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("timeout_seconds__gte", 1), ("timeout_seconds__lte", 120)), name="devices_device_timeout_range"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("protocol__in", ["ZK_TCP", "ZK_UDP"])), name="devices_device_protocol_valid"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("identity_status__in", ["VERIFIED", "IDENTITY_MISMATCH", "UNVERIFIED"])), name="devices_device_identity_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("adms_registration_state__in", ["NEVER_SEEN", "REGISTERED"])), name="devices_device_adms_registration_valid"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("adms_token_hash__isnull", True), ("adms_token_hash__regex", "^[0-9a-f]{64}$"), _connector="OR"), name="devices_device_adms_token_hash_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(condition=models.Q(("adms_enabled", False), ("adms_token_hash__isnull", False), _connector="OR"), name="devices_device_adms_enabled_has_token"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("ip_address__isnull", False), ("expected_serial__isnull", False), ("serial_number__isnull", False), _connector="OR"), name="devices_device_locatable"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("adms_port__isnull", True), models.Q(("adms_port__gte", 1), ("adms_port__lte", 65535)), _connector="OR"), name="devices_device_adms_port_range"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceuser",
            index=models.Index(fields=["pin"], name="devices_device_user_pin_idx"),
        ),
        migrations.AddConstraint(
            model_name="deviceuser",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("device", "pin"), name="devices_device_user_pin_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="deviceuser",
            constraint=models.CheckConstraint(condition=models.Q(("pin", ""), _negated=True), name="devices_device_user_pin_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="protocolmapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("device_platform", "firmware_version", "field", "raw_value"), name="devices_protocol_mapping_scope_live_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="protocolmapping",
            constraint=models.CheckConstraint(condition=models.Q(("field__in", ["status", "punch"])), name="devices_protocol_mapping_field_valid"),
        ),
        migrations.AddConstraint(
            model_name="protocolmapping",
            constraint=models.CheckConstraint(condition=models.Q(("meaning_type__in", ["VERIFY_MODE", "PUNCH_DIRECTION"])), name="devices_protocol_mapping_meaning_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="protocolmapping",
            constraint=models.CheckConstraint(condition=models.Q(("confidence__in", ["VERIFIED", "ASSUMED", "UNKNOWN"])), name="devices_protocol_mapping_confidence_valid"),
        ),
        migrations.AddConstraint(
            model_name="protocolmapping",
            constraint=models.CheckConstraint(condition=models.Q(("meaning_code", ""), _negated=True), name="devices_protocol_mapping_meaning_not_blank"),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["device", "sync_type", "-started_at", "-id"], name="devices_sync_log_device_idx"),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["agent", "-started_at"], name="devices_sync_log_agent_idx"),
        ),
        migrations.AddConstraint(
            model_name="synclog",
            constraint=models.CheckConstraint(condition=models.Q(("sync_type__in", ["INFO", "USERS", "ATTENDANCE"])), name="devices_sync_log_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="synclog",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["SUCCESS", "PARTIAL", "FAILED"])), name="devices_sync_log_status_valid"),
        ),
        migrations.RunSQL(ADMS_REQUEST_SQL, ADMS_REQUEST_DROP_SQL),
        migrations.RunPython(create_initial_partitions, migrations.RunPython.noop),
    ]
