# Generated by Django 6.0.8 on 2026-09-28 17:59

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyMap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("CMS", "CMS (blog_cms)"),
                            ("BACKEND", "Main backend (GoldenApp)"),
                            ("FLARIZE", "Flarize JSON"),
                            ("PA", "Purchase Agreement page"),
                            ("SI", "Site Inspection V2"),
                            ("ESSL", "eSSL attendance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_table", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=128)),
                ("target_table", models.CharField(max_length=64)),
                ("target_id", models.BigIntegerField()),
                ("imported_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "core_legacy_map",
                "indexes": [models.Index(fields=["target_table", "target_id"], name="core_legacy_map_target_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("source_system", "source_table", "source_id"), name="core_legacy_map_source_uniq"),
                    models.CheckConstraint(condition=models.Q(("source_system__in", ["CMS", "BACKEND", "FLARIZE", "PA", "SI", "ESSL"])), name="core_legacy_map_source_system_valid"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("aggregate_type", models.CharField(blank=True, default="", max_length=64)),
                ("aggregate_uid", models.UUIDField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("dedup_key", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("parked_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("delivered", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "core_outbox_event",
                "indexes": [
                    models.Index(condition=models.Q(("parked_at__isnull", True), ("processed_at__isnull", True)), fields=["id"], name="core_outbox_pending_idx"),
                    models.Index(fields=["aggregate_type", "aggregate_uid"], name="core_outbox_aggregate_idx"),
                    models.Index(condition=models.Q(("parked_at__isnull", False)), fields=["parked_at"], name="core_outbox_parked_idx"),
                ],
                "constraints": [models.UniqueConstraint(condition=models.Q(("dedup_key__isnull", False)), fields=("dedup_key",), name="core_outbox_event_dedup_key_uniq")],
            },
        ),
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                ("pk", models.CompositePrimaryKey("kind", "period_key", blank=True, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=16)),
                ("period_key", models.CharField(blank=True, default="", max_length=16)),
                ("next_value", models.BigIntegerField(default=1)),
            ],
            options={
                "db_table": "core_sequence_counter",
                "constraints": [models.CheckConstraint(condition=models.Q(("next_value__gte", 1)), name="core_sequence_counter_next_value_positive")],
            },
        ),
        migrations.CreateModel(
            name="SystemException",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(choices=[("api", "API request"), ("task", "Celery task"), ("outbox", "Outbox handler"), ("command", "Management command")], default="api", max_length=16)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("method", models.CharField(blank=True, default="", max_length=8)),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("user_uid", models.UUIDField(blank=True, null=True)),
                ("exception_type", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, default="")),
                ("traceback", models.TextField(blank=True, default="")),
                ("context", models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                "db_table": "core_system_exception",
                "indexes": [models.Index(fields=["-occurred_at"], name="core_sysexc_occurred_idx"), models.Index(fields=["exception_type", "occurred_at"], name="core_sysexc_type_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(("source__in", ["api", "task", "outbox", "command"])), name="core_system_exception_source_valid")],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_feature_flag",
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("key",), name="core_feature_flag_key_uniq")],
            },
        ),
        migrations.CreateModel(
            name="ServiceCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("kind", models.CharField(choices=[("AGENT", "Office agent")], max_length=16)),
                ("name", models.CharField(max_length=120)),
                ("token_prefix", models.CharField(db_index=True, max_length=16)),
                ("token_hash", models.CharField(max_length=64)),
                ("issued_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("bound_object_id", models.BigIntegerField(blank=True, null=True)),
                ("bound_content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_service_credential",
                "indexes": [models.Index(fields=["bound_content_type", "bound_object_id"], name="core_svc_cred_bound_idx")],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("token_prefix",), name="core_service_credential_prefix_uniq"),
                    models.CheckConstraint(condition=models.Q(("kind__in", ["AGENT"])), name="core_service_credential_kind_valid"),
                ],
            },
        ),
    ]
