# Generated by Django 6.0.8 on 2026-09-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="claimed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
