# Generated by Django 6.0.8 on 2026-09-29 14:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("customers", "0002_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.CharField(help_text="SV-YYYYMMDD-NNNN (core_sequence_counter SV, office-local day).", max_length=24)),
                ("visit_date", models.DateField()),
                ("origin", models.CharField(choices=[("PRE_SALE", "Pre-sale"), ("AGREEMENT", "Purchase agreement")], default="PRE_SALE", max_length=14)),
                ("system_type", models.CharField(choices=[("ON_GRID", "On-grid"), ("HYBRID", "Hybrid"), ("UNDECIDED", "Undecided")], default="UNDECIDED", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CUSTOMER_APPROVAL_PENDING", "Customer approval pending"),
                            ("APPROVED", "Approved"),
                            ("INSTALLATION_READY", "Installation ready"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUIRED", "Revision required"),
                            ("ON_HOLD", "On hold"),
                        ],
                        default="DRAFT",
                        max_length=28,
                    ),
                ),
                (
                    "held_from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CUSTOMER_APPROVAL_PENDING", "Customer approval pending"),
                            ("APPROVED", "Approved"),
                            ("INSTALLATION_READY", "Installation ready"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUIRED", "Revision required"),
                            ("ON_HOLD", "On hold"),
                        ],
                        default="",
                        help_text="The status ON_HOLD returns to on resume.",
                        max_length=28,
                    ),
                ),
                (
                    "complexity_status",
                    models.CharField(
                        choices=[("NOT_ASSESSED", "Not assessed"), ("ROUTINE", "Routine"), ("ENGINEERING_REVIEW_REQUIRED", "Engineering review required")], default="NOT_ASSESSED", max_length=28
                    ),
                ),
                ("complexity_reason", models.TextField(blank=True, default="")),
                ("agreement_uid", models.UUIDField(blank=True, help_text="The purchase agreement in force (agreements context; linked by event, no FK).", null=True)),
                ("agreement_number", models.CharField(blank=True, default="", max_length=32)),
                ("agreement_version", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("quotation_version_uid", models.UUIDField(blank=True, null=True)),
                ("address", models.TextField(blank=True, default="")),
                ("pincode", models.CharField(blank=True, default="", max_length=6)),
                ("location", models.CharField(blank=True, default="", max_length=120)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("google_map_link", models.CharField(blank=True, default="", max_length=500)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("location_accuracy_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("location_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "road_access",
                    models.CharField(blank=True, choices=[("GOOD", "Good"), ("LIMITED", "Limited"), ("DIFFICULT", "Difficult"), ("NO_VEHICLE", "No vehicle access")], default="", max_length=16),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[("CAR", "Car"), ("PICKUP_VAN", "Pickup / Van"), ("TRUCK", "Truck"), ("MANUAL", "Manual movement only"), ("NOT_ASSESSED", "Not assessed")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("access_remarks", models.TextField(blank=True, default="")),
                ("building_type", models.CharField(blank=True, default="", max_length=60)),
                ("no_of_floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("roof_type", models.CharField(blank=True, choices=[("RCC_FLAT", "RCC flat"), ("TILE", "Tile"), ("SHEET_METAL", "Sheet metal"), ("OTHER", "Other")], default="", max_length=16)),
                ("roof_strength", models.CharField(blank=True, choices=[("GOOD", "Good"), ("REVIEW", "Needs review"), ("POOR", "Poor")], default="", max_length=16)),
                (
                    "roof_accessibility",
                    models.CharField(blank=True, choices=[("EASY", "Easy"), ("RESTRICTED", "Restricted"), ("DIFFICULT", "Difficult"), ("UNSAFE", "Unsafe")], default="", max_length=16),
                ),
                ("roof_accessibility_reason", models.TextField(blank=True, default="")),
                (
                    "roof_condition",
                    models.CharField(blank=True, choices=[("GOOD", "Good"), ("FAIR", "Fair"), ("NEEDS_REPAIR", "Needs repair"), ("REVIEW_REQUIRED", "Review required")], default="", max_length=16),
                ),
                ("installation_difficulty", models.CharField(blank=True, choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="", max_length=8)),
                ("roof_length_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("roof_width_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("available_area_m2", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("usable_area_m2", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("roof_slope", models.CharField(blank=True, choices=[("FLAT", "Flat"), ("LOW", "Low"), ("MEDIUM", "Medium"), ("STEEP", "Steep")], default="", max_length=8)),
                (
                    "direction_facing",
                    models.CharField(
                        blank=True,
                        choices=[("N", "North"), ("NE", "North-east"), ("E", "East"), ("SE", "South-east"), ("S", "South"), ("SW", "South-west"), ("W", "West"), ("NW", "North-west")],
                        default="",
                        max_length=4,
                    ),
                ),
                ("morning_shading", models.CharField(blank=True, choices=[("NONE", "None"), ("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="", max_length=8)),
                ("afternoon_shading", models.CharField(blank=True, choices=[("NONE", "None"), ("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="", max_length=8)),
                ("shade_source", models.CharField(blank=True, default="", max_length=255)),
                ("shading_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "generation_impact",
                    models.CharField(blank=True, choices=[("NONE", "None"), ("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("REQUIRES_REVIEW", "Requires review")], default="", max_length=16),
                ),
                ("shading_remarks", models.TextField(blank=True, default="")),
                ("consumer_number", models.CharField(blank=True, default="", max_length=20)),
                ("consumer_name", models.CharField(blank=True, default="", max_length=255)),
                ("registered_phone_e164", models.CharField(blank=True, default="", max_length=16)),
                ("phase", models.CharField(blank=True, choices=[("1P", "Single phase"), ("3P", "Three phase"), ("NC", "Not confirmed")], default="", max_length=4)),
                ("connected_load_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("sanctioned_load_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("meter_number", models.CharField(blank=True, default="", max_length=40)),
                (
                    "tariff",
                    models.CharField(
                        blank=True, choices=[("LT_I", "LT I"), ("LT_II", "LT II"), ("LT_III", "LT III"), ("LT_IV", "LT IV"), ("NOT_CONFIRMED", "Not confirmed")], default="", max_length=13
                    ),
                ),
                (
                    "neutral_link",
                    models.CharField(blank=True, choices=[("AVAILABLE", "Available"), ("NOT_AVAILABLE", "Not available"), ("NEEDS_MODIFICATION", "Needs modification")], default="", max_length=20),
                ),
                (
                    "termination_point",
                    models.CharField(blank=True, choices=[("AVAILABLE", "Available"), ("NOT_AVAILABLE", "Not available"), ("NEEDS_MODIFICATION", "Needs modification")], default="", max_length=20),
                ),
                (
                    "distribution_board",
                    models.CharField(blank=True, choices=[("AVAILABLE", "Available"), ("NOT_AVAILABLE", "Not available"), ("NEEDS_MODIFICATION", "Needs modification")], default="", max_length=20),
                ),
                (
                    "earthing",
                    models.CharField(blank=True, choices=[("AVAILABLE", "Available"), ("NOT_AVAILABLE", "Not available"), ("NEEDS_MODIFICATION", "Needs modification")], default="", max_length=20),
                ),
                ("electrical_remarks", models.TextField(blank=True, default="")),
                ("wheeling_required", models.BooleanField(blank=True, null=True)),
                ("ac_cable_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("dc_cable_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("la_cable_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("battery_cable_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("battery_cable_route", models.TextField(blank=True, default="")),
                ("cable_routing_remarks", models.TextField(blank=True, default="")),
                ("site_suitability", models.CharField(blank=True, choices=[("SUITABLE", "Suitable"), ("CONDITIONAL", "Conditional"), ("NOT_SUITABLE", "Not suitable")], default="", max_length=16)),
                ("suitability_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("final_recommendation", models.TextField(blank=True, default="")),
                ("engineer_remarks", models.TextField(blank=True, default="")),
                ("additional_requirements", models.TextField(blank=True, default="")),
                ("approval_remarks", models.TextField(blank=True, default="")),
                ("has_location_restrictions", models.BooleanField(default=False)),
                ("customer_restrictions", models.TextField(blank=True, default="")),
                ("customer_location_remarks", models.TextField(blank=True, default="")),
                ("quoted_size_kw", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("quoted_panel_capacity_w", models.PositiveIntegerField(blank=True, null=True)),
                ("quoted_structure_type", models.CharField(blank=True, default="", max_length=32)),
                ("quoted_structure_material", models.CharField(blank=True, default="", max_length=64)),
                (
                    "site_structure_type",
                    models.CharField(
                        blank=True,
                        choices=[("SUFFICIENT", "Sufficient"), ("ADDITIONAL_REQUIRED", "Additional structure required"), ("REQUIRES_ENGINEERING_REVIEW", "Requires engineering review")],
                        default="",
                        max_length=28,
                    ),
                ),
                ("walkway_required", models.BooleanField(default=False)),
                ("walkway_length_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("walkway_width_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("ladder_required", models.BooleanField(default=False)),
                ("ladder_length_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("sliding_door_required", models.BooleanField(default=False)),
                ("sliding_door_width_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("sliding_door_height_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("elevated_height_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("panel_width_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("panel_height_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("panel_area_m2", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("equipment_width_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("equipment_height_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("equipment_area_m2", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("on_hold_reason", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="customers.customer")),
                ("engineer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("pre_sale_source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="site_inspections.inspection")),
                ("quoted_battery", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="catalog.component")),
                ("quoted_inverter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="catalog.component")),
                ("quoted_panel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="catalog.component")),
                ("released_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "site_inspections_inspection",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("PANEL_AREA", "Panel area"),
                            ("EQUIPMENT_AREA", "Equipment area"),
                            ("ROOF", "Roof"),
                            ("ACCESS", "Site access"),
                            ("ELECTRICAL", "Electrical"),
                            ("CABLE_ROUTE", "Cable route"),
                            ("SHADING", "Shading"),
                            ("ADDITIONAL_WORK", "Additional work"),
                            ("EVIDENCE", "Evidence"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=24,
                    ),
                ),
                ("stage", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="media.mediaasset")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="site_inspections.inspection")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "site_inspections_photo",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("stage", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("STRUCTURE", "Structure"),
                            ("CABLE", "Cable"),
                            ("EARTHING", "Earthing"),
                            ("ELECTRICAL", "Electrical"),
                            ("CIVIL", "Civil"),
                            ("ACCESS", "Access"),
                            ("SAFETY", "Safety"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=24,
                    ),
                ),
                ("note", models.TextField()),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="site_inspections.inspection")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("photos", models.ManyToManyField(blank=True, db_table="site_inspections_observation_photo", related_name="observations", to="site_inspections.photo")),
            ],
            options={
                "db_table": "site_inspections_observation",
                "ordering": ["inspection_id", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="inspection",
            name="equipment_photo",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="site_inspections.photo"),
        ),
        migrations.AddField(
            model_name="inspection",
            name="panel_photo",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="site_inspections.photo"),
        ),
        migrations.CreateModel(
            name="EquipmentAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("equipment_type", models.CharField(choices=[("ON_GRID_INVERTER", "On-grid inverter"), ("HYBRID_INVERTER", "Hybrid inverter"), ("HYBRID_BATTERY", "Hybrid battery")], max_length=20)),
                ("checks_version", models.CharField(max_length=8)),
                ("results", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("NOT_STARTED", "Not started"), ("IN_PROGRESS", "In progress"), ("PASS", "Pass"), ("FAIL", "Fail"), ("REQUIRES_REVIEW", "Requires review")],
                        default="NOT_STARTED",
                        max_length=16,
                    ),
                ),
                ("issue", models.TextField(blank=True, default="")),
                ("corrective_action", models.TextField(blank=True, default="")),
                ("engineer_remarks", models.TextField(blank=True, default="")),
                (
                    "review_status",
                    models.CharField(choices=[("NOT_REQUIRED", "Not required"), ("PENDING", "Pending"), ("RESOLVED", "Resolved"), ("WAIVED", "Waived")], default="NOT_REQUIRED", max_length=12),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment_assessments", to="site_inspections.inspection")),
                ("evidence_photo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="site_inspections.photo")),
            ],
            options={
                "db_table": "site_inspections_equipment_assessment",
                "ordering": ["inspection_id", "equipment_type"],
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("annotation_type", models.CharField(choices=[("PANEL_AREA", "Proposed panel area"), ("EQUIPMENT_AREA", "Proposed equipment area")], max_length=16)),
                ("geometry", models.JSONField(help_text="{x, y, w, h} in 0–1 image space (LEGACY_CONTAINER: the V2 4:3 container space).")),
                ("geometry_space", models.CharField(choices=[("IMAGE", "Image-normalised"), ("LEGACY_CONTAINER", "Legacy 4:3 container (re-draw)")], default="IMAGE", max_length=16)),
                ("width_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("height_m", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("area_m2", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to="site_inspections.inspection")),
                ("photo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to="site_inspections.photo")),
            ],
            options={
                "db_table": "site_inspections_annotation",
                "ordering": ["inspection_id", "annotation_type", "-number"],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.PositiveSmallIntegerField()),
                ("source", models.CharField(choices=[("PRE_SALE", "Pre-sale"), ("AGREEMENT", "Agreement")], max_length=10)),
                ("agreement_version", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="site_inspections.inspection")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "site_inspections_snapshot",
                "ordering": ["inspection_id", "-number"],
            },
        ),
        migrations.CreateModel(
            name="EngineeringReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("EQUIPMENT", "Equipment assessment"), ("STRUCTURE", "Structure decision"), ("ROOF", "Roof condition"), ("GENERATION", "Generation impact")],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "decision",
                    models.CharField(choices=[("PENDING", "Pending"), ("ROUTINE", "Routine"), ("REQUIRES_CHANGES", "Requires changes"), ("RESOLVED", "Resolved")], default="PENDING", max_length=16),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="engineering_reviews", to="site_inspections.inspection")),
            ],
            options={
                "db_table": "site_inspections_engineering_review",
                "ordering": ["inspection_id", "created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("decision", "PENDING"), ("deleted_at__isnull", True)), fields=("inspection",), name="site_inspections_review_one_pending"),
                    models.CheckConstraint(condition=models.Q(("trigger__in", ["MANUAL", "EQUIPMENT", "STRUCTURE", "ROOF", "GENERATION"])), name="site_inspections_review_trigger_valid"),
                    models.CheckConstraint(condition=models.Q(("decision__in", ["PENDING", "ROUTINE", "REQUIRES_CHANGES", "RESOLVED"])), name="site_inspections_review_decision_valid"),
                    models.CheckConstraint(condition=models.Q(("decision", "PENDING"), ("decided_at__isnull", False), _connector="OR"), name="site_inspections_review_decided_at"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdditionalWorkItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("WALKWAY", "Walkway"),
                            ("LADDER", "Ladder"),
                            ("SLIDING_DOOR", "Sliding door"),
                            ("ELEVATED_STRUCTURE", "Elevated structure"),
                            ("UNDERGROUND_CABLING", "Underground cabling"),
                            ("EXTRA_AC_CABLE", "Additional AC cable"),
                            ("EXTRA_DC_CABLE", "Additional DC cable"),
                            ("NEW_NEUTRAL_LINK", "New neutral link"),
                            ("NEW_TERMINATION", "New termination point"),
                            ("ADDITIONAL_EARTHING", "Additional earthing"),
                            ("CIVIL_WORK", "Civil / waterproofing"),
                            ("STRUCTURE_CHANGE", "Structure / support change"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("unit", models.CharField(blank=True, choices=[("NOS", "Nos"), ("M", "m"), ("M2", "m²"), ("M3", "m³"), ("JOB", "Job")], default="", max_length=8)),
                ("dimensions", models.CharField(blank=True, default="", max_length=120)),
                ("reason", models.TextField(blank=True, default="")),
                ("customer_impacting", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("IDENTIFIED", "Identified"),
                            ("ENGINEERING_REVIEW", "Engineering review"),
                            ("COST_CALCULATED", "Cost calculated"),
                            ("CUSTOMER_QUOTE_SENT", "Customer quote sent"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="IDENTIFIED",
                        max_length=22,
                    ),
                ),
                ("agreement_uid", models.UUIDField(blank=True, help_text="The EXTRA_STRUCTURE agreement that prices this item (agreements context; no FK).", null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="additional_work", to="site_inspections.inspection")),
            ],
            options={
                "db_table": "site_inspections_additional_work_item",
                "ordering": ["inspection_id", "work_type"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("inspection", "work_type"), name="site_inspections_work_one_per_type"),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "work_type__in",
                                [
                                    "WALKWAY",
                                    "LADDER",
                                    "SLIDING_DOOR",
                                    "ELEVATED_STRUCTURE",
                                    "UNDERGROUND_CABLING",
                                    "EXTRA_AC_CABLE",
                                    "EXTRA_DC_CABLE",
                                    "NEW_NEUTRAL_LINK",
                                    "NEW_TERMINATION",
                                    "ADDITIONAL_EARTHING",
                                    "CIVIL_WORK",
                                    "STRUCTURE_CHANGE",
                                    "OTHER",
                                ],
                            )
                        ),
                        name="site_inspections_work_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["NONE", "IDENTIFIED", "ENGINEERING_REVIEW", "COST_CALCULATED", "CUSTOMER_QUOTE_SENT", "APPROVED", "REJECTED"])),
                        name="site_inspections_work_status_valid",
                    ),
                    models.CheckConstraint(condition=models.Q(("unit", ""), ("unit__in", ["NOS", "M", "M2", "M3", "JOB"]), _connector="OR"), name="site_inspections_work_unit_valid"),
                    models.CheckConstraint(condition=models.Q(("quantity__isnull", True), ("quantity__gte", 0), _connector="OR"), name="site_inspections_work_quantity_non_negative"),
                    models.CheckConstraint(
                        condition=models.Q(models.Q(("status__in", ["COST_CALCULATED", "CUSTOMER_QUOTE_SENT"]), _negated=True), ("agreement_uid__isnull", False), _connector="OR"),
                        name="site_inspections_work_costed_has_agreement",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(models.Q(("status__in", ["APPROVED", "REJECTED"]), _negated=True), ("decided_at__isnull", False), _connector="OR"), name="site_inspections_work_decided_at"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("SUPERSEDED", "Superseded"), ("EXPIRED", "Expired")], default="PENDING", max_length=10
                    ),
                ),
                ("location_snapshot", models.JSONField(blank=True, help_text="Both current rectangles when requested (engines.inspection_readiness.build_location_snapshot).", null=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone_e164", models.CharField(blank=True, default="", max_length=16)),
                ("token_hash", models.CharField(blank=True, default="", help_text="SHA-256 (hex) of the link token; the token itself is never stored.", max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("responded_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("customer_comment", models.TextField(blank=True, default="")),
                ("paper_reason", models.TextField(blank=True, default="")),
                ("approved_by_staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="site_inspections.inspection")),
                ("paper_scan_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("signature_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "site_inspections_location_approval",
                "ordering": ["inspection_id", "-number"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "PENDING")), fields=("inspection",), name="site_inspections_approval_one_pending"),
                    models.UniqueConstraint(fields=("inspection", "number"), name="site_inspections_approval_number_uniq"),
                    models.UniqueConstraint(condition=models.Q(("token_hash", ""), _negated=True), fields=("token_hash",), name="site_inspections_approval_token_uniq"),
                    models.CheckConstraint(condition=models.Q(("status__in", ["PENDING", "APPROVED", "REJECTED", "SUPERSEDED", "EXPIRED"])), name="site_inspections_approval_status_valid"),
                    models.CheckConstraint(
                        condition=models.Q(("customer_phone_e164", ""), ("customer_phone_e164__regex", "^\\+[1-9][0-9]{7,14}$"), _connector="OR"), name="site_inspections_approval_phone_format"
                    ),
                    models.CheckConstraint(condition=models.Q(("token_hash", ""), ("token_hash__regex", "^[0-9a-f]{64}$"), _connector="OR"), name="site_inspections_approval_token_hex"),
                    models.CheckConstraint(
                        condition=models.Q(models.Q(("status", "PENDING"), _negated=True), models.Q(models.Q(("token_hash", ""), _negated=True), ("expires_at__isnull", False)), _connector="OR"),
                        name="site_inspections_approval_pending_has_link",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("approved_by_staff__isnull", True), models.Q(("paper_scan_asset__isnull", False), models.Q(("paper_reason", ""), _negated=True)), _connector="OR"),
                        name="site_inspections_approval_paper_documented",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["inspection", "photo_type"], name="si_photo_insp_type"),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(fields=("id", "inspection"), name="site_inspections_photo_id_inspection_uniq"),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(("photo_type__in", ["PANEL_AREA", "EQUIPMENT_AREA", "ROOF", "ACCESS", "ELECTRICAL", "CABLE_ROUTE", "SHADING", "ADDITIONAL_WORK", "EVIDENCE", "OTHER"])),
                name="site_inspections_photo_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(condition=models.Q(("stage__isnull", True), models.Q(("stage__gte", 1), ("stage__lte", 10)), _connector="OR"), name="site_inspections_photo_stage_range"),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(("category__in", ["GENERAL", "STRUCTURE", "CABLE", "EARTHING", "ELECTRICAL", "CIVIL", "ACCESS", "SAFETY", "OTHER"])),
                name="site_inspections_observation_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(("stage__isnull", True), models.Q(("stage__gte", 1), ("stage__lte", 10)), _connector="OR"), name="site_inspections_observation_stage_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(condition=models.Q(("note", ""), _negated=True), name="site_inspections_observation_note_present"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["engineer", "status"], name="si_insp_engineer_status"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["status", "visit_date"], name="si_insp_status_visit"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["created_at"], name="si_insp_created"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(fields=("number",), name="site_inspections_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("agreement_uid__isnull", False), ("deleted_at__isnull", True)), fields=("agreement_uid",), name="site_inspections_one_per_agreement"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("origin__in", ["PRE_SALE", "AGREEMENT"])), name="site_inspections_origin_valid"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ON_GRID", "HYBRID", "UNDECIDED"])), name="site_inspections_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "IN_PROGRESS", "COMPLETED", "CUSTOMER_APPROVAL_PENDING", "APPROVED", "INSTALLATION_READY", "REJECTED", "REVISION_REQUIRED", "ON_HOLD"])),
                name="site_inspections_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("complexity_status__in", ["NOT_ASSESSED", "ROUTINE", "ENGINEERING_REVIEW_REQUIRED"])), name="site_inspections_complexity_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("road_access", ""), ("road_access__in", ["GOOD", "LIMITED", "DIFFICULT", "NO_VEHICLE"]), _connector="OR"), name="site_inspections_road_access_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("vehicle_type", ""), ("vehicle_type__in", ["CAR", "PICKUP_VAN", "TRUCK", "MANUAL", "NOT_ASSESSED"]), _connector="OR"), name="site_inspections_vehicle_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("roof_type", ""), ("roof_type__in", ["RCC_FLAT", "TILE", "SHEET_METAL", "OTHER"]), _connector="OR"), name="site_inspections_roof_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("roof_strength", ""), ("roof_strength__in", ["GOOD", "REVIEW", "POOR"]), _connector="OR"), name="site_inspections_roof_strength_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("roof_accessibility", ""), ("roof_accessibility__in", ["EASY", "RESTRICTED", "DIFFICULT", "UNSAFE"]), _connector="OR"),
                name="site_inspections_roof_accessibility_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("roof_condition", ""), ("roof_condition__in", ["GOOD", "FAIR", "NEEDS_REPAIR", "REVIEW_REQUIRED"]), _connector="OR"), name="site_inspections_roof_condition_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("installation_difficulty", ""), ("installation_difficulty__in", ["LOW", "MEDIUM", "HIGH"]), _connector="OR"), name="site_inspections_installation_difficulty_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("roof_slope", ""), ("roof_slope__in", ["FLAT", "LOW", "MEDIUM", "STEEP"]), _connector="OR"), name="site_inspections_roof_slope_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction_facing", ""), ("direction_facing__in", ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]), _connector="OR"), name="site_inspections_direction_facing_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("morning_shading", ""), ("morning_shading__in", ["NONE", "LOW", "MEDIUM", "HIGH"]), _connector="OR"), name="site_inspections_morning_shading_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("afternoon_shading", ""), ("afternoon_shading__in", ["NONE", "LOW", "MEDIUM", "HIGH"]), _connector="OR"), name="site_inspections_afternoon_shading_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation_impact", ""), ("generation_impact__in", ["NONE", "LOW", "MEDIUM", "HIGH", "REQUIRES_REVIEW"]), _connector="OR"),
                name="site_inspections_generation_impact_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("phase", ""), ("phase__in", ["1P", "3P", "NC"]), _connector="OR"), name="site_inspections_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("tariff", ""), ("tariff__in", ["LT_I", "LT_II", "LT_III", "LT_IV", "NOT_CONFIRMED"]), _connector="OR"), name="site_inspections_tariff_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("neutral_link", ""), ("neutral_link__in", ["AVAILABLE", "NOT_AVAILABLE", "NEEDS_MODIFICATION"]), _connector="OR"), name="site_inspections_neutral_link_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("termination_point", ""), ("termination_point__in", ["AVAILABLE", "NOT_AVAILABLE", "NEEDS_MODIFICATION"]), _connector="OR"),
                name="site_inspections_termination_point_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("distribution_board", ""), ("distribution_board__in", ["AVAILABLE", "NOT_AVAILABLE", "NEEDS_MODIFICATION"]), _connector="OR"),
                name="site_inspections_distribution_board_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("earthing", ""), ("earthing__in", ["AVAILABLE", "NOT_AVAILABLE", "NEEDS_MODIFICATION"]), _connector="OR"), name="site_inspections_earthing_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("site_suitability", ""), ("site_suitability__in", ["SUITABLE", "CONDITIONAL", "NOT_SUITABLE"]), _connector="OR"), name="site_inspections_site_suitability_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("site_structure_type", ""), ("site_structure_type__in", ["SUFFICIENT", "ADDITIONAL_REQUIRED", "REQUIRES_ENGINEERING_REVIEW"]), _connector="OR"),
                name="site_inspections_site_structure_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("location_accuracy_m__isnull", True), ("location_accuracy_m__gte", 0), _connector="OR"), name="site_inspections_location_accuracy_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("roof_length_m__isnull", True), ("roof_length_m__gte", 0), _connector="OR"), name="site_inspections_roof_length_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("roof_width_m__isnull", True), ("roof_width_m__gte", 0), _connector="OR"), name="site_inspections_roof_width_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_area_m2__isnull", True), ("available_area_m2__gte", 0), _connector="OR"), name="site_inspections_available_area_m2_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("usable_area_m2__isnull", True), ("usable_area_m2__gte", 0), _connector="OR"), name="site_inspections_usable_area_m2_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("connected_load_kw__isnull", True), ("connected_load_kw__gte", 0), _connector="OR"), name="site_inspections_connected_load_kw_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("sanctioned_load_kw__isnull", True), ("sanctioned_load_kw__gte", 0), _connector="OR"), name="site_inspections_sanctioned_load_kw_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("ac_cable_m__isnull", True), ("ac_cable_m__gte", 0), _connector="OR"), name="site_inspections_ac_cable_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("dc_cable_m__isnull", True), ("dc_cable_m__gte", 0), _connector="OR"), name="site_inspections_dc_cable_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("la_cable_m__isnull", True), ("la_cable_m__gte", 0), _connector="OR"), name="site_inspections_la_cable_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("battery_cable_m__isnull", True), ("battery_cable_m__gte", 0), _connector="OR"), name="site_inspections_battery_cable_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("quoted_size_kw__isnull", True), ("quoted_size_kw__gte", 0), _connector="OR"), name="site_inspections_quoted_size_kw_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("walkway_length_m__isnull", True), ("walkway_length_m__gte", 0), _connector="OR"), name="site_inspections_walkway_length_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("walkway_width_m__isnull", True), ("walkway_width_m__gte", 0), _connector="OR"), name="site_inspections_walkway_width_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("ladder_length_m__isnull", True), ("ladder_length_m__gte", 0), _connector="OR"), name="site_inspections_ladder_length_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("sliding_door_width_m__isnull", True), ("sliding_door_width_m__gte", 0), _connector="OR"), name="site_inspections_sliding_door_width_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("sliding_door_height_m__isnull", True), ("sliding_door_height_m__gte", 0), _connector="OR"), name="site_inspections_sliding_door_height_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("elevated_height_m__isnull", True), ("elevated_height_m__gte", 0), _connector="OR"), name="site_inspections_elevated_height_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("panel_width_m__isnull", True), ("panel_width_m__gte", 0), _connector="OR"), name="site_inspections_panel_width_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("panel_height_m__isnull", True), ("panel_height_m__gte", 0), _connector="OR"), name="site_inspections_panel_height_m_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("panel_area_m2__isnull", True), ("panel_area_m2__gte", 0), _connector="OR"), name="site_inspections_panel_area_m2_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("equipment_width_m__isnull", True), ("equipment_width_m__gte", 0), _connector="OR"), name="site_inspections_equipment_width_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("equipment_height_m__isnull", True), ("equipment_height_m__gte", 0), _connector="OR"), name="site_inspections_equipment_height_m_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("equipment_area_m2__isnull", True), ("equipment_area_m2__gte", 0), _connector="OR"), name="site_inspections_equipment_area_m2_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("held_from_status", ""),
                    ("held_from_status__in", ["DRAFT", "IN_PROGRESS", "COMPLETED", "CUSTOMER_APPROVAL_PENDING", "APPROVED", "INSTALLATION_READY", "REJECTED", "REVISION_REQUIRED", "ON_HOLD"]),
                    _connector="OR",
                ),
                name="site_inspections_held_from_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("number", ""), _negated=True), name="site_inspections_number_present"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("registered_phone_e164", ""), ("registered_phone_e164__regex", "^\\+[1-9][0-9]{7,14}$"), _connector="OR"), name="site_inspections_phone_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("pincode", ""), ("pincode__regex", "^[1-9][0-9]{5}$"), _connector="OR"), name="site_inspections_pincode_format"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__isnull", True), models.Q(("latitude__gte", -90), ("latitude__lte", 90)), _connector="OR"), name="site_inspections_latitude_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__isnull", True), models.Q(("longitude__gte", -180), ("longitude__lte", 180)), _connector="OR"), name="site_inspections_longitude_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("shading_pct__isnull", True), models.Q(("shading_pct__gte", 0), ("shading_pct__lte", 100)), _connector="OR"), name="site_inspections_shading_pct_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("suitability_pct__isnull", True), models.Q(("suitability_pct__gte", 0), ("suitability_pct__lte", 100)), _connector="OR"),
                name="site_inspections_suitability_pct_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(condition=models.Q(("origin", "PRE_SALE"), ("agreement_uid__isnull", False), _connector="OR"), name="site_inspections_agreement_origin"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ON_HOLD"), _negated=True), models.Q(models.Q(("on_hold_reason", ""), _negated=True), models.Q(("held_from_status", ""), _negated=True)), _connector="OR"
                ),
                name="site_inspections_hold_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "INSTALLATION_READY"), _negated=True), ("released_at__isnull", False), _connector="OR"), name="site_inspections_ready_released"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentassessment",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("inspection", "equipment_type"), name="site_inspections_equipment_one_per_type"),
        ),
        migrations.AddConstraint(
            model_name="equipmentassessment",
            constraint=models.CheckConstraint(condition=models.Q(("equipment_type__in", ["ON_GRID_INVERTER", "HYBRID_INVERTER", "HYBRID_BATTERY"])), name="site_inspections_equipment_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="equipmentassessment",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["NOT_STARTED", "IN_PROGRESS", "PASS", "FAIL", "REQUIRES_REVIEW"])), name="site_inspections_equipment_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="equipmentassessment",
            constraint=models.CheckConstraint(condition=models.Q(("review_status__in", ["NOT_REQUIRED", "PENDING", "RESOLVED", "WAIVED"])), name="site_inspections_equipment_review_valid"),
        ),
        migrations.AddConstraint(
            model_name="equipmentassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("review_status__in", ["RESOLVED", "WAIVED"]), _negated=True), models.Q(("resolved_at__isnull", False), models.Q(("resolution_note", ""), _negated=True)), _connector="OR"
                ),
                name="site_inspections_equipment_resolution_noted",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["photo", "inspection"], name="si_annotation_photo_insp"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_current", True)), fields=("inspection", "annotation_type"), name="site_inspections_annotation_one_current"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(fields=("inspection", "annotation_type", "number"), name="site_inspections_annotation_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(condition=models.Q(("annotation_type__in", ["PANEL_AREA", "EQUIPMENT_AREA"])), name="site_inspections_annotation_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(condition=models.Q(("geometry_space__in", ["IMAGE", "LEGACY_CONTAINER"])), name="site_inspections_annotation_space_valid"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(condition=models.Q(("width_m__isnull", True), ("width_m__gt", 0), _connector="OR"), name="site_inspections_annotation_width_positive"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(condition=models.Q(("height_m__isnull", True), ("height_m__gt", 0), _connector="OR"), name="site_inspections_annotation_height_positive"),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.UniqueConstraint(fields=("inspection", "number"), name="site_inspections_snapshot_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.CheckConstraint(condition=models.Q(("source__in", ["PRE_SALE", "AGREEMENT"])), name="site_inspections_snapshot_source_valid"),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="site_inspections_snapshot_number_positive"),
        ),
    ]
