# Generated by Django 6.0.8 on 2026-09-29 03:35

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pricing", "0001_initial"),
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceReleaseLine",
            fields=[
                ("pk", models.CompositePrimaryKey("release", "component", blank=True, editable=False, primary_key=True, serialize=False)),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="pricing.pricerelease")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="release_lines", to="catalog.component")),
                ("list_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("list_price_gst_inclusive", models.BooleanField(default=False)),
                ("landed_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("gst_rate", models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                "db_table": "pricing_release_line",
                "ordering": ["release_id", "component_id"],
            },
        ),
        migrations.AddField(
            model_name="price",
            name="supplier",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prices", to="procurement.supplier"),
        ),
        migrations.AddField(
            model_name="price",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="pricerelease",
            name="created_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="pricerelease",
            name="market_rate_set",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="releases", to="pricing.marketrateset"),
        ),
        migrations.AddField(
            model_name="pricerelease",
            name="published_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="pricerelease",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="roofaddon",
            name="created_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="roofaddon",
            name="set",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roof_addons", to="pricing.marketrateset"),
        ),
        migrations.AddField(
            model_name="roofaddon",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="statutoryfee",
            name="created_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="statutoryfee",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="swapdelta",
            name="created_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="swapdelta",
            name="from_component",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component"),
        ),
        migrations.AddField(
            model_name="swapdelta",
            name="set",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="swap_deltas", to="pricing.marketrateset"),
        ),
        migrations.AddField(
            model_name="swapdelta",
            name="to_component",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component"),
        ),
        migrations.AddField(
            model_name="swapdelta",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="validitypolicy",
            name="created_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="validitypolicy",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="costconfig",
            index=models.Index(models.F("key"), models.OrderBy(models.F("effective_from"), descending=True), name="pricing_cost_config_key_from"),
        ),
        migrations.AddConstraint(
            model_name="costconfig",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("effective_to__isnull", True)), fields=("key",), name="pricing_cost_config_one_current_per_key"),
        ),
        migrations.AddConstraint(
            model_name="costconfig",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[a-z][a-z0-9_]*(\\.[a-z0-9_]+)*$")), name="pricing_cost_config_key_format"),
        ),
        migrations.AddConstraint(
            model_name="costconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("effective_to__isnull", True), ("effective_to__gte", models.F("effective_from")), _connector="OR"), name="pricing_cost_config_effective_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="installationmatrix",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("size_kw", "phase", "installation_type"), name="pricing_installation_matrix_cell_uniq"),
        ),
        migrations.AddConstraint(
            model_name="installationmatrix",
            constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["", "1P", "3P"])), name="pricing_installation_matrix_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="installationmatrix",
            constraint=models.CheckConstraint(condition=models.Q(("installation_type__in", ["FLAT", "SHEET", "ELEVATED"])), name="pricing_installation_matrix_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="installationmatrix",
            constraint=models.CheckConstraint(condition=models.Q(("size_kw__gt", 0)), name="pricing_installation_matrix_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="installationmatrix",
            constraint=models.CheckConstraint(condition=models.Q(("install_cost__gte", 0)), name="pricing_installation_matrix_cost_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="installationmatrix",
            constraint=models.CheckConstraint(condition=models.Q(("labour_days__isnull", True), ("labour_days__gte", 0), _connector="OR"), name="pricing_installation_matrix_days_not_negative"),
        ),
        migrations.AddIndex(
            model_name="marketrateset",
            index=models.Index(fields=["status", "-created_at"], name="pricing_mrs_status_created"),
        ),
        migrations.AddConstraint(
            model_name="marketrateset",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "ACTIVE")), fields=("status",), name="pricing_market_rate_set_one_active"),
        ),
        migrations.AddConstraint(
            model_name="marketrateset",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True)), name="pricing_market_rate_set_name_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="marketrateset",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "ACTIVE", "RETIRED"])), name="pricing_market_rate_set_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="marketrateset",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="pricing_market_rate_set_name_not_blank"),
        ),
        migrations.AddIndex(
            model_name="marketrate",
            index=models.Index(fields=["set", "system_type", "tier"], name="pricing_mr_set_system_tier"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("set", "system_type", "tier", "battery_config", "size_key", "from_size_key", "future_size_key", "variant"),
                name="pricing_market_rate_cell_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID", "UPGRADE"])), name="pricing_market_rate_system_valid"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("tier", ""), ("tier__in", ["BASE", "VALUE", "PREMIUM"]), _connector="OR"), name="pricing_market_rate_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("battery_config__in", ["", "0", "1", "2"])), name="pricing_market_rate_battery_valid"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["", "1P", "3P"])), name="pricing_market_rate_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("size_kw__gt", 0)), name="pricing_market_rate_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("customer_price_incl_gst__gte", 0)), name="pricing_market_rate_price_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("system_type", "UPGRADE"), models.Q(("from_size_key", ""), _negated=True)),
                    models.Q(models.Q(("system_type", "UPGRADE"), _negated=True), ("from_size_key", ""), models.Q(("tier", ""), _negated=True)),
                    _connector="OR",
                ),
                name="pricing_market_rate_upgrade_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketrate",
            constraint=models.CheckConstraint(condition=models.Q(("size_key", ""), _negated=True), name="pricing_market_rate_size_key_not_blank"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["status", "starts_on", "ends_on"], name="pricing_offer_status_dates"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("code"), condition=models.Q(("deleted_at__isnull", True)), name="pricing_offer_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("type__in", ["FLAT", "PERCENT"])), name="pricing_offer_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "APPROVED", "ACTIVE", "PAUSED", "EXPIRED", "ARCHIVED"])), name="pricing_offer_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("applies_to_system__in", ["ALL", "ONGRID", "HYBRID", "UPGRADE"])), name="pricing_offer_system_valid"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("applies_to_tier__in", ["ALL", "BASE", "VALUE", "PREMIUM"])), name="pricing_offer_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("value__gte", 0)), name="pricing_offer_value_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("type", "PERCENT"), _negated=True), ("value__lte", 100), _connector="OR"), name="pricing_offer_percent_at_most_100"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(("starts_on__isnull", True), ("ends_on__isnull", True), ("ends_on__gte", models.F("starts_on")), _connector="OR"), name="pricing_offer_date_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("applies_to_size_kw__isnull", True), ("applies_to_size_kw__gt", 0), _connector="OR"), name="pricing_offer_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("code__regex", "^[A-Za-z0-9][A-Za-z0-9_.-]{0,49}$")), name="pricing_offer_code_format"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="pricing_offer_name_not_blank"),
        ),
        migrations.AddIndex(
            model_name="offertransition",
            index=models.Index(fields=["offer", "at"], name="pricing_offer_tr_offer_at"),
        ),
        migrations.AddConstraint(
            model_name="offertransition",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_status", ""), ("from_status__in", ["DRAFT", "APPROVED", "ACTIVE", "PAUSED", "EXPIRED", "ARCHIVED"]), _connector="OR"),
                name="pricing_offer_transition_from_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="offertransition",
            constraint=models.CheckConstraint(condition=models.Q(("to_status__in", ["DRAFT", "APPROVED", "ACTIVE", "PAUSED", "EXPIRED", "ARCHIVED"])), name="pricing_offer_transition_to_valid"),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(models.F("component"), models.F("kind"), models.OrderBy(models.F("effective_from"), descending=True), name="pricing_price_comp_kind_from"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                condition=models.Q(("effective_to__isnull", True), ("deleted_at__isnull", True)), fields=("component", "kind"), name="pricing_price_one_current_per_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(condition=models.Q(("version_key", ""), _negated=True), fields=("kind", "version_key"), name="pricing_price_version_key_uniq"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["PURCHASE", "LANDED", "LIST"])), name="pricing_price_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("source__in", ["BATCH", "MANUAL", "IMPORT", "MARKUP"])), name="pricing_price_source_valid"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("kind", "LIST"), ("source", "MARKUP"), _negated=True), name="pricing_price_list_never_markup"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="pricing_price_amount_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("per_watt__isnull", True), ("per_watt__gte", 0), _connector="OR"), name="pricing_price_per_watt_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("currency__regex", "^[A-Z]{3}$")), name="pricing_price_currency_iso"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                condition=models.Q(("effective_to__isnull", True), ("effective_to__gte", models.F("effective_from")), _connector="OR"), name="pricing_price_effective_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricerelease",
            constraint=models.UniqueConstraint(fields=("number",), name="pricing_release_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="pricerelease",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "PUBLISHED")), fields=("status",), name="pricing_release_one_published"),
        ),
        migrations.AddConstraint(
            model_name="pricerelease",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["PUBLISHED", "SUPERSEDED"])), name="pricing_release_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="pricerelease",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="pricing_release_number_positive"),
        ),
        migrations.AddConstraint(
            model_name="pricerelease",
            constraint=models.CheckConstraint(condition=models.Q(("payload_sha256__regex", "^[0-9a-f]{64}$")), name="pricing_release_sha256_format"),
        ),
        migrations.AddIndex(
            model_name="pricereleaseline",
            index=models.Index(fields=["component", "release"], name="pricing_release_line_comp"),
        ),
        migrations.AddConstraint(
            model_name="pricereleaseline",
            constraint=models.CheckConstraint(condition=models.Q(("gst_rate__gte", 0), ("gst_rate__lte", 1)), name="pricing_release_line_gst_fraction"),
        ),
        migrations.AddConstraint(
            model_name="pricereleaseline",
            constraint=models.CheckConstraint(condition=models.Q(("list_price__isnull", True), ("list_price__gte", 0), _connector="OR"), name="pricing_release_line_list_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="pricereleaseline",
            constraint=models.CheckConstraint(condition=models.Q(("landed_cost__isnull", True), ("landed_cost__gte", 0), _connector="OR"), name="pricing_release_line_landed_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="roofaddon",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("set", "structure_type", "size_kw"), name="pricing_roof_addon_uniq"),
        ),
        migrations.AddConstraint(
            model_name="roofaddon",
            constraint=models.CheckConstraint(condition=models.Q(("structure_type__in", ["FLAT_ROOF", "ELEVATED", "SHEET_ROOF", "GROUND"])), name="pricing_roof_addon_structure_valid"),
        ),
        migrations.AddConstraint(
            model_name="roofaddon",
            constraint=models.CheckConstraint(condition=models.Q(("size_kw__gt", 0)), name="pricing_roof_addon_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="roofaddon",
            constraint=models.CheckConstraint(condition=models.Q(("addon_incl_gst__gte", 0)), name="pricing_roof_addon_amount_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("effective_to__isnull", True)),
                fields=("kind", "phase", "capacity_kw_max"),
                name="pricing_statutory_fee_one_current",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["KSEB_REGISTRATION", "KSEB_METER", "NET_METER_TEST", "OTHER"])), name="pricing_statutory_fee_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.CheckConstraint(condition=models.Q(("phase__isnull", True), ("phase__in", ["1P", "3P"]), _connector="OR"), name="pricing_statutory_fee_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="pricing_statutory_fee_amount_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.CheckConstraint(condition=models.Q(("capacity_kw_max__isnull", True), ("capacity_kw_max__gt", 0), _connector="OR"), name="pricing_statutory_fee_capacity_positive"),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.CheckConstraint(
                condition=models.Q(("effective_to__isnull", True), ("effective_to__gte", models.F("effective_from")), _connector="OR"), name="pricing_statutory_fee_effective_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="statutoryfee",
            constraint=models.CheckConstraint(condition=models.Q(("label", ""), _negated=True), name="pricing_statutory_fee_label_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="swapdelta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("set", "system_type", "tier", "slot", "from_component", "to_component"), name="pricing_swap_delta_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="swapdelta",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID", "UPGRADE"])), name="pricing_swap_delta_system_valid"),
        ),
        migrations.AddConstraint(
            model_name="swapdelta",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="pricing_swap_delta_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="swapdelta",
            constraint=models.CheckConstraint(condition=models.Q(("slot__in", ["panel", "inverter", "battery"])), name="pricing_swap_delta_slot_valid"),
        ),
        migrations.AddConstraint(
            model_name="swapdelta",
            constraint=models.CheckConstraint(condition=models.Q(("from_component", models.F("to_component")), _negated=True), name="pricing_swap_delta_distinct_components"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("kind", "DEFAULT")), fields=("key",), name="pricing_validity_policy_one_default"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("kind", "WINDOW")), fields=("key", "policy_id"), name="pricing_validity_policy_window_uniq"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[A-Z][A-Z0-9_]{0,15}$")), name="pricing_validity_policy_key_format"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["DEFAULT", "WINDOW"])), name="pricing_validity_policy_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["ACTIVE", "INACTIVE"])), name="pricing_validity_policy_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.CheckConstraint(condition=models.Q(("days__gte", 1)), name="pricing_validity_policy_days_positive"),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="pricing_validity_policy_window_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="validitypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("kind", "DEFAULT"), ("policy_id", "")), models.Q(("kind", "WINDOW"), models.Q(("policy_id", ""), _negated=True)), _connector="OR"),
                name="pricing_validity_policy_window_id",
            ),
        ),
    ]
