"""Package registry lifecycle — ports of Flarize ``packageApproval.js`` (V4), ``packageAuthority.js`` and
``packageProjection.js``.

A registry is ``{"schema", "packages": [...]}``. A package moves DRAFT → SUBMITTED → APPROVED (or REJECTED); approving
a revision supersedes the previous APPROVED revision of the same ``comboKey``; only a superseded or non-approved
record may be ARCHIVED. Approval needs a fresh VALID engineering validation of the current revision.

Like the JS, the lifecycle functions MUTATE the registry passed in and return a small result dict. Engineering
validation (``runPackageChecker``) calls the engineering checker through an injected ``check_project_bom`` callable
(the checker is its own engine). Package ids are generated by an injectable :class:`PackageIdFactory` (the JS used
``Date.now()`` and an in-process counter).
"""

from __future__ import annotations

import copy
import functools
import threading
import time
from typing import Any, Callable

from engines._jscompat import JsError, clean, is_array, is_nullish, is_object, js_keys, js_str, js_trim, jsget, locale_compare, nullish, strict_equal, to_base36, truthy
from engines.flarize_rbac import CAPABILITY, ROLE, Authorize, assert_can, is_individual_sales_role

PACKAGE_STATUS = {"PROPOSED": "PROPOSED", "APPROVED": "APPROVED", "REJECTED": "REJECTED"}
PACKAGE_STATE = {"DRAFT": "DRAFT", "SUBMITTED": "SUBMITTED", "APPROVED": "APPROVED", "REJECTED": "REJECTED", "ARCHIVED": "ARCHIVED"}
APPROVAL_ERROR = {
    name: name
    for name in (
        "PACKAGE_NOT_FOUND",
        "ALREADY_APPROVED",
        "ALREADY_REJECTED",
        "NOT_APPROVED_FOR_SALES",
        "MISSING_REASON",
        "VALIDATION_MISSING",
        "VALIDATION_STALE",
        "PACKAGE_NOT_VALID",
        "ARCHITECTURE_UNDECLARED",
        "ARCHITECTURE_INVALID",
        "NOT_DRAFT_STATE",
        "NOT_SUBMITTED_STATE",
        "NOT_APPROVED_SOURCE",
        "CANNOT_ARCHIVE_ACTIVE_APPROVED",
        "CANNOT_RESET_ARCHIVED",
        "INVALID_COMPARE_COUNT",
        "DUPLICATE_COMBO_APPROVED",
        "COMPONENT_NOT_APPROVED",
    )
}
VALID_ARCHITECTURES = ("DEYE", "ENPHASE")
PROFILE_INVERTER_TYPE_TO_ARCHITECTURE = {"ongrid": "DEYE", "hybrid": "DEYE", "micro": "ENPHASE"}
EDITABLE_FIELDS = ("architecture", "components", "profileKey")

# packageAuthority.js
PACKAGE_ROLES = (
    "panel",
    "inverter",
    "microInverter",
    "battery",
    "batteryMccb",
    "dcdb",
    "acdb",
    "meter",
    "isolator",
    "dcCable",
    "acCable",
    "earthCable",
    "laCable",
    "cbRod",
    "structure",
)
SALES_SELECTABLE_ROLES = ("panel", "inverter", "structure")
ENGINEERING_CRITICAL_ROLES = tuple(r for r in PACKAGE_ROLES if r not in SALES_SELECTABLE_ROLES)
ROLE_TO_CATEGORY = {
    "panel": "panel",
    "inverter": "inverter",
    "microInverter": "enphase",
    "battery": "battery",
    "batteryMccb": "mccb_box",
    "dcdb": "dcdb",
    "acdb": "acdb",
    "meter": "meter",
    "isolator": "isolator",
    "dcCable": "dc_cable",
    "acCable": "ac_cable",
    "earthCable": "earth_cable",
    "laCable": "la_cable",
    "cbRod": "cb_rod",
    "structure": "structure_material",
}

# bomRoles.js (the checker's role vocabulary; only what runPackageChecker needs to map registry lines)
_CATEGORY_TO_CHECKER_ROLE = {
    "panel": "PANEL",
    "inverter": "INVERTER",
    "battery": "BATTERY",
    "mccb_box": "BATTERY_PROTECTION",
    "battery_cable": "BATTERY_CABLE",
    "isolator": "AC_ISOLATOR",
    "acdb": "ACDB",
    "dcdb": "DCDB",
    "change_over": "CHANGEOVER",
    "meter": "METER",
    "ac_cable": "AC_CABLE",
    "dc_cable": "DC_CABLE",
    "ug_cable": "AC_CABLE",
    "armoured_cable": "AC_CABLE",
    "earth_cable": "EARTHING",
    "cb_rod": "EARTHING",
    "la_cable": "PROTECTION",
    "structure_material": "STRUCTURE",
}
_ENPHASE_COMPONENT_ROLES = {
    "en1": "MICRO_INVERTER",
    "en2": "AC_CABLE",
    "en3": "MONITORING",
    "en4": "PROTECTION",
    "en5": "AC_CABLE",
    "en6": "MONITORING",
    "en7": "ENERGY_SYSTEM_CONTROLLER",
    "en_sysctrl": "ENERGY_SYSTEM_CONTROLLER",
    "en_flexbat": "BATTERY",
}


class ApprovalError(JsError):
    js_name = "ApprovalError"


class PackageIdFactory:
    """``generatePackageId``: ``CFGPKG-<SYS>-<size>-<PHASE>-<TIER>[-FR<size>]-<ms base36><seq base36>``.

    ``now_ms`` pins the millisecond stamp (tests, parity replays); without it the wall clock is used, like the JS.
    The sequence is taken under a lock: the JS ran single-threaded, a Django worker does not, and two threads reading
    the same ``seq`` in the same millisecond produced the same package id. The counter is per process, so services
    running several worker processes pass a factory of their own (e.g. uid-based) — see docs/decisions.
    """

    def __init__(self, now_ms: int | None = None, seq: int = 0):
        self.now_ms = now_ms
        self.seq = seq
        self._lock = threading.Lock()

    def _next_seq(self) -> int:
        with self._lock:
            seq = self.seq
            self.seq += 1
        return seq

    def __call__(self, template: dict) -> str:
        system_type = js_str(template.get("systemType") if truthy(template.get("systemType")) else "PKG").upper()
        size = js_str(template.get("size") if truthy(template.get("size")) else "")
        phase = js_str(template.get("phase") if truthy(template.get("phase")) else "").upper()
        tier = js_str(template.get("tier") if truthy(template.get("tier")) else "").upper()
        fr = f"-FR{js_str(template.get('systemSize'))}" if template.get("variant") == "FUTURE_READY" and truthy(template.get("systemSize")) else ""
        now_ms = self.now_ms if self.now_ms is not None else int(time.time() * 1000)
        stamp = to_base36(now_ms) + to_base36(self._next_seq() % 1296).rjust(2, "0")
        return f"CFGPKG-{system_type}-{size}-{phase}-{tier}{fr}-{stamp}"


_DEFAULT_ID_FACTORY = PackageIdFactory()


def _require_at(at: Any) -> None:
    if not truthy(at):
        raise ApprovalError("Timestamp (at) is required.", "MISSING_TIMESTAMP")


def _find_package(registry: Any, package_id: Any) -> dict | None:
    packages = jsget(registry, "packages")
    for package in packages if truthy(packages) else []:
        if strict_equal(jsget(package, "packageId"), package_id):
            return package
    return None


def _not_found(package_id: Any) -> ApprovalError:
    return ApprovalError(f'Package "{js_str(package_id)}" not found.', APPROVAL_ERROR["PACKAGE_NOT_FOUND"], {"packageId": package_id})


def _user_id(actor: Any) -> Any:
    return jsget(actor, "userId")


def resolve_package_architecture(pkg: Any, catalog: Any) -> dict:
    """``{architecture, source}``: an explicit valid ``pkg.architecture`` wins, else the profile's ``inverterType``."""
    if truthy(pkg) and jsget(pkg, "architecture") in VALID_ARCHITECTURES:
        return {"architecture": pkg["architecture"], "source": "PACKAGE_DECLARED"}
    profile = None
    if truthy(jsget(pkg, "profileKey")) and truthy(jsget(catalog, "packageProfiles")):
        profile = jsget(catalog["packageProfiles"], pkg["profileKey"])
    mapped = None
    if truthy(profile) and not is_nullish(jsget(profile, "inverterType")):
        mapped = PROFILE_INVERTER_TYPE_TO_ARCHITECTURE.get(js_str(profile["inverterType"]).lower())
    if mapped:
        return {"architecture": mapped, "source": "PROFILE_INVERTER_TYPE"}
    return {"architecture": None, "source": None}


def _assert_components_approved(pkg: dict, catalog: Any) -> None:
    if not truthy(catalog):
        return
    bad = []
    components = jsget(pkg, "components")
    for comp in components if truthy(components) else []:
        role = jsget(comp, "role")
        cid = jsget(comp, "componentId") if truthy(jsget(comp, "componentId")) else jsget(comp, "pinnedComponentId")
        if not truthy(role) or not truthy(cid):
            continue
        category = jsget(jsget(catalog, "categories"), role)
        if not truthy(category) or not is_array(jsget(category, "items")):
            continue
        item = next((i for i in category["items"] if strict_equal(jsget(i, "id"), cid)), None)
        if item is None:
            bad.append({"role": role, "componentId": cid, "reason": "NOT_IN_CATALOG"})
            continue
        status = jsget(item, "approvalStatus")
        if status != "APPROVED":
            bad.append({"role": role, "componentId": cid, "name": item.get("name") if truthy(item.get("name")) else None, "approvalStatus": nullish(status, "UNKNOWN")})
    if bad:
        raise ApprovalError(
            f'Package "{js_str(jsget(pkg, "packageId"))}" cannot be approved — {len(bad)} pinned component(s) not APPROVED in catalog.',
            APPROVAL_ERROR["COMPONENT_NOT_APPROVED"],
            clean({"packageId": jsget(pkg, "packageId"), "components": bad}),
        )


def _assert_ready_for_approval(pkg: dict, *, acknowledge_warnings: bool = False) -> None:
    package_id = jsget(pkg, "packageId")
    validation = jsget(pkg, "lastValidation")
    if not truthy(validation):
        raise ApprovalError(
            f'Package "{js_str(package_id)}" has no engineering validation. Run the checker before approval.',
            APPROVAL_ERROR["VALIDATION_MISSING"],
            clean({"packageId": package_id}),
        )
    revision = nullish(jsget(pkg, "revisionNumber"), 1)
    validated = jsget(validation, "revisionNumber")
    if not strict_equal(validated, revision):
        raise ApprovalError(
            f'Validation on package "{js_str(package_id)}" is for revision {js_str(validated)} but the package is at revision {js_str(revision)}.',
            APPROVAL_ERROR["VALIDATION_STALE"],
            clean({"packageId": package_id, "validatedRevision": validated, "currentRevision": revision}),
        )
    status = jsget(validation, "status")
    if not (status == "VALID" or (truthy(acknowledge_warnings) and status == "WARNING")):
        raise ApprovalError(
            f'Package "{js_str(package_id)}" cannot be approved — validation status is {js_str(status)}.',
            APPROVAL_ERROR["PACKAGE_NOT_VALID"],
            clean({"packageId": package_id, "validationStatus": status}),
        )


def combo_key_for(pkg: Any) -> str:
    """``systemType|size|phase|tier``, plus ``|FR<systemSize>`` for a FUTURE_READY pack."""

    def part(key: str) -> str:
        return js_str(nullish(jsget(pkg, key), ""))

    base = f"{part('systemType')}|{part('size')}|{part('phase')}|{part('tier')}"
    system_size = nullish(jsget(pkg, "systemSize"), None)
    if nullish(jsget(pkg, "variant"), None) == "FUTURE_READY" and truthy(system_size):
        return f"{base}|FR{js_str(system_size)}"
    return base


def _combo_key_of(pkg: dict) -> str:
    combo = jsget(pkg, "comboKey")
    return combo_key_for(pkg) if is_nullish(combo) else combo


def approve_package(
    registry: dict,
    *,
    actor: Any,
    package_id: Any,
    notes: Any = None,
    at: Any,
    catalog: Any = None,
    acknowledge_warnings: bool = False,
    authorize: Authorize = assert_can,
) -> dict:
    """Approve (PACKAGE_APPROVE): fresh VALID validation, approved components, supersede the previous revision."""
    authorize(actor, CAPABILITY["PACKAGE_APPROVE"])
    _require_at(at)
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    if pkg.get("packageState") == PACKAGE_STATE["APPROVED"] or pkg.get("approvalStatus") == PACKAGE_STATUS["APPROVED"]:
        raise ApprovalError(f'Package "{js_str(package_id)}" is already APPROVED.', APPROVAL_ERROR["ALREADY_APPROVED"], {"packageId": package_id})
    _assert_ready_for_approval(pkg, acknowledge_warnings=acknowledge_warnings)
    if jsget(pkg.get("lastValidation"), "status") == "WARNING":
        findings = jsget(pkg["lastValidation"], "findings")
        pkg["acknowledgedWarnings"] = [
            clean({"ruleId": jsget(f, "ruleId"), "acknowledgedBy": _user_id(actor), "acknowledgedAt": at}) for f in (findings if truthy(findings) else []) if jsget(f, "severity") == "WARNING"
        ]
    _assert_components_approved(pkg, catalog)
    user_id = _user_id(actor)
    pkg["approvalStatus"] = PACKAGE_STATUS["APPROVED"]
    pkg["approvedBy"] = user_id
    pkg["approvedAt"] = at
    pkg["approvalNotes"] = notes if truthy(notes) else None
    pkg["engineeringStatus"] = "APPROVED"
    pkg["packageState"] = PACKAGE_STATE["APPROVED"]
    for comp in pkg.get("components") or []:
        if comp.get("approvalStatus") != "APPROVED":
            comp["approvalStatus"] = "APPROVED"
            comp["approvedByDecision"] = f"PKG_APPROVAL_{js_str(user_id)}_{js_str(at)}"
    combo = _combo_key_of(pkg)
    for other in registry.get("packages") or []:
        if strict_equal(other.get("packageId"), pkg.get("packageId")):
            continue
        if _combo_key_of(other) != combo:
            continue
        if other.get("packageState") != PACKAGE_STATE["APPROVED"] or truthy(other.get("supersededBy")):
            continue
        other["supersededBy"] = pkg.get("packageId")
    return clean(
        {
            "packageId": package_id,
            "approvalStatus": PACKAGE_STATUS["APPROVED"],
            "approvedBy": user_id,
            "approvedAt": at,
            "componentCount": len(pkg.get("components") or []),
        }
    )


def reject_package(registry: dict, *, actor: Any, package_id: Any, reason: Any, at: Any, authorize: Authorize = assert_can) -> dict:
    authorize(actor, CAPABILITY["PACKAGE_APPROVE"])
    _require_at(at)
    if not truthy(reason) or not js_trim(reason):
        raise ApprovalError("A reason is required when rejecting a package.", APPROVAL_ERROR["MISSING_REASON"], {"packageId": package_id})
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    user_id = _user_id(actor)
    pkg["approvalStatus"] = PACKAGE_STATUS["REJECTED"]
    pkg["rejectedBy"] = user_id
    pkg["rejectedAt"] = at
    pkg["rejectionReason"] = js_trim(reason)
    pkg["engineeringStatus"] = "REJECTED"
    pkg["packageState"] = PACKAGE_STATE["REJECTED"]
    return clean({"packageId": package_id, "approvalStatus": PACKAGE_STATUS["REJECTED"], "rejectedBy": user_id, "rejectedAt": at, "reason": js_trim(reason)})


def reset_package(registry: dict, *, actor: Any, package_id: Any, at: Any, authorize: Authorize = assert_can) -> dict:
    """Back to DRAFT/PROPOSED (PACKAGE_APPROVE); clears the validation; refuses an ARCHIVED record."""
    authorize(actor, CAPABILITY["PACKAGE_APPROVE"])
    _require_at(at)
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    if pkg.get("packageState") == PACKAGE_STATE["ARCHIVED"]:
        raise ApprovalError(f'Package "{js_str(package_id)}" is ARCHIVED and cannot be reset.', APPROVAL_ERROR["CANNOT_RESET_ARCHIVED"], {"packageId": package_id})
    pkg.update(
        {
            "approvalStatus": PACKAGE_STATUS["PROPOSED"],
            "approvedBy": None,
            "approvedAt": None,
            "rejectedBy": None,
            "rejectedAt": None,
            "rejectionReason": None,
            "approvalNotes": None,
            "engineeringStatus": "WARNING",
            "packageState": PACKAGE_STATE["DRAFT"],
            "lastValidation": None,
        }
    )
    for comp in pkg.get("components") or []:
        decision = comp.get("approvedByDecision")
        if truthy(decision) and isinstance(decision, str) and decision.startswith("PKG_APPROVAL_"):
            comp["approvalStatus"] = "PROPOSED"
            comp["approvedByDecision"] = None
    return {"packageId": package_id, "approvalStatus": PACKAGE_STATUS["PROPOSED"]}


def bulk_approve_packages(registry: dict, *, actor: Any, filter: Any = None, notes: Any = None, at: Any, catalog: Any = None, authorize: Authorize = assert_can) -> dict:
    """Dispatch :func:`approve_package` over every non-approved package matching the filter; errors per item."""
    authorize(actor, CAPABILITY["PACKAGE_APPROVE"])
    _require_at(at)
    wanted = filter if isinstance(filter, dict) else {}

    def matches(pkg: dict) -> bool:
        if pkg.get("packageState") == PACKAGE_STATE["APPROVED"] or pkg.get("approvalStatus") == PACKAGE_STATUS["APPROVED"]:
            return False
        for key in ("systemType", "tier", "phase", "size"):
            if truthy(wanted.get(key)) and not strict_equal(pkg.get(key), wanted[key]):
                return False
        return True

    targets = [p for p in registry.get("packages") or [] if matches(p)]
    results = []
    for pkg in targets:
        try:
            results.append(approve_package(registry, actor=actor, package_id=pkg.get("packageId"), notes=notes, at=at, catalog=catalog, authorize=authorize))
        except Exception as exc:  # the JS catches everything and reports it per package
            code = getattr(exc, "code", None)
            results.append({"packageId": pkg.get("packageId"), "error": getattr(exc, "message", str(exc)), "code": code if truthy(code) else None})
    return {"approved": [r for r in results if not truthy(r.get("error"))], "errors": [r for r in results if truthy(r.get("error"))], "total": len(targets)}


def list_packages_for_role(registry: Any, *, actor: Any = None, filter: Any = None) -> list[dict]:
    """Admin/PH list; Sales roles see only APPROVED packages."""
    packages = jsget(registry, "packages")
    result = list(packages) if truthy(packages) else []
    role = jsget(actor, "role")
    if is_individual_sales_role(role) or role == ROLE["SALES_HEAD"]:
        result = [p for p in result if p.get("approvalStatus") == PACKAGE_STATUS["APPROVED"]]
    wanted = filter if isinstance(filter, dict) else {}
    for key in ("systemType", "tier", "phase", "size", "approvalStatus", "packageState"):
        if truthy(wanted.get(key)):
            result = [p for p in result if strict_equal(p.get(key), wanted[key])]
    listed = []
    for p in result:
        components = p.get("components") or []
        listed.append(
            clean(
                {
                    "packageId": jsget(p, "packageId"),
                    "systemType": jsget(p, "systemType"),
                    "size": jsget(p, "size"),
                    "phase": jsget(p, "phase"),
                    "tier": jsget(p, "tier"),
                    "profileKey": jsget(p, "profileKey"),
                    "approvalStatus": jsget(p, "approvalStatus"),
                    "approvedBy": p.get("approvedBy") if truthy(p.get("approvedBy")) else None,
                    "approvedAt": p.get("approvedAt") if truthy(p.get("approvedAt")) else None,
                    "engineeringStatus": jsget(p, "engineeringStatus"),
                    "componentCount": len(components),
                    "approvedComponentCount": len([c for c in components if c.get("approvalStatus") == "APPROVED"]),
                    "packageState": nullish(jsget(p, "packageState"), None),
                    "revisionNumber": nullish(jsget(p, "revisionNumber"), 1),
                    "comboKey": nullish(jsget(p, "comboKey"), None),
                    "variant": nullish(jsget(p, "variant"), "STANDARD"),
                    "systemSize": nullish(jsget(p, "systemSize"), jsget(p, "size")),
                    "publishedFromConfigVersion": nullish(jsget(p, "publishedFromConfigVersion"), None),
                    "supersededBy": nullish(jsget(p, "supersededBy"), None),
                    "architecture": nullish(jsget(p, "architecture"), None),
                    "lastValidationStatus": nullish(jsget(jsget(p, "lastValidation"), "status"), None),
                    "createdBy": nullish(jsget(p, "createdBy"), None),
                    "createdAt": nullish(jsget(p, "createdAt"), None),
                    "submittedBy": nullish(jsget(p, "submittedBy"), None),
                    "submittedAt": nullish(jsget(p, "submittedAt"), None),
                }
            )
        )
    return listed


def approval_summary(registry: Any) -> dict:
    packages = jsget(registry, "packages")
    packages = packages if truthy(packages) else []
    return {
        "total": len(packages),
        "approved": len([p for p in packages if p.get("approvalStatus") == PACKAGE_STATUS["APPROVED"]]),
        "proposed": len([p for p in packages if p.get("approvalStatus") == PACKAGE_STATUS["PROPOSED"]]),
        "rejected": len([p for p in packages if p.get("approvalStatus") == PACKAGE_STATUS["REJECTED"]]),
    }


def assert_package_selectable_by_actor(registry: Any, *, actor: Any, package_id: Any) -> bool:
    """Sales may select only APPROVED packages; every other role may select any."""
    role = jsget(actor, "role")
    if not (is_individual_sales_role(role) or role == ROLE["SALES_HEAD"]):
        return True
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    status = jsget(pkg, "approvalStatus")
    if status != PACKAGE_STATUS["APPROVED"]:
        raise ApprovalError(
            f'Package "{js_str(package_id)}" is {js_str(status)}. Only APPROVED packages are available for Sales.',
            APPROVAL_ERROR["NOT_APPROVED_FOR_SALES"],
            clean({"packageId": package_id, "approvalStatus": status}),
        )
    return True


def _architecture_invalid(architecture: Any) -> ApprovalError:
    return ApprovalError(
        f'Architecture "{js_str(architecture)}" is not one of {", ".join(VALID_ARCHITECTURES)}.',
        APPROVAL_ERROR["ARCHITECTURE_INVALID"],
        clean({"architecture": architecture}),
    )


def create_package(registry: dict, *, actor: Any, template: Any, at: Any, id_factory: Callable[[dict], str] | None = None, authorize: Authorize = assert_can) -> dict:
    """A new DRAFT package (PACKAGE_CREATE) from a template with the identity fields and components."""
    authorize(actor, CAPABILITY["PACKAGE_CREATE"])
    _require_at(at)
    if not truthy(template) or not is_object(template):
        raise ApprovalError("A package template object is required.", "MISSING_TEMPLATE")
    for key in ("systemType", "size", "phase", "tier", "architecture", "profileKey", "components"):
        if is_nullish(jsget(template, key)):
            raise ApprovalError(f'Template is missing required field "{key}".', "MISSING_TEMPLATE_FIELD", {"field": key})
    if not is_array(template["components"]):
        raise ApprovalError("Template components must be an array.", "MISSING_TEMPLATE_FIELD", {"field": "components"})
    if template["architecture"] not in VALID_ARCHITECTURES:
        raise _architecture_invalid(template["architecture"])
    package_id = template.get("packageId") if truthy(template.get("packageId")) else (id_factory or _DEFAULT_ID_FACTORY)(template)
    record = {
        "packageId": package_id,
        "systemType": template["systemType"],
        "size": template["size"],
        "phase": template["phase"],
        "tier": template["tier"],
        "profileKey": template["profileKey"],
        "architecture": template["architecture"],
        "upgradePathId": nullish(jsget(template, "upgradePathId"), None),
        "fromSize": nullish(jsget(template, "fromSize"), None),
        "toSize": nullish(jsget(template, "toSize"), None),
        "variant": nullish(jsget(template, "variant"), "STANDARD"),
        "systemSize": nullish(jsget(template, "systemSize"), template["size"]),
        "packageState": PACKAGE_STATE["DRAFT"],
        "revisionNumber": 1,
        "comboKey": combo_key_for(template),
        "supersededBy": None,
        "approvalStatus": PACKAGE_STATUS["PROPOSED"],
        "engineeringStatus": "WARNING",
        "approvedBy": None,
        "approvedAt": None,
        "approvalNotes": None,
        "rejectedBy": None,
        "rejectedAt": None,
        "rejectionReason": None,
        "createdBy": _user_id(actor),
        "createdAt": at,
        "submittedBy": None,
        "submittedAt": None,
        "archivedBy": None,
        "archivedAt": None,
        "archivalReason": None,
        "lastValidation": None,
        "legacyApproved": False,
        "blockers": [],
        "approvedRules": [],
        "prohibited": [],
        "components": copy.deepcopy(template["components"]),
    }
    record = clean(record)
    if not is_array(registry.get("packages")):
        registry["packages"] = []
    registry["packages"].append(record)
    return {"packageId": package_id, "package": record}


_RESET_ON_COPY = {
    "approvalStatus": PACKAGE_STATUS["PROPOSED"],
    "engineeringStatus": "WARNING",
    "approvedBy": None,
    "approvedAt": None,
    "approvalNotes": None,
    "rejectedBy": None,
    "rejectedAt": None,
    "rejectionReason": None,
    "archivedBy": None,
    "archivedAt": None,
    "archivalReason": None,
    "submittedBy": None,
    "submittedAt": None,
    "lastValidation": None,
    "legacyApproved": False,
}


def duplicate_package(registry: dict, *, actor: Any, source_package_id: Any, at: Any, id_factory: Callable[[dict], str] | None = None, authorize: Authorize = assert_can) -> dict:
    """A new DRAFT copying the design of any package (PACKAGE_DUPLICATE); approval metadata stripped."""
    authorize(actor, CAPABILITY["PACKAGE_DUPLICATE"])
    _require_at(at)
    source = _find_package(registry, source_package_id)
    if source is None:
        raise _not_found(source_package_id)
    duplicate = copy.deepcopy(source)
    package_id = (id_factory or _DEFAULT_ID_FACTORY)(source)
    duplicate["packageId"] = package_id
    duplicate["packageState"] = PACKAGE_STATE["DRAFT"]
    duplicate["revisionNumber"] = 1
    duplicate["supersededBy"] = None
    duplicate.update(_RESET_ON_COPY)
    duplicate["createdBy"] = _user_id(actor)
    duplicate["createdAt"] = at
    duplicate["comboKey"] = "|".join(js_str(nullish(duplicate.get(k), "")) for k in ("systemType", "size", "phase", "tier"))
    duplicate["architecture"] = nullish(source.get("architecture"), None)
    duplicate = clean(duplicate)
    registry["packages"].append(duplicate)
    return {"packageId": package_id, "package": duplicate}


def create_revision(registry: dict, *, actor: Any, source_package_id: Any, at: Any, id_factory: Callable[[dict], str] | None = None, authorize: Authorize = assert_can) -> dict:
    """A DRAFT revision (revisionNumber + 1, same comboKey) of an APPROVED, non-superseded package (PACKAGE_EDIT)."""
    authorize(actor, CAPABILITY["PACKAGE_EDIT"])
    _require_at(at)
    source = _find_package(registry, source_package_id)
    if source is None:
        raise _not_found(source_package_id)
    if source.get("packageState") != PACKAGE_STATE["APPROVED"] or truthy(source.get("supersededBy")):
        raise ApprovalError(
            f'Cannot revise "{js_str(source_package_id)}" — it is not an APPROVED, non-superseded record.',
            APPROVAL_ERROR["NOT_APPROVED_SOURCE"],
            clean({"packageId": source_package_id, "packageState": jsget(source, "packageState"), "supersededBy": jsget(source, "supersededBy")}),
        )
    revision = copy.deepcopy(source)
    package_id = (id_factory or _DEFAULT_ID_FACTORY)(source)
    revision["packageId"] = package_id
    revision_number = source.get("revisionNumber")
    revision["revisionNumber"] = (revision_number if truthy(revision_number) else 1) + 1
    combo = source.get("comboKey")
    revision["comboKey"] = combo if not is_nullish(combo) else "|".join(js_str(nullish(source.get(k), "")) for k in ("systemType", "size", "phase", "tier"))
    revision["packageState"] = PACKAGE_STATE["DRAFT"]
    revision["supersededBy"] = None
    revision.update(_RESET_ON_COPY)
    revision["createdBy"] = _user_id(actor)
    revision["createdAt"] = at
    revision["architecture"] = nullish(source.get("architecture"), None)
    revision = clean(revision)
    registry["packages"].append(revision)
    return {"packageId": package_id, "package": revision}


def edit_package(registry: dict, *, actor: Any, package_id: Any, patch: Any, at: Any, authorize: Authorize = assert_can) -> dict:
    """Patch ``architecture`` / ``components`` / ``profileKey`` of a DRAFT; any edit clears the validation."""
    authorize(actor, CAPABILITY["PACKAGE_EDIT"])
    _require_at(at)
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    if pkg.get("packageState") != PACKAGE_STATE["DRAFT"]:
        raise ApprovalError(
            f'Package "{js_str(package_id)}" is {js_str(jsget(pkg, "packageState"))}; only DRAFT packages may be edited.',
            APPROVAL_ERROR["NOT_DRAFT_STATE"],
            clean({"packageId": package_id, "packageState": jsget(pkg, "packageState")}),
        )
    changes = patch if truthy(patch) and is_object(patch) else {}
    for key in js_keys(changes):
        if key not in EDITABLE_FIELDS:
            raise ApprovalError(f'Field "{key}" is not editable on a DRAFT package.', "IMMUTABLE_FIELD", {"field": key})
    if isinstance(changes, dict):
        if "architecture" in changes:
            if changes["architecture"] not in VALID_ARCHITECTURES:
                raise _architecture_invalid(changes["architecture"])
            pkg["architecture"] = changes["architecture"]
        if "components" in changes:
            if not is_array(changes["components"]):
                raise ApprovalError("components must be an array.", "IMMUTABLE_FIELD", {"field": "components"})
            pkg["components"] = copy.deepcopy(changes["components"])
        if "profileKey" in changes:
            pkg["profileKey"] = changes["profileKey"]
    pkg["lastValidation"] = None
    return {"packageId": package_id, "package": pkg}


def submit_package(registry: dict, *, actor: Any, package_id: Any, at: Any, acknowledge_warnings: bool = False, authorize: Authorize = assert_can) -> dict:
    """DRAFT → SUBMITTED (PACKAGE_SUBMIT) behind the same validation gate as approval."""
    authorize(actor, CAPABILITY["PACKAGE_SUBMIT"])
    _require_at(at)
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    if pkg.get("packageState") != PACKAGE_STATE["DRAFT"]:
        raise ApprovalError(
            f'Package "{js_str(package_id)}" is {js_str(jsget(pkg, "packageState"))}; only DRAFT packages may be submitted.',
            APPROVAL_ERROR["NOT_DRAFT_STATE"],
            clean({"packageId": package_id, "packageState": jsget(pkg, "packageState")}),
        )
    _assert_ready_for_approval(pkg, acknowledge_warnings=acknowledge_warnings)
    pkg["packageState"] = PACKAGE_STATE["SUBMITTED"]
    pkg["submittedBy"] = _user_id(actor)
    pkg["submittedAt"] = at
    return clean({"packageId": package_id, "packageState": PACKAGE_STATE["SUBMITTED"], "submittedBy": _user_id(actor), "submittedAt": at})


def archive_package(registry: dict, *, actor: Any, package_id: Any, reason: Any, at: Any, authorize: Authorize = assert_can) -> dict:
    """ARCHIVED (PACKAGE_ARCHIVE); an active APPROVED record must be superseded or rejected first."""
    authorize(actor, CAPABILITY["PACKAGE_ARCHIVE"])
    _require_at(at)
    if not truthy(reason) or not js_trim(js_str(reason)):
        raise ApprovalError("A reason is required when archiving a package.", APPROVAL_ERROR["MISSING_REASON"], {"packageId": package_id})
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    if pkg.get("packageState") == PACKAGE_STATE["APPROVED"] and not truthy(pkg.get("supersededBy")):
        raise ApprovalError(
            f'Package "{js_str(package_id)}" is an active APPROVED record and cannot be archived until it is superseded or rejected.',
            APPROVAL_ERROR["CANNOT_ARCHIVE_ACTIVE_APPROVED"],
            {"packageId": package_id},
        )
    pkg["packageState"] = PACKAGE_STATE["ARCHIVED"]
    pkg["archivedBy"] = _user_id(actor)
    pkg["archivedAt"] = at
    pkg["archivalReason"] = js_trim(js_str(reason))
    return clean({"packageId": package_id, "packageState": PACKAGE_STATE["ARCHIVED"], "archivedBy": _user_id(actor), "archivedAt": at})


def _checker_role(component: Any) -> str:
    if not truthy(component):
        return "OTHER"
    component_id = jsget(component, "componentId")
    if truthy(component_id) and component_id in _ENPHASE_COMPONENT_ROLES:
        return _ENPHASE_COMPONENT_ROLES[component_id]
    role = jsget(component, "role")
    if truthy(role) and role in _CATEGORY_TO_CHECKER_ROLE:
        return _CATEGORY_TO_CHECKER_ROLE[role]
    return "OTHER"


def run_package_checker(registry: dict, env: Any, *, actor: Any, package_id: Any, at: Any, check_project_bom: Callable[[dict], dict], authorize: Authorize = assert_can) -> dict:
    """Run the engineering checker at TEMPLATE scope and pin the result (with the revision) on ``lastValidation``.

    ``check_project_bom`` receives the JS argument object of ``engineeringChecker.checkProjectBom`` as one dict.
    """
    authorize(actor, CAPABILITY["BOM_RUN_CHECKER"])
    _require_at(at)
    pkg = _find_package(registry, package_id)
    if pkg is None:
        raise _not_found(package_id)
    architecture = pkg.get("architecture")
    if architecture is not None and architecture not in VALID_ARCHITECTURES:
        raise _architecture_invalid(architecture)
    env = env if isinstance(env, dict) else {}
    resolved = resolve_package_architecture(pkg, env.get("catalog"))
    if not resolved["architecture"]:
        raise ApprovalError(
            f'Package "{js_str(package_id)}" has no architecture declared and its profile "{js_str(jsget(pkg, "profileKey"))}" ' "declares no inverterType; the checker cannot run.",
            APPROVAL_ERROR["ARCHITECTURE_UNDECLARED"],
            {"packageId": package_id, "profileKey": nullish(jsget(pkg, "profileKey"), None)},
        )
    components = pkg.get("components") if is_array(pkg.get("components")) else []
    lines = [clean({"role": _checker_role(c), "componentId": jsget(c, "componentId"), "quantity": jsget(c, "quantity")}) for c in components]
    lines = _stable_sort(lines, lambda a, b: locale_compare(js_str(a["role"]), js_str(b["role"])))
    bom = {"phase": jsget(pkg, "phase"), "architecture": resolved["architecture"], "sysType": nullish(jsget(pkg, "systemType"), None), "lines": lines}
    validation = check_project_bom(
        {
            "bom": clean(bom),
            "lines": lines,
            "templateScope": True,
            "catalog": env.get("catalog") if truthy(env.get("catalog")) else {"categories": {}},
            "batteryMaster": env.get("batteryMaster") if truthy(env.get("batteryMaster")) else {},
            "at": at,
            "catalogVersion": nullish(env.get("catalogVersion"), None),
            "upgrade": None,
            "futureUpgrade": False,
        }
    )
    revision_number = pkg.get("revisionNumber") if truthy(pkg.get("revisionNumber")) else 1
    pkg["lastValidation"] = {**validation, "revisionNumber": revision_number, "architecture": resolved["architecture"], "architectureSource": resolved["source"]}
    return pkg["lastValidation"]


def _stable_sort(items: list, compare: Callable[[Any, Any], int]) -> list:
    return sorted(items, key=functools.cmp_to_key(compare))


# ---------------------------------------------------------------------------------------------------------------
# packageAuthority.js
# ---------------------------------------------------------------------------------------------------------------


def _selectable_component(category_key: str, item: Any) -> dict | None:
    if not truthy(item):
        return None
    status = item.get("status") if truthy(item.get("status")) else "ACTIVE"
    tiers = item.get("tiers") if is_array(item.get("tiers")) else []
    return {"componentId": jsget(item, "id"), "status": status, "tiers": tiers, "raw": item}


def derive_package_components(profile: Any, catalog: Any, *, tier: Any = None, phase: Any = None) -> dict:
    """``{components: {role: {...}}, unpinnedRoles}``: explicit profile components win, else the first eligible item."""
    components: dict[str, dict] = {}
    unpinned: list[str] = []
    for role in PACKAGE_ROLES:
        category_key = ROLE_TO_CATEGORY[role]
        raw_items = jsget(jsget(jsget(catalog, "categories"), category_key), "items")
        items = [_selectable_component(category_key, i) for i in (raw_items if truthy(raw_items) else [])]
        items = [c for c in items if c is not None and c["status"] == "ACTIVE" and len(c["tiers"]) > 0]
        items = [c for c in items if not truthy(tier) or tier in c["tiers"]]
        items = [c for c in items if not truthy(phase) or not truthy(jsget(c["raw"], "phase")) or c["raw"].get("phase") == phase]
        explicit_id = jsget(jsget(profile, "components"), role)
        if not truthy(explicit_id):
            explicit_id = jsget(profile, "batteryComponentId") if role == "battery" else None
        explicit = next((c for c in items if strict_equal(c["componentId"], explicit_id)), None) if truthy(explicit_id) else None
        if not items and explicit is None:
            continue
        chosen = explicit or items[0]
        if explicit is None:
            unpinned.append(role)
        components[role] = {
            "role": role,
            "category": category_key,
            "componentId": chosen["componentId"] if truthy(chosen["componentId"]) else None,
            "pinned": explicit is not None,
            "salesSelectable": role in SALES_SELECTABLE_ROLES,
            "approvedAlternates": [c["componentId"] for c in items],
        }
    return {"components": components, "unpinnedRoles": unpinned}


def is_approved_selection(package_components: Any, role: Any, component_id: Any) -> bool:
    entry = jsget(package_components, role)
    if not truthy(entry):
        return False
    return strict_equal(entry.get("componentId"), component_id) or component_id in (entry.get("approvedAlternates") or [])


def is_sales_editable(role: Any) -> bool:
    """May a Sales user change this role at all (decision C12)?"""
    return role in SALES_SELECTABLE_ROLES


# ---------------------------------------------------------------------------------------------------------------
# packageProjection.js
# ---------------------------------------------------------------------------------------------------------------


def _hydrate_record(record: Any) -> Any:
    if not truthy(record) or not isinstance(record, dict):
        return record
    approval_status = nullish(jsget(record, "approvalStatus"), None)
    has_created_by = record.get("createdBy") is not None
    has_created_at = record.get("createdAt") is not None
    legacy_approved = approval_status == "APPROVED" and not has_created_by and not has_created_at
    if not is_nullish(jsget(record, "packageState")):
        package_state = record["packageState"]
    elif approval_status == "APPROVED":
        package_state = "APPROVED"
    elif approval_status == "REJECTED":
        package_state = "REJECTED"
    else:
        package_state = "DRAFT"
    base_key = "|".join(js_str(nullish(jsget(record, k), "")) for k in ("systemType", "size", "phase", "tier"))
    combo_key = f"{base_key}|FR{js_str(record['systemSize'])}" if record.get("variant") == "FUTURE_READY" and truthy(record.get("systemSize")) else base_key
    hydrated = dict(record)
    hydrated.update(
        {
            "packageState": package_state,
            "revisionNumber": nullish(jsget(record, "revisionNumber"), 1),
            "comboKey": combo_key,
            "supersededBy": nullish(jsget(record, "supersededBy"), None),
            "architecture": nullish(jsget(record, "architecture"), None),
            "createdBy": nullish(jsget(record, "createdBy"), None),
            "createdAt": nullish(jsget(record, "createdAt"), None),
            "submittedBy": nullish(jsget(record, "submittedBy"), None),
            "submittedAt": nullish(jsget(record, "submittedAt"), None),
            "archivedBy": nullish(jsget(record, "archivedBy"), None),
            "archivedAt": nullish(jsget(record, "archivedAt"), None),
            "archivalReason": nullish(jsget(record, "archivalReason"), None),
            "lastValidation": nullish(jsget(record, "lastValidation"), None),
            "legacyApproved": legacy_approved,
        }
    )
    return hydrated


def hydrate_registry(raw: Any) -> dict:
    """Project a raw registry into the V4 record shape (pure, idempotent; never synthesises a validation)."""
    packages = jsget(raw, "packages")
    return {"schema": nullish(jsget(raw, "schema"), None), "packages": [_hydrate_record(p) for p in (packages if is_array(packages) else [])]}


def visible_for_runtime(hydrated: Any) -> dict:
    """The packages Sales runtime may see: APPROVED, not superseded, not archived."""
    packages = jsget(hydrated, "packages")
    return {
        "schema": nullish(jsget(hydrated, "schema"), None),
        "packages": [p for p in (packages if is_array(packages) else []) if jsget(p, "packageState") == "APPROVED" and not truthy(jsget(p, "supersededBy")) and jsget(p, "packageState") != "ARCHIVED"],
    }
