# Generated by Django 6.0.8 on 2026-09-28 22:45

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import hr.models.shift
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(help_text="Employee code (unique among live employees, case-insensitive).", max_length=50)),
                ("full_name", models.CharField(max_length=150)),
                ("department", models.CharField(blank=True, default="", max_length=100)),
                ("designation", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(blank=True, default="", help_text="Contact address; not unique and not the login.", max_length=254)),
                ("phone_e164", models.CharField(blank=True, default="", max_length=16)),
                ("joined_on", models.DateField(blank=True, null=True)),
                ("left_on", models.DateField(blank=True, null=True)),
                ("identity_method", models.CharField(choices=[("UNSPECIFIED", "Not stated"), ("FACE", "Face"), ("CARD", "Card"), ("FACE_CARD", "Face or card")], default="UNSPECIFIED", max_length=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("photo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employee", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "hr_employee",
                "ordering": ["full_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("paid", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True, help_text="When false, self-service requests are approved on creation.")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "hr_leave_type",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("is_half_day", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], default="PENDING", max_length=12)),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_records", to="hr.employee")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("leave_type", models.ForeignKey(db_column="type_id", on_delete=django.db.models.deletion.PROTECT, related_name="leave_records", to="hr.leavetype")),
            ],
            options={
                "db_table": "hr_leave_record",
                "ordering": ["-date_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField(blank=True, default="")),
                ("timezone", models.CharField(default="Asia/Kolkata", help_text="IANA zone (validated against zoneinfo).", max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "hr_office",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="", help_text="DV-49: kept from eSSL.")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="holidays", to="hr.office")),
            ],
            options={
                "db_table": "hr_holiday",
                "ordering": ["date", "id"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="office",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employees", to="hr.office"),
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(help_text="On the next day when is_overnight.")),
                ("is_overnight", models.BooleanField(default=False)),
                ("overnight_buffer_minutes", models.PositiveIntegerField(default=180)),
                ("grace_minutes", models.PositiveIntegerField(default=10)),
                ("late_threshold_minutes", models.PositiveIntegerField(default=0, help_text="Further allowance beyond grace before a day is late.")),
                ("early_exit_threshold_minutes", models.PositiveIntegerField(default=15)),
                ("full_day_minutes", models.PositiveIntegerField(default=480)),
                ("half_day_minutes", models.PositiveIntegerField(default=240)),
                ("half_day_after_minutes", models.PositiveIntegerField(default=30, help_text="Arrivals later than start + this are a half day (A5).")),
                ("break_minutes", models.PositiveIntegerField(default=60)),
                ("auto_deduct_break", models.BooleanField(default=True)),
                ("debounce_minutes", models.PositiveIntegerField(default=2, help_text="Punches within this many minutes of the previous one are ignored (A3).")),
                ("overtime_enabled", models.BooleanField(default=True)),
                ("overtime_after_minutes", models.PositiveIntegerField(default=480)),
                ("working_days", models.JSONField(default=hr.models.shift._default_working_days, help_text="Weekdays 0=Monday … 6=Sunday.")),
                ("weekly_off_days", models.JSONField(default=hr.models.shift._default_weekly_off_days, help_text="Weekdays 0=Monday … 6=Sunday; wins over working_days.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "hr_shift",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="office",
            name="default_shift",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_for_offices", to="hr.shift"),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employees", to="hr.shift"),
        ),
        migrations.CreateModel(
            name="AttendanceRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=120)),
                ("rules", models.JSONField(default=dict)),
                ("effective_from", models.DateField(blank=True, help_text="Applies to work dates on or after this date (always when empty).", null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attendance_rules", to="hr.office")),
                ("shift", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attendance_rules", to="hr.shift")),
            ],
            options={
                "db_table": "hr_attendance_rule",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper("code"), condition=models.Q(("deleted_at__isnull", True)), name="hr_leave_type_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.CheckConstraint(condition=models.Q(("code", ""), _negated=True), name="hr_leave_type_code_not_blank"),
        ),
        migrations.AddIndex(
            model_name="leaverecord",
            index=models.Index(fields=["employee", "date_from"], name="hr_leave_employee_from_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverecord",
            index=models.Index(fields=["status", "date_from"], name="hr_leave_status_from_idx"),
        ),
        migrations.AddConstraint(
            model_name="leaverecord",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["PENDING", "APPROVED", "REJECTED", "CANCELLED"])), name="hr_leave_record_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="leaverecord",
            constraint=models.CheckConstraint(condition=models.Q(("date_to__gte", models.F("date_from"))), name="hr_leave_record_dates_ordered"),
        ),
        migrations.AddConstraint(
            model_name="leaverecord",
            constraint=models.CheckConstraint(condition=models.Q(("is_half_day", False), ("date_to", models.F("date_from")), _connector="OR"), name="hr_leave_record_half_day_single_date"),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(fields=["date"], name="hr_holiday_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="holiday",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("office__isnull", False)), fields=("office", "date"), name="hr_holiday_office_date_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="holiday",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("office__isnull", True)), fields=("date",), name="hr_holiday_global_date_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper("code"), condition=models.Q(("deleted_at__isnull", True)), name="hr_shift_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("code", ""), _negated=True), name="hr_shift_code_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_time__lte", models.F("start_time")), ("is_overnight", True)), models.Q(("end_time__gt", models.F("start_time")), ("is_overnight", False)), _connector="OR"
                ),
                name="hr_shift_overnight_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("half_day_minutes__lte", models.F("full_day_minutes"))), name="hr_shift_half_day_within_full_day"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("overnight_buffer_minutes__lte", 720)), name="hr_shift_overnight_buffer_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("grace_minutes__lte", 720)), name="hr_shift_grace_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("late_threshold_minutes__lte", 720)), name="hr_shift_late_threshold_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("early_exit_threshold_minutes__lte", 720)), name="hr_shift_early_exit_threshold_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("full_day_minutes__lte", 1440)), name="hr_shift_full_day_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("half_day_minutes__lte", 1440)), name="hr_shift_half_day_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("half_day_after_minutes__lte", 720)), name="hr_shift_half_day_after_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("break_minutes__lte", 720)), name="hr_shift_break_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("debounce_minutes__lte", 60)), name="hr_shift_debounce_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(condition=models.Q(("overtime_after_minutes__lte", 1440)), name="hr_shift_overtime_after_minutes_max"),
        ),
        migrations.AddConstraint(
            model_name="office",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper("code"), condition=models.Q(("deleted_at__isnull", True)), name="hr_office_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="office",
            constraint=models.CheckConstraint(condition=models.Q(("code", ""), _negated=True), name="hr_office_code_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="office",
            constraint=models.CheckConstraint(condition=models.Q(("timezone", ""), _negated=True), name="hr_office_timezone_not_blank"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["office", "is_active"], name="hr_employee_office_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper("code"), condition=models.Q(("deleted_at__isnull", True)), name="hr_employee_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(condition=models.Q(("code", ""), _negated=True), name="hr_employee_code_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(condition=models.Q(("identity_method__in", ["UNSPECIFIED", "FACE", "CARD", "FACE_CARD"])), name="hr_employee_identity_method_valid"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(condition=models.Q(("phone_e164", ""), ("phone_e164__regex", "^\\+[1-9][0-9]{6,14}$"), _connector="OR"), name="hr_employee_phone_e164_valid"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(("left_on__isnull", True), ("joined_on__isnull", True), ("left_on__gte", models.F("joined_on")), _connector="OR"), name="hr_employee_left_after_joined"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerule",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="hr_attendance_rule_name_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="attendancerule",
            constraint=models.CheckConstraint(condition=models.Q(("office__isnull", True), ("shift__isnull", True), _connector="OR"), name="hr_attendance_rule_single_scope"),
        ),
    ]
