# Generated by Django 6.0.8 on 2026-09-28 21:16

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pincode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("pincode", models.CharField(max_length=6)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("serviceable", models.BooleanField(default=True, help_text="Whether Flarize installs in this pincode.")),
                ("distance_km_from_office", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_pincode",
                "ordering": ["pincode"],
            },
        ),
        migrations.CreateModel(
            name="PincodeOffice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("office_name", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("division", models.CharField(blank=True, default="", max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("pincode", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offices", to="reference.pincode")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_pincode_office",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RoomSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("bhk_type", models.PositiveSmallIntegerField()),
                ("size", models.PositiveIntegerField(help_text="Square feet.")),
                ("units", models.PositiveIntegerField(help_text="Typical monthly consumption (kWh).")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_room_size",
                "ordering": ["sort_order", "bhk_type", "size", "id"],
            },
        ),
        migrations.CreateModel(
            name="Wattage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("value", models.PositiveIntegerField()),
                ("show_in_ui", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_wattage",
                "ordering": ["sort_order", "value", "id"],
            },
        ),
        migrations.CreateModel(
            name="Appliance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=100)),
                ("name_ml", models.CharField(blank=True, default="", help_text="Malayalam name (falls back to English).", max_length=100)),
                ("icon", models.CharField(blank=True, default="", help_text="Emoji or short icon key.", max_length=16)),
                ("watts", models.PositiveIntegerField()),
                ("default_hours", models.DecimalField(decimal_places=2, help_text="Default hours of use per day (0–24).", max_digits=4)),
                ("is_optional", models.BooleanField(default=False, help_text="Offered as an add-on row (water pump, EV charging …).")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_appliance",
                "ordering": ["sort_order", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="reference_appliance_code_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("code__regex", "^[a-z0-9_]{2,32}$")), name="reference_appliance_code_format"),
                    models.CheckConstraint(condition=models.Q(("default_hours__gte", 0), ("default_hours__lte", 24)), name="reference_appliance_hours_range"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("name", models.CharField(max_length=100)),
                ("show_in_ui", models.BooleanField(default=True)),
                ("url", models.CharField(blank=True, default="", help_text="Icon URL.", max_length=255)),
                ("watts", models.PositiveIntegerField(blank=True, null=True)),
                ("k_value", models.FloatField(blank=True, help_text="Usage factor applied by the advanced calculator.", null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_device_type",
                "ordering": ["sort_order", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True)), name="reference_device_type_name_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("k_value__isnull", True), ("k_value__gte", 0), _connector="OR"), name="reference_device_type_k_value_non_negative"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvCar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("model", models.CharField(max_length=100)),
                ("battery_capacity", models.FloatField(help_text="kWh.")),
                ("claimed_range", models.PositiveIntegerField(help_text="km.")),
                ("adjusted_real_world_range", models.PositiveIntegerField(help_text="km.")),
                ("ex_showroom_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("energy_consumption", models.FloatField(blank=True, help_text="kWh per km.", null=True)),
                ("k_value", models.FloatField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_ev_car",
                "ordering": ["sort_order", "model", "id"],
                "constraints": [
                    models.UniqueConstraint(django.db.models.functions.text.Lower("model"), condition=models.Q(("deleted_at__isnull", True)), name="reference_ev_car_model_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("battery_capacity__gte", 0)), name="reference_ev_car_battery_non_negative"),
                    models.CheckConstraint(condition=models.Q(("ex_showroom_price__gte", 0)), name="reference_ev_car_price_non_negative"),
                    models.CheckConstraint(condition=models.Q(("energy_consumption__isnull", True), ("energy_consumption__gte", 0), _connector="OR"), name="reference_ev_car_consumption_non_negative"),
                    models.CheckConstraint(condition=models.Q(("k_value__isnull", True), ("k_value__gte", 0), _connector="OR"), name="reference_ev_car_k_value_non_negative"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvScooter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("model", models.CharField(max_length=100)),
                ("battery_capacity", models.FloatField(help_text="kWh.")),
                ("claimed_range", models.PositiveIntegerField(help_text="km.")),
                ("adjusted_real_world_range", models.PositiveIntegerField(help_text="km.")),
                ("ex_showroom_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("energy_consumption", models.FloatField(blank=True, help_text="kWh per km.", null=True)),
                ("k_value", models.FloatField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_ev_scooter",
                "ordering": ["sort_order", "model", "id"],
                "constraints": [
                    models.UniqueConstraint(django.db.models.functions.text.Lower("model"), condition=models.Q(("deleted_at__isnull", True)), name="reference_ev_scooter_model_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("battery_capacity__gte", 0)), name="reference_ev_scooter_battery_non_negative"),
                    models.CheckConstraint(condition=models.Q(("ex_showroom_price__gte", 0)), name="reference_ev_scooter_price_non_negative"),
                    models.CheckConstraint(
                        condition=models.Q(("energy_consumption__isnull", True), ("energy_consumption__gte", 0), _connector="OR"), name="reference_ev_scooter_consumption_non_negative"
                    ),
                    models.CheckConstraint(condition=models.Q(("k_value__isnull", True), ("k_value__gte", 0), _connector="OR"), name="reference_ev_scooter_k_value_non_negative"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KsebTariff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are hidden from the website.")),
                ("sort_order", models.IntegerField(default=0, help_text="Display order on the website (ascending).")),
                ("slab_from_units", models.PositiveIntegerField(help_text="First unit (kWh per month) of the slab.")),
                ("slab_to_units", models.PositiveIntegerField(blank=True, help_text="Last unit of the slab; empty = no upper limit.", null=True)),
                ("phase", models.CharField(blank=True, choices=[("1P", "Single phase"), ("3P", "Three phase")], help_text="Empty = applies to every phase.", max_length=4, null=True)),
                ("rate_per_unit", models.DecimalField(decimal_places=4, max_digits=10)),
                ("fixed_charge", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reference_kseb_tariff",
                "ordering": ["phase", "effective_from", "slab_from_units", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)), fields=("phase", "effective_from", "slab_from_units"), name="reference_kseb_tariff_slab_live_uniq", nulls_distinct=False
                    ),
                    models.CheckConstraint(condition=models.Q(("phase__isnull", True), ("phase__in", ["1P", "3P"]), _connector="OR"), name="reference_kseb_tariff_phase_valid"),
                    models.CheckConstraint(
                        condition=models.Q(("slab_to_units__isnull", True), ("slab_to_units__gte", models.F("slab_from_units")), _connector="OR"), name="reference_kseb_tariff_slab_ordered"
                    ),
                    models.CheckConstraint(condition=models.Q(("rate_per_unit__gte", 0)), name="reference_kseb_tariff_rate_non_negative"),
                    models.CheckConstraint(condition=models.Q(("fixed_charge__gte", 0)), name="reference_kseb_tariff_fixed_charge_non_negative"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="pincode",
            index=models.Index(fields=["district"], name="reference_pincode_district"),
        ),
        migrations.AddConstraint(
            model_name="pincode",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("pincode",), name="reference_pincode_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="pincode",
            constraint=models.CheckConstraint(condition=models.Q(("pincode__regex", "^[1-9][0-9]{5}$")), name="reference_pincode_format"),
        ),
        migrations.AddConstraint(
            model_name="pincode",
            constraint=models.CheckConstraint(
                condition=models.Q(("distance_km_from_office__isnull", True), ("distance_km_from_office__gte", 0), _connector="OR"), name="reference_pincode_distance_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodeoffice",
            index=models.Index(fields=["pincode", "sort_order"], name="reference_pincode_office_order"),
        ),
        migrations.AddIndex(
            model_name="pincodeoffice",
            index=models.Index(fields=["district"], name="reference_pincode_office_dist"),
        ),
        migrations.AddConstraint(
            model_name="roomsize",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("bhk_type", "size"), name="reference_room_size_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="roomsize",
            constraint=models.CheckConstraint(condition=models.Q(("bhk_type__gte", 1)), name="reference_room_size_bhk_positive"),
        ),
        migrations.AddConstraint(
            model_name="roomsize",
            constraint=models.CheckConstraint(condition=models.Q(("size__gte", 1)), name="reference_room_size_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="wattage",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("value",), name="reference_wattage_value_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="wattage",
            constraint=models.CheckConstraint(condition=models.Q(("value__gte", 1)), name="reference_wattage_value_positive"),
        ),
    ]
