# Generated by Django 6.0.8 on 2026-09-29 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("rules_version", models.CharField(help_text="PLAN `version` (e.g. phase1e.1); renamed: `version` is the optimistic lock.", max_length=16)),
                (
                    "engine",
                    models.CharField(
                        choices=[("engineeringChecker", "BOM checker (PBC rules)"), ("engineeringValidation", "Engineering validation (ENG rules)")], default="engineeringChecker", max_length=24
                    ),
                ),
                ("rules", models.JSONField(help_text="engines.engineering_checker.RuleSet.as_json(): {engine, version, rules[]} with severities and parameters.")),
                ("active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "engineering_rule_set",
                "ordering": ["engine", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("subject_type", models.CharField(choices=[("PACK_CONFIG_VERSION", "Pack config version"), ("PROJECT_BOM", "Project BOM"), ("QUOTATION_DRAFT", "Quotation draft")], max_length=24)),
                ("subject_uid", models.UUIDField()),
                ("subject_label", models.CharField(blank=True, default="", max_length=120)),
                ("result", models.CharField(choices=[("PASS", "Pass"), ("WARN", "Warnings"), ("FAIL", "Blocked")], max_length=8)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("rule_set", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="engineering.ruleset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "engineering_run",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("rule_code", models.CharField(max_length=16)),
                ("severity", models.CharField(choices=[("BLOCK", "Block"), ("WARN", "Warning"), ("INFO", "Info")], max_length=8)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("identity", models.CharField(help_text="rule|components|pack — stable across runs of one subject (acknowledgements carry over).", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="engineering.run")),
            ],
            options={
                "db_table": "engineering_finding",
                "ordering": ["run_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Acknowledgement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("reason", models.TextField()),
                ("at", models.DateTimeField()),
                ("acknowledged_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("finding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="acknowledgements", to="engineering.finding")),
            ],
            options={
                "db_table": "engineering_acknowledgement",
                "ordering": ["-at", "-id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("finding",), name="engineering_acknowledgement_one_per_finding"),
                    models.CheckConstraint(condition=models.Q(("reason", ""), _negated=True), name="engineering_acknowledgement_reason_required"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ruleset",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("rules_version",), name="engineering_rule_set_version_uniq"),
        ),
        migrations.AddConstraint(
            model_name="ruleset",
            constraint=models.UniqueConstraint(condition=models.Q(("active", True), ("deleted_at__isnull", True)), fields=("engine",), name="engineering_rule_set_one_active"),
        ),
        migrations.AddConstraint(
            model_name="ruleset",
            constraint=models.CheckConstraint(condition=models.Q(("engine__in", ["engineeringChecker", "engineeringValidation"])), name="engineering_rule_set_engine_valid"),
        ),
        migrations.AddConstraint(
            model_name="ruleset",
            constraint=models.CheckConstraint(condition=models.Q(("rules_version__regex", "^[A-Za-z0-9][A-Za-z0-9._-]{0,15}$")), name="engineering_rule_set_version_format"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["subject_type", "subject_uid", "-created_at"], name="engineering_run_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["result", "-created_at"], name="engineering_run_result_idx"),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(condition=models.Q(("subject_type__in", ["PACK_CONFIG_VERSION", "PROJECT_BOM", "QUOTATION_DRAFT"])), name="engineering_run_subject_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(condition=models.Q(("result__in", ["PASS", "WARN", "FAIL"])), name="engineering_run_result_valid"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["run", "severity"], name="engineering_finding_run_sev"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["identity"], name="engineering_finding_identity"),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(condition=models.Q(("severity__in", ["BLOCK", "WARN", "INFO"])), name="engineering_finding_severity_valid"),
        ),
    ]
