# Generated by Django 6.0.8 on 2026-09-28 22:18

import blog.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("delivery_id", models.BigIntegerField(editable=False)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.CharField(max_length=160)),
                ("role", models.CharField(blank=True, default="", help_text="byline role, e.g. 'Solar Engineer'", max_length=120)),
                ("bio", models.TextField(blank=True, default="")),
                ("avatar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_author",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("delivery_id", models.BigIntegerField(editable=False)),
                ("name", models.CharField(help_text="delivered as `label` (legacy name)", max_length=120)),
                ("slug", models.CharField(max_length=120)),
                ("color", models.CharField(default="#123532", max_length=9, validators=[blog.validators.validate_color])),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_badge",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("delivery_id", models.BigIntegerField(editable=False)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.CharField(max_length=120)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "blog_category",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("api_uid", models.CharField(help_text="public route segment, e.g. 'articles'", max_length=80, validators=[blog.validators.validate_api_uid])),
                ("singular_name", models.CharField(max_length=80)),
                ("plural_name", models.CharField(help_text="PLAN §2.8 `name` (the legacy CMS display name)", max_length=80)),
                ("description", models.TextField(blank=True, default="")),
                ("path_prefix", models.CharField(help_text="site path entries are published under, e.g. '/blog'", max_length=120, validators=[blog.validators.validate_path_prefix])),
                ("is_active", models.BooleanField(default=True, help_text="an inactive collection's whole route answers 404")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_collection",
                "ordering": ["plural_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("delivery_id", models.BigIntegerField(editable=False, help_text="the Strapi numeric `id` of the delivery contract (DV-34)")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, validators=[blog.validators.validate_entry_slug])),
                ("excerpt", models.TextField(blank=True, default="")),
                ("summary", models.JSONField(blank=True, default=list, help_text="Strapi-blocks array")),
                ("introduction", models.JSONField(blank=True, default=list, help_text="Strapi-blocks array")),
                ("warning", models.TextField(blank=True, default="", help_text="'important' callout")),
                ("insights", models.TextField(blank=True, default="", help_text="'key insight' callout")),
                ("read_time", models.PositiveSmallIntegerField(blank=True, help_text="minutes", null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("locale", models.CharField(default="en", max_length=2)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("REVIEW", "In review"), ("PUBLISHED", "Published"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, help_text="system first-publish stamp (never refreshed)", null=True)),
                ("published_on", models.DateTimeField(blank=True, help_text="author-set display date (seeded from published_at)", null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, help_text="the Beat task publishes the entry at this time", null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entries", to="blog.author")),
                ("collection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="blog.collection")),
                ("cover_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_entry",
                "ordering": ["sort_order", "-published_on", "-created_at", "delivery_id"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("delivery_id", models.BigIntegerField(editable=False)),
                ("position", models.IntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("RICH_TEXT", "Rich text"), ("IMAGE", "Image"), ("QUOTE", "Quote"), ("CTA", "Call to action"), ("EMBED", "Embed"), ("TABLE", "Table")],
                        default="RICH_TEXT",
                        max_length=12,
                    ),
                ),
                ("component", models.CharField(default="shared.rich-text", max_length=120)),
                ("data", models.JSONField(blank=True, default=list, help_text="the block body (Strapi-blocks array for RICH_TEXT)")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="content_blocks", to="blog.entry")),
            ],
            options={
                "db_table": "blog_content_block",
                "ordering": ["position", "delivery_id"],
            },
        ),
        migrations.CreateModel(
            name="EntryAttributeValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slot_key", models.CharField(max_length=60)),
                ("value", models.JSONField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attribute_values", to="blog.entry")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_entry_attribute_value",
                "ordering": ["slot_key", "id"],
            },
        ),
        migrations.CreateModel(
            name="EntryBadge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="blog.badge")),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="blog.entry")),
            ],
            options={
                "db_table": "blog_entry_badge",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="badges",
            field=models.ManyToManyField(blank=True, related_name="entries", through="blog.EntryBadge", to="blog.badge"),
        ),
        migrations.CreateModel(
            name="EntryCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="blog.category")),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="blog.entry")),
            ],
            options={
                "db_table": "blog_entry_category",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="entries", through="blog.EntryCategory", to="blog.category"),
        ),
        migrations.CreateModel(
            name="EntryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("group_key", models.CharField(max_length=60)),
                ("position", models.IntegerField(default=0)),
                ("external_url", models.URLField(blank=True, default="", max_length=1000)),
                ("alt", models.CharField(blank=True, default="", max_length=255)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="blog.entry")),
                ("media_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_entry_image",
                "ordering": ["group_key", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="EntrySeo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("seo_title", models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ("meta_description", models.TextField(blank=True, help_text="70–160 characters reads best in results")),
                ("canonical_url", models.URLField(blank=True, help_text="only when this URL duplicates another", max_length=1000)),
                ("og_title", models.CharField(blank=True, help_text="social share title; falls back to the SEO title", max_length=255)),
                ("og_description", models.TextField(blank=True, help_text="social share description; falls back to the meta description")),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("none", "No structured data"),
                            ("WebPage", "Web page"),
                            ("Article", "Article"),
                            ("FAQPage", "FAQ page"),
                            ("JobPosting", "Job posting"),
                            ("Organization", "Organization"),
                            ("BreadcrumbList", "Breadcrumb list"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("schema_extra", models.JSONField(blank=True, default=dict, help_text="only the structured fields the generator cannot infer from the record")),
                ("noindex", models.BooleanField(default=False, help_text="ask search engines not to index this URL")),
                ("keywords", models.TextField(blank=True, default="", help_text="comma-separated meta keywords (legacy CMS)")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("entry", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="seo", to="blog.entry")),
                ("og_image", models.ForeignKey(blank=True, help_text="social share image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_entry_seo",
            },
        ),
        migrations.CreateModel(
            name="EntrySlugHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("collection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="blog.collection")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slug_history", to="blog.entry")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_entry_slug_history",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("delivery_id", models.BigIntegerField(editable=False)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.CharField(max_length=80)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_tag",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="EntryTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="blog.entry")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="blog.tag")),
            ],
            options={
                "db_table": "blog_entry_tag",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="entries", through="blog.EntryTag", to="blog.tag"),
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_template",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="blog.template"),
        ),
        migrations.CreateModel(
            name="TemplateAttributeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="stable machine name (immutable)", max_length=60, validators=[blog.validators.validate_key])),
                ("label", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("RICHTEXT_BLOCKS", "Rich text (blocks)"), ("NUMBER", "Number"), ("BOOL", "Yes / no"), ("DATE", "Date"), ("ENUM", "Choice"), ("URL", "URL")],
                        default="TEXT",
                        max_length=16,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                ("required", models.BooleanField(default=False, help_text="enforced at publish time only")),
                ("position", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attribute_slots", to="blog.template")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_template_attribute_slot",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateImageGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="stable machine name, e.g. coverImg (immutable)", max_length=60, validators=[blog.validators.validate_key])),
                ("label", models.CharField(max_length=120)),
                ("repeatable", models.BooleanField(default=False)),
                ("max_items", models.PositiveIntegerField(blank=True, help_text="cap for a repeatable group; null = unbounded", null=True)),
                ("required", models.BooleanField(default=False, help_text="enforced at publish time only")),
                ("position", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="image_groups", to="blog.template")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "blog_template_image_group",
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="blog_author_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(fields=("delivery_id",), name="blog_author_delivery_id_uniq"),
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="blog_badge_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.UniqueConstraint(fields=("delivery_id",), name="blog_badge_delivery_id_uniq"),
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.CheckConstraint(condition=models.Q(("color__regex", "^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$")), name="blog_badge_color_hex"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="blog_category_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("delivery_id",), name="blog_category_delivery_id_uniq"),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("api_uid",), name="blog_collection_api_uid_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="contentblock",
            constraint=models.UniqueConstraint(fields=("delivery_id",), name="blog_content_block_delivery_id_uniq"),
        ),
        migrations.AddConstraint(
            model_name="contentblock",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["RICH_TEXT", "IMAGE", "QUOTE", "CTA", "EMBED", "TABLE"])), name="blog_content_block_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="entryattributevalue",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("entry", "slot_key"), name="blog_entry_attribute_value_slot_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="entrybadge",
            constraint=models.UniqueConstraint(fields=("entry", "badge"), name="blog_entry_badge_uniq"),
        ),
        migrations.AddConstraint(
            model_name="entrycategory",
            constraint=models.UniqueConstraint(fields=("entry", "category"), name="blog_entry_category_uniq"),
        ),
        migrations.AddConstraint(
            model_name="entryimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("media_asset__isnull", False), ("external_url", "")), models.Q(("media_asset__isnull", True), models.Q(("external_url", ""), _negated=True)), _connector="OR"
                ),
                name="blog_entry_image_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryslughistory",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("active", True)), fields=("collection", "slug"), name="blog_entry_slug_history_active_uniq"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="blog_tag_name_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="blog_tag_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(fields=("delivery_id",), name="blog_tag_delivery_id_uniq"),
        ),
        migrations.AddConstraint(
            model_name="entrytag",
            constraint=models.UniqueConstraint(fields=("entry", "tag"), name="blog_entry_tag_uniq"),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="blog_template_slug_live_uniq"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["collection", "status", "published_on"], name="blog_entry_delivery_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["status", "updated_at"], name="blog_entry_status_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(condition=models.Q(("scheduled_for__isnull", False)), fields=["scheduled_for"], name="blog_entry_scheduled_idx"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("collection", "slug"), name="blog_entry_collection_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(fields=("delivery_id",), name="blog_entry_delivery_id_uniq"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"])), name="blog_entry_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "PUBLISHED"), _negated=True), ("published_at__isnull", False), _connector="OR"), name="blog_entry_published_has_published_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "ARCHIVED"), _negated=True), ("archived_at__isnull", False), _connector="OR"), name="blog_entry_archived_has_archived_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(condition=models.Q(("scheduled_for__isnull", True), ("status__in", ["DRAFT", "REVIEW"]), _connector="OR"), name="blog_entry_schedule_only_unpublished"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(condition=models.Q(("verified_by__isnull", True), ("verified_at__isnull", False), _connector="OR"), name="blog_entry_verified_has_verified_at"),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(condition=models.Q(("locale__regex", "^[a-z]{2}$")), name="blog_entry_locale_format"),
        ),
        migrations.AddConstraint(
            model_name="templateattributeslot",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("template", "key"), name="blog_template_attribute_slot_key_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="templateattributeslot",
            constraint=models.CheckConstraint(condition=models.Q(("type__in", ["TEXT", "RICHTEXT_BLOCKS", "NUMBER", "BOOL", "DATE", "ENUM", "URL"])), name="blog_template_attribute_slot_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="templateimagegroup",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("template", "key"), name="blog_template_image_group_key_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="templateimagegroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_items__isnull", True), models.Q(("max_items__gte", 1), ("repeatable", True)), _connector="OR"), name="blog_template_image_group_max_items_valid"
            ),
        ),
    ]
