# Generated by Django 6.0.8 on 2026-09-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
