# The stock ledger of PLAN §2.3 (flag INVENTORY_STOCK). Generated by Django 6.0.8, then extended by hand with:
# * the inventory_balance VIEW (signed sum of the movements per component and location; Balance maps it unmanaged,
#   its relations are written into the state by hand because the autodetector leaves them out of unmanaged models);
# * the append-only privileges of inventory_movement (REVOKE UPDATE, DELETE, TRUNCATE from DB_APP_ROLE, as audit_log).

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

BALANCE_VIEW_SQL = """
CREATE VIEW inventory_balance AS
SELECT m.component_id,
       m.location_id,
       CAST(SUM(CASE WHEN m.direction = 'IN' THEN m.qty ELSE -m.qty END) AS numeric(18, 3)) AS qty,
       CAST(SUM(CASE WHEN m.direction = 'IN' THEN m.qty ELSE 0 END) AS numeric(18, 3)) AS qty_in,
       CAST(SUM(CASE WHEN m.direction = 'OUT' THEN m.qty ELSE 0 END) AS numeric(18, 3)) AS qty_out,
       CAST(COUNT(*) AS integer) AS movement_count,
       MAX(m.at) AS last_movement_at
FROM inventory_movement m
WHERE m.deleted_at IS NULL
GROUP BY m.component_id, m.location_id;
"""


def apply_append_only(apps, schema_editor):
    """REVOKE UPDATE, DELETE, TRUNCATE on inventory_movement from DB_APP_ROLE when the app runs as another role."""
    role = (getattr(settings, "DB_APP_ROLE", "") or "").strip()
    if not role:
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_user")
        if cursor.fetchone()[0] == role:
            return
    from inventory.services.privileges import apply_append_only_privileges

    apply_append_only_privileges(role)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(help_text="Short code, unique among live locations (case-insensitive), e.g. HO-STORE.", max_length=30)),
                ("name", models.CharField(max_length=150)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="hr.office")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "inventory_location",
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("qty", models.DecimalField(decimal_places=3, help_text="Always positive; the direction gives the sign.", max_digits=12)),
                ("direction", models.CharField(choices=[("IN", "In"), ("OUT", "Out")], max_length=3)),
                ("reason", models.CharField(choices=[("PURCHASE", "Purchase"), ("ISSUE_TO_PROJECT", "Issue to project"), ("RETURN", "Return"), ("ADJUST", "Adjustment")], max_length=16)),
                ("ref_type", models.CharField(blank=True, default="", help_text="What caused it, as <app>.<model> (e.g. procurement.batch_line).", max_length=64)),
                ("ref_uid", models.UUIDField(blank=True, null=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now, help_text="When the stock moved (may be earlier than created_at).")),
                ("note", models.TextField(blank=True, default="", help_text="Required for ADJUST (the adjustment's justification).")),
                ("by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.location")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "inventory_movement",
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper("code"), condition=models.Q(("deleted_at__isnull", True)), name="inventory_location_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(condition=models.Q(("code__regex", "^[A-Za-z0-9][A-Za-z0-9_.-]{0,29}$")), name="inventory_location_code_format"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="inventory_location_name_not_blank"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["component", "location"], name="inventory_mov_comp_loc_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["-at", "-id"], name="inventory_mov_at_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["location", "-at"], name="inventory_mov_location_at_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["ref_type", "ref_uid"], name="inventory_mov_ref_idx"),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(condition=models.Q(("qty__gt", 0)), name="inventory_movement_qty_positive"),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(condition=models.Q(("direction__in", ["IN", "OUT"])), name="inventory_movement_direction_valid"),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(condition=models.Q(("reason__in", ["PURCHASE", "ISSUE_TO_PROJECT", "RETURN", "ADJUST"])), name="inventory_movement_reason_valid"),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("direction", "IN"), ("reason", "PURCHASE")), models.Q(("direction", "OUT"), ("reason", "ISSUE_TO_PROJECT")), ("reason__in", ["RETURN", "ADJUST"]), _connector="OR"
                ),
                name="inventory_movement_reason_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ref_type", ""), ("ref_uid__isnull", True)), models.Q(("ref_type__regex", "^[a-z][a-z0-9_]*\\.[a-z][a-z0-9_]*$"), ("ref_uid__isnull", False)), _connector="OR"
                ),
                name="inventory_movement_ref_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("reason", "ADJUST"), _negated=True), models.Q(("note", ""), _negated=True), _connector="OR"), name="inventory_movement_adjust_has_note"
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.UniqueConstraint(condition=models.Q(("ref_type", "procurement.batch_line")), fields=("ref_type", "ref_uid"), name="inventory_movement_batch_line_uniq"),
        ),
        migrations.RunSQL(BALANCE_VIEW_SQL, "DROP VIEW IF EXISTS inventory_balance;"),
        migrations.CreateModel(
            name="Balance",
            fields=[
                ("pk", models.CompositePrimaryKey("component", "location", blank=True, editable=False, primary_key=True, serialize=False)),
                ("component", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="catalog.component")),
                ("location", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="inventory.location")),
                ("qty", models.DecimalField(decimal_places=3, max_digits=18)),
                ("qty_in", models.DecimalField(decimal_places=3, max_digits=18)),
                ("qty_out", models.DecimalField(decimal_places=3, max_digits=18)),
                ("movement_count", models.IntegerField()),
                ("last_movement_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inventory_balance",
                "ordering": ["component_id", "location_id"],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.RunPython(apply_append_only, migrations.RunPython.noop),
    ]
