# Generated by Django 6.0.8 on 2026-09-28 19:24

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("QUOTATION", "Quotation"),
                            ("AGREEMENT", "Agreement"),
                            ("INSPECTION_REPORT", "Inspection report"),
                            ("ATTENDANCE_REPORT", "Attendance report"),
                            ("PUBLISH_REPORT", "Publish report"),
                        ],
                        max_length=24,
                    ),
                ),
                ("object_type", models.CharField(max_length=64)),
                ("object_uid", models.UUIDField()),
                ("template", models.CharField(default="default", max_length=64)),
                ("language", models.CharField(choices=[("en", "English"), ("ml", "Malayalam"), ("hi", "Hindi")], max_length=2)),
                ("payload", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("QUEUED", "Queued"), ("RUNNING", "Running"), ("DONE", "Done"), ("FAILED", "Failed")], default="QUEUED", max_length=12)),
                ("file", models.CharField(blank=True, default="", max_length=512)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "documents_render_job",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentDownload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("used_user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("issued_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="downloads", to="documents.renderjob")),
            ],
            options={
                "db_table": "documents_download",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="renderjob",
            index=models.Index(fields=["object_type", "object_uid", "created_at"], name="documents_job_object_created"),
        ),
        migrations.AddIndex(
            model_name="renderjob",
            index=models.Index(condition=models.Q(("status__in", ["QUEUED", "RUNNING"])), fields=["status", "created_at"], name="documents_job_open_created"),
        ),
        migrations.AddConstraint(
            model_name="renderjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["QUOTATION", "AGREEMENT", "INSPECTION_REPORT", "ATTENDANCE_REPORT", "PUBLISH_REPORT"])), name="documents_job_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="renderjob",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["QUEUED", "RUNNING", "DONE", "FAILED"])), name="documents_job_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="renderjob",
            constraint=models.CheckConstraint(condition=models.Q(("language__in", ["en", "ml", "hi"])), name="documents_job_language_valid"),
        ),
        migrations.AddConstraint(
            model_name="renderjob",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "DONE"), _negated=True), models.Q(models.Q(("file", ""), _negated=True), ("page_count__gte", 1)), _connector="OR"),
                name="documents_job_done_has_file",
            ),
        ),
        migrations.AddIndex(
            model_name="documentdownload",
            index=models.Index(fields=["job", "created_at"], name="documents_download_job_created"),
        ),
    ]
