# Generated by Django 6.0.8 on 2026-09-28 21:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.SlugField(help_text="public identifier, e.g. 'career'", max_length=80)),
                ("route", models.CharField(help_text="site-relative path, e.g. '/career'", max_length=255)),
                ("title", models.CharField(help_text="how the page is referred to internally (legacy `name`)", max_length=160)),
                ("description", models.TextField(blank=True, default="", help_text="what this page is for; shown to maintainers")),
                ("group", models.CharField(blank=True, default="", help_text="grouping for the Pages list, e.g. 'Solutions'", max_length=80)),
                ("template", models.CharField(blank=True, default="", help_text="page component family on the website", max_length=32)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=12)),
                ("is_protected", models.BooleanField(default=True, help_text="copy/layout is developer-owned; only slots and SEO are editable")),
                ("sort_order", models.IntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, help_text="content reviewed; cleared by every content change", null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "sitepages_page",
                "ordering": ["sort_order", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageImageSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="stable machine name the page component reads", max_length=60)),
                ("label", models.CharField(max_length=120)),
                ("guidance", models.CharField(blank=True, default="", help_text="e.g. 'landscape, at least 1600×900'", max_length=255)),
                ("external_url", models.URLField(blank=True, default="", help_text="used when no asset is chosen", max_length=1000)),
                ("alt", models.CharField(blank=True, default="", help_text="overrides the asset's own alt text here", max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="image_slots", to="sitepages.page")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "sitepages_page_image_slot",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageSeo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("seo_title", models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ("meta_description", models.TextField(blank=True, help_text="70–160 characters reads best in results")),
                ("canonical_url", models.URLField(blank=True, help_text="only when this URL duplicates another", max_length=1000)),
                ("og_title", models.CharField(blank=True, help_text="social share title; falls back to the SEO title", max_length=255)),
                ("og_description", models.TextField(blank=True, help_text="social share description; falls back to the meta description")),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("none", "No structured data"),
                            ("WebPage", "Web page"),
                            ("Article", "Article"),
                            ("FAQPage", "FAQ page"),
                            ("JobPosting", "Job posting"),
                            ("Organization", "Organization"),
                            ("BreadcrumbList", "Breadcrumb list"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("schema_extra", models.JSONField(blank=True, default=dict, help_text="only the structured fields the generator cannot infer from the record")),
                ("noindex", models.BooleanField(default=False, help_text="ask search engines not to index this URL")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("og_image", models.ForeignKey(blank=True, help_text="social share image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("page", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="seo", to="sitepages.page")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "sitepages_page_seo",
            },
        ),
        migrations.CreateModel(
            name="PageTextSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="stable machine name the page component reads", max_length=60)),
                ("label", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SHORT_TEXT", "Short text"),
                            ("LONG_TEXT", "Long text"),
                            ("RICH_TEXT", "Rich text (light HTML)"),
                            ("MARKDOWN", "Markdown"),
                            ("URL", "URL"),
                            ("EMAIL", "E-mail"),
                            ("PHONE", "Phone"),
                        ],
                        default="SHORT_TEXT",
                        max_length=16,
                    ),
                ),
                ("guidance", models.CharField(blank=True, default="", max_length=255)),
                ("value", models.TextField(blank=True, default="", help_text="empty = the page keeps its built-in text")),
                ("max_length", models.PositiveIntegerField(blank=True, help_text="cap enforced on every edit; null = uncapped", null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="text_slots", to="sitepages.page")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "sitepages_page_text_slot",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["status", "sort_order"], name="sitepages_page_status_sort"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["group", "sort_order"], name="sitepages_page_group_sort"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="sitepages_page_slug_uniq"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("route",), name="sitepages_page_route_uniq"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "ARCHIVED"])), name="sitepages_page_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")), name="sitepages_page_slug_format"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(condition=models.Q(("route__regex", "^/[^\\s?#]*$")), name="sitepages_page_route_format"),
        ),
        migrations.AddConstraint(
            model_name="pageimageslot",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("page", "key"), name="sitepages_image_slot_page_key_uniq"),
        ),
        migrations.AddConstraint(
            model_name="pageimageslot",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[A-Za-z][A-Za-z0-9_-]*$")), name="sitepages_image_slot_key_format"),
        ),
        migrations.AddConstraint(
            model_name="pageseo",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_type__in", ["none", "WebPage", "Article", "FAQPage", "JobPosting", "Organization", "BreadcrumbList"])), name="sitepages_page_seo_schema_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetextslot",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("page", "key"), name="sitepages_text_slot_page_key_uniq"),
        ),
        migrations.AddConstraint(
            model_name="pagetextslot",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["SHORT_TEXT", "LONG_TEXT", "RICH_TEXT", "MARKDOWN", "URL", "EMAIL", "PHONE"])), name="sitepages_text_slot_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="pagetextslot",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[A-Za-z][A-Za-z0-9_-]*$")), name="sitepages_text_slot_key_format"),
        ),
        migrations.AddConstraint(
            model_name="pagetextslot",
            constraint=models.CheckConstraint(condition=models.Q(("max_length__isnull", True), ("max_length__gt", 0), _connector="OR"), name="sitepages_text_slot_max_length_positive"),
        ),
    ]
