# Generated by Django 6.0.8 on 2026-09-28 22:22

import core.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm (a trusted extension): the GIN trigram index on UPPER(name) behind the customer name search.
        TrigramExtension(),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("body", models.TextField()),
                ("pinned", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "customers_note",
                "ordering": ["-pinned", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(help_text="CUST-… (Flarize ids are kept for migrated rows).", max_length=24)),
                ("name", models.CharField(max_length=255)),
                ("phone_e164", models.CharField(blank=True, default="", help_text="E.164; unique among live customers.", max_length=16)),
                ("alt_phone", models.CharField(blank=True, default="", help_text="Second number as entered (E.164 when it parses).", max_length=20)),
                ("email", core.models.fields.CIEmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("pincode", models.CharField(blank=True, default="", max_length=6)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("location", models.CharField(blank=True, default="", max_length=120)),
                ("google_map_link", models.URLField(blank=True, default="", max_length=500)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("current_bill", models.DecimalField(blank=True, decimal_places=2, help_text="Electricity bill amount (INR) per bill_cycle.", max_digits=10, null=True)),
                (
                    "bill_cycle",
                    models.CharField(
                        blank=True, choices=[("MONTHLY", "Monthly"), ("BIMONTHLY", "Every two months")], default="", help_text="The period current_bill covers (Flarize billCycle).", max_length=12
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("WEBSITE", "Website"), ("SALES_ENTRY", "Sales entry"), ("REFERRAL", "Referral"), ("PA_IMPORT", "Purchase agreement import"), ("SI_IMPORT", "Site inspection import")],
                        default="SALES_ENTRY",
                        max_length=16,
                    ),
                ),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "customers_customer",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
