# Generated by Django 6.0.8 on 2026-09-28 22:22

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="leads.lead"),
        ),
        migrations.AddField(
            model_name="customer",
            name="merged_into",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="customers.customer"),
        ),
        migrations.AddField(
            model_name="customer",
            name="owner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="customernote",
            name="created_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="customernote",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="customers.customer"),
        ),
        migrations.AddField(
            model_name="customernote",
            name="updated_by",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"), name="customers_customer_name_trgm"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["created_at"], name="customers_customer_created"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="customers_customer_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("phone_e164", ""), _negated=True)), fields=("phone_e164",), name="customers_customer_phone_live_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("source__in", ["WEBSITE", "SALES_ENTRY", "REFERRAL", "PA_IMPORT", "SI_IMPORT"])), name="customers_customer_source_valid"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("bill_cycle__in", ["", "MONTHLY", "BIMONTHLY"])), name="customers_customer_bill_cycle_valid"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("phone_e164", ""), ("phone_e164__regex", "^\\+[1-9][0-9]{7,14}$"), _connector="OR"), name="customers_customer_phone_e164_format"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("pincode", ""), ("pincode__regex", "^[1-9][0-9]{5}$"), _connector="OR"), name="customers_customer_pincode_format"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("code", ""), _negated=True), name="customers_customer_code_present"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__isnull", True), models.Q(("latitude__gte", -90), ("latitude__lte", 90)), _connector="OR"), name="customers_customer_latitude_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__isnull", True), models.Q(("longitude__gte", -180), ("longitude__lte", 180)), _connector="OR"), name="customers_customer_longitude_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("current_bill__isnull", True), ("current_bill__gte", 0), _connector="OR"), name="customers_customer_current_bill_positive"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(condition=models.Q(("merged_into__isnull", True), ("deleted_at__isnull", False), _connector="OR"), name="customers_customer_merged_is_deleted"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("merged_into__isnull", True), models.Q(("merged_into", models.F("id")), _negated=True), _connector="OR"), name="customers_customer_not_merged_into_self"
            ),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(fields=["customer", "created_at"], name="customers_note_customer_at"),
        ),
        migrations.AddConstraint(
            model_name="customernote",
            constraint=models.CheckConstraint(condition=models.Q(("body", ""), _negated=True), name="customers_note_body_present"),
        ),
    ]
