# Generated by Django 6.0.8 on 2026-09-29 15:50

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bom", "0001_initial"),
        ("catalog", "0001_initial"),
        ("customers", "0002_initial"),
        ("documents", "0001_initial"),
        ("media", "0001_initial"),
        ("pricing", "0003_current_price_view_and_append_only"),
        ("quotations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "number",
                    models.CharField(blank=True, default="", help_text="AGR-<FY>-<nnnn> (core.sequences AGR), taken at issue; blank while DRAFT. Imported rows: <PROFILE>-<record id>.", max_length=48),
                ),
                ("kind", models.CharField(choices=[("PURCHASE_AGREEMENT", "Purchase agreement"), ("SALE_ORDER", "Sale order"), ("EXTRA_STRUCTURE", "Extra structure agreement")], max_length=20)),
                ("source_type", models.CharField(blank=True, choices=[("SITE_INSPECTION", "Site inspection")], default="", help_text="DV-3: what a blank agreement was raised from.", max_length=20)),
                ("source_uid", models.UUIDField(blank=True, help_text="DV-3: the uid of that record (e.g. the site inspection); no foreign key.", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("ACCEPTED", "Accepted"), ("SUPERSEDED", "Superseded"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=12
                    ),
                ),
                ("revision", models.PositiveSmallIntegerField(default=1, help_text="PLAN `version` (DV-136): 1, then +1 for every superseding agreement of the chain.")),
                ("language", models.CharField(choices=[("en", "English"), ("ml", "Malayalam"), ("hi", "Hindi")], default="en", max_length=2)),
                ("system_type", models.CharField(choices=[("ON_GRID", "On-grid"), ("HYBRID", "Hybrid")], default="ON_GRID", max_length=8)),
                ("capacity_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("size_label", models.CharField(blank=True, default="", help_text="The plant as printed (legacy `kw`, e.g. '5KW Plant with 6KW Inverter – Hybrid').", max_length=120)),
                ("phase", models.CharField(blank=True, choices=[("1P", "Single phase"), ("3P", "Three phase")], default="", max_length=2)),
                (
                    "variant",
                    models.CharField(blank=True, choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], default="", help_text="Package tier printed after the price.", max_length=8),
                ),
                ("panel_label", models.CharField(blank=True, default="", max_length=255)),
                ("panel_capacity_w", models.PositiveIntegerField(blank=True, null=True)),
                ("panel_capacity_label", models.CharField(blank=True, default="", help_text="Wattage range as printed (legacy `panelcap`, e.g. '545W – 580W').", max_length=64)),
                ("panel_dcr", models.BooleanField(blank=True, null=True)),
                ("panel_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("inverter_brand", models.CharField(blank=True, default="", max_length=100)),
                ("inverter_type", models.CharField(blank=True, choices=[("STRING", "String Inverter"), ("MICRO", "Micro Inverter"), ("HYBRID", "Hybrid Inverter")], default="", max_length=8)),
                ("inverter_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("battery_label", models.CharField(blank=True, default="", help_text="Battery option as printed ('' = None).", max_length=64)),
                ("battery_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("structure_type", models.CharField(blank=True, default="", help_text="Roof / installation type (FLAT, SHEET, ELEVATED).", max_length=24)),
                ("structure_material", models.CharField(blank=True, default="", max_length=120)),
                ("extra_structure", models.BooleanField(default=False)),
                ("walkway_required", models.BooleanField(default=False)),
                ("ladder_required", models.BooleanField(default=False)),
                ("original_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("extra_cost", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("final_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("statutory_fee_label", models.CharField(blank=True, default="", max_length=120)),
                ("statutory_fee_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("add_on_offer", models.TextField(blank=True, default="")),
                ("extra_description", models.TextField(blank=True, default="")),
                ("price_override_reason", models.TextField(blank=True, default="")),
                ("consumer_number", models.CharField(blank=True, default="", help_text="KSEB consumer number.", max_length=20)),
                ("registered_phone_e164", models.CharField(blank=True, default="", help_text="Phone registered with KSEB (E.164).", max_length=16)),
                ("wheeling_required", models.BooleanField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, help_text="The deep-frozen document, written once at issue (imported rows: + the raw browser record).", null=True)),
                ("payload_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_via", models.CharField(blank=True, choices=[("OTP", "Customer OTP"), ("PAPER", "Paper-signed copy")], default="", max_length=8)),
                ("acceptance_note", models.TextField(blank=True, default="")),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                ("legacy", models.BooleanField(default=False, help_text="Imported from the Purchase Agreement page (flarize_agr).")),
                ("legacy_ref", models.CharField(blank=True, default="", help_text="<profile>/<record id> of an imported record.", max_length=96)),
                ("legacy_quotation_ref", models.CharField(blank=True, default="", help_text="Quotation number typed on the legacy page (QUO-GR-AS-26-…).", max_length=48)),
                ("acceptance_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("acceptance_recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("battery", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agreements", to="customers.customer")),
                ("document_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="documents.renderjob")),
                ("inverter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("issued_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("panel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="catalog.component")),
                ("quotation_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="agreements", to="quotations.version")),
                ("statutory_fee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="pricing.statutoryfee")),
                ("structure_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="bom.structuretemplate")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="superseded_by", to="agreements.agreement")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agreements_agreement",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgreementLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(blank=True, default="", max_length=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("additional_work_item_uid", models.UUIDField(blank=True, help_text="DV-3: the site-inspection additional-work item this line prices (no foreign key).", null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("agreement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="agreements.agreement")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agreements_line",
                "ordering": ["agreement_id", "sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(fields=["owner", "-created_at"], name="agreements_agreement_owner"),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(fields=["customer", "-created_at"], name="agreements_agreement_customer"),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(fields=["status", "kind"], name="agreements_agreement_status"),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(fields=["source_type", "source_uid"], name="agreements_agreement_source"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), models.Q(("number", ""), _negated=True)), fields=("number",), name="agreements_agreement_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("legacy_ref", ""), _negated=True)), fields=("legacy_ref",), name="agreements_agreement_legacy_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "ISSUED")), fields=("quotation_version", "kind"), name="agreements_agreement_one_issued"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "DRAFT")), fields=("quotation_version", "kind"), name="agreements_agreement_one_draft"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("status", "CANCELLED"), _negated=True)), fields=("supersedes",), name="agreements_agreement_superseded_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["PURCHASE_AGREEMENT", "SALE_ORDER", "EXTRA_STRUCTURE"])), name="agreements_agreement_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "ISSUED", "ACCEPTED", "SUPERSEDED", "CANCELLED"])), name="agreements_agreement_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("language__in", ["en", "ml", "hi"])), name="agreements_agreement_language_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ON_GRID", "HYBRID"])), name="agreements_agreement_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["1P", "3P", ""])), name="agreements_agreement_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("variant__in", ["BASE", "VALUE", "PREMIUM", ""])), name="agreements_agreement_variant_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("inverter_type__in", ["STRING", "MICRO", "HYBRID", ""])), name="agreements_agreement_inverter_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("source_type__in", ["SITE_INSPECTION", ""])), name="agreements_agreement_source_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("accepted_via__in", ["OTP", "PAPER", ""])), name="agreements_agreement_accepted_via_valid"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("source_type", ""), ("source_uid__isnull", True)), models.Q(models.Q(("source_type", ""), _negated=True), ("source_uid__isnull", False)), _connector="OR"),
                name="agreements_agreement_source_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("source_type", ""), ("quotation_version__isnull", True), _connector="OR"), name="agreements_agreement_source_or_quotation"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("legacy", False), ("quotation_version__isnull", True), _connector="OR"), name="agreements_agreement_legacy_no_quotation"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("revision__gte", 1)), name="agreements_agreement_revision_positive"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(condition=models.Q(("capacity_kw__isnull", True), ("capacity_kw__gt", 0), _connector="OR"), name="agreements_agreement_capacity_positive"),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("original_price__isnull", True), ("original_price__gte", 0), _connector="OR"),
                    ("extra_cost__gte", 0),
                    ("discount__gte", 0),
                    models.Q(("final_price__isnull", True), ("final_price__gte", 0), _connector="OR"),
                    models.Q(("statutory_fee_amount__isnull", True), ("statutory_fee_amount__gte", 0), _connector="OR"),
                ),
                name="agreements_agreement_money_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legacy", True),
                    (
                        "final_price",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(models.F("original_price"), "+", models.F("extra_cost")), "-", models.F("discount")
                        ),
                    ),
                    ("final_price__isnull", True),
                    ("original_price__isnull", True),
                    _connector="OR",
                ),
                name="agreements_agreement_price_arithmetic",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ("ISSUED", "ACCEPTED", "SUPERSEDED")), _negated=True),
                    models.Q(models.Q(("number", ""), _negated=True), ("issued_at__isnull", False), ("payload__isnull", False), ("payload_sha256__regex", "^[0-9a-f]{64}$")),
                    _connector="OR",
                ),
                name="agreements_agreement_issued_is_frozen",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "DRAFT"), _negated=True), models.Q(("number", ""), ("payload__isnull", True), ("payload_sha256", "")), _connector="OR"),
                name="agreements_agreement_draft_not_frozen",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "ACCEPTED"), _negated=True), models.Q(("accepted_at__isnull", False), models.Q(("accepted_via", ""), _negated=True)), _connector="OR"),
                name="agreements_agreement_accepted_recorded",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "CANCELLED"), _negated=True), ("cancelled_at__isnull", False), _connector="OR"), name="agreements_agreement_cancelled_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementline",
            constraint=models.CheckConstraint(condition=models.Q(("description", ""), _negated=True), name="agreements_line_description_present"),
        ),
        migrations.AddConstraint(
            model_name="agreementline",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="agreements_line_quantity_positive"),
        ),
        migrations.AddConstraint(
            model_name="agreementline",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__gte", 0), ("amount__gte", 0)), name="agreements_line_money_not_negative"),
        ),
    ]
