# Generated by Django 6.0.8 on 2026-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agreement",
            name="agreements_agreement_one_issued",
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("status__in", ("ISSUED", "ACCEPTED"))), fields=("quotation_version", "kind"), name="agreements_agreement_one_in_force"
            ),
        ),
    ]
