# Generated by Django 6.0.8 on 2026-09-28 21:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatteryFamily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("voltage_class", models.CharField(choices=[("48V", "48 V (low voltage)"), ("HV", "High voltage")], max_length=8)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_battery_family",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("website", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("logo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_brand",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                (
                    "bom_role",
                    models.CharField(
                        choices=[
                            ("MAIN_PANEL", "Main panel"),
                            ("MAIN_INVERTER", "Main inverter"),
                            ("BATTERY", "Battery"),
                            ("PROTECTION", "Protection"),
                            ("CABLE", "Cable"),
                            ("EARTHING", "Earthing"),
                            ("STRUCTURE", "Structure"),
                            ("SERVICE", "Service"),
                            ("MISC", "Miscellaneous"),
                        ],
                        default="MISC",
                        max_length=24,
                    ),
                ),
                ("gst_rate", models.DecimalField(decimal_places=4, help_text="Default GST rate as a fraction (0.18 = 18 %).", max_digits=5)),
                ("hsn_code", models.CharField(blank=True, default="", max_length=12)),
                ("unit", models.CharField(choices=[("NOS", "Numbers"), ("M", "Metres"), ("KG", "Kilograms"), ("SET", "Set")], default="NOS", max_length=12)),
                ("attribute_schema", models.JSONField(blank=True, default=dict, help_text="JSON Schema for component.attributes.")),
                ("sku_prefix", models.CharField(max_length=8)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_category",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("sku", models.CharField(max_length=32)),
                ("brand_label", models.CharField(blank=True, default="", help_text="Brand as printed (source spelling); defaults to the brand's name.", max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("attributes", models.JSONField(blank=True, default=dict, help_text="Validated against the category's attribute_schema.")),
                ("gst_rate_override", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("hsn_code_override", models.CharField(blank=True, default="", max_length=12)),
                ("unit_override", models.CharField(blank=True, choices=[("NOS", "Numbers"), ("M", "Metres"), ("KG", "Kilograms"), ("SET", "Set")], default="", max_length=12)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("DEPRECATED", "Deprecated"), ("RETIRED", "Retired")], default="DRAFT", max_length=12)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("deprecated_reason", models.TextField(blank=True, default="")),
                ("retired_reason", models.TextField(blank=True, default="")),
                ("is_public", models.BooleanField(default=False, help_text="Visible on the website (with a published public profile).")),
                ("is_premium", models.BooleanField(default=False)),
                ("warranty_product_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("warranty_performance_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("warranty_extendable_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("warranty_text", models.CharField(blank=True, default="", max_length=64)),
                ("engineering_status", models.CharField(blank=True, default="", help_text="Source engineering note code (e.g. APPROVED_V1_1P_AC_ISOLATOR).", max_length=48)),
                ("notes", models.TextField(blank=True, default="")),
                ("datasheet_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "search",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.CombinedSearchVector(
                                        django.contrib.postgres.search.SearchVector("sku", config="simple", weight="A"),
                                        "||",
                                        django.contrib.postgres.search.SearchVector("name", config="simple", weight="A"),
                                        django.contrib.postgres.search.SearchConfig("simple"),
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector("model", config="simple", weight="A"),
                                    django.contrib.postgres.search.SearchConfig("simple"),
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector("brand_label", config="simple", weight="B"),
                                django.contrib.postgres.search.SearchConfig("simple"),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector("description", config="simple", weight="C"),
                            django.contrib.postgres.search.SearchConfig("simple"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("brand", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="components", to="catalog.brand")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="components", to="catalog.category")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("datasheet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("primary_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("replacement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replaces", to="catalog.component")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_component",
                "ordering": ["sku", "id"],
            },
        ),
        migrations.CreateModel(
            name="BatterySpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("chemistry", models.CharField(blank=True, choices=[("LFP", "Lithium iron phosphate"), ("LEAD_ACID", "Lead acid"), ("NMC", "Lithium NMC")], max_length=16, null=True)),
                ("battery_type", models.CharField(blank=True, default="", max_length=32)),
                ("nominal_voltage_v", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("min_voltage_v", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_voltage_v", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("capacity_kwh", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("usable_kwh", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("backup_hours", models.DecimalField(blank=True, decimal_places=2, help_text="Website calculator backup time (legacy batteries.backup_hour).", max_digits=5, null=True)),
                ("max_c_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("cycle_life", models.PositiveIntegerField(blank=True, null=True)),
                ("dod_pct", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("stackable", models.BooleanField(blank=True, null=True)),
                ("max_units_in_series", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_units_in_parallel", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bms_included", models.BooleanField(blank=True, null=True)),
                ("continuous_charge_current_a", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("continuous_discharge_current_a", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("maximum_charge_current_a", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("maximum_discharge_current_a", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("peak_current_a", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("integrated_protection", models.BooleanField(blank=True, null=True)),
                ("protection_type", models.CharField(blank=True, default="", max_length=32)),
                ("protection_rating", models.CharField(blank=True, default="", max_length=12)),
                ("external_protection_required", models.BooleanField(blank=True, null=True)),
                ("communication_protocol", models.CharField(blank=True, default="", max_length=64)),
                ("communication_required", models.BooleanField(blank=True, null=True)),
                ("compatible_inverters", models.JSONField(blank=True, help_text="Component SKUs; null = unknown.", null=True)),
                ("compatible_system_types", models.JSONField(blank=True, null=True)),
                ("compatible_phases", models.JSONField(blank=True, null=True)),
                ("architecture", models.CharField(blank=True, default="", max_length=24)),
                (
                    "engineering_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PENDING_ENGINEERING_APPROVAL", "Pending engineering approval"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("WITHDRAWN", "Withdrawn")],
                        default="PENDING_ENGINEERING_APPROVAL",
                        max_length=32,
                    ),
                ),
                (
                    "procurement_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive"), ("DISCONTINUED", "Discontinued"), ("PENDING_SOURCING", "Pending sourcing")], default="ACTIVE", max_length=20
                    ),
                ),
                ("engineering_notes", models.TextField(blank=True, default="")),
                ("open_items", models.JSONField(blank=True, default=list)),
                ("status_history", models.JSONField(blank=True, default=list)),
                ("supplier", models.CharField(blank=True, default="", max_length=120)),
                ("supplier_reference", models.CharField(blank=True, default="", max_length=120)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("family", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="batteries", to="catalog.batteryfamily")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("component", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="battery_spec", to="catalog.component")),
            ],
            options={
                "db_table": "catalog_battery_spec",
            },
        ),
        migrations.CreateModel(
            name="ComponentChange",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("field", models.CharField(max_length=64)),
                ("old", models.JSONField(blank=True, null=True)),
                ("new", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="changes", to="catalog.component")),
            ],
            options={
                "db_table": "catalog_component_change",
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ComponentPublicProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.SlugField(max_length=160)),
                ("headline", models.CharField(blank=True, default="", help_text="Card title on the website.", max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="", help_text="Markdown.")),
                ("image_url", models.CharField(blank=True, default="", help_text="Legacy image path or URL; the component's primary image wins.", max_length=500)),
                ("price_range_label", models.CharField(blank=True, default="", help_text="Shown when the current price release has no price for the component.", max_length=100)),
                ("subsidy_eligible", models.BooleanField(blank=True, null=True)),
                ("kerala_climate_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("overall_rating", models.CharField(blank=True, choices=[("EXCELLENT", "Excellent"), ("VERY_GOOD", "Very good"), ("GOOD", "Good")], max_length=12, null=True)),
                ("rating_tier", models.CharField(blank=True, choices=[("PREMIUM", "Premium"), ("MID_RANGE", "Mid-range"), ("VALUE", "Value")], max_length=12, null=True)),
                ("ratings", models.JSONField(blank=True, default=dict, help_text="{efficiency, heat_performance, reliability, warranty, kerala_climate}: 0-100.")),
                ("pros", models.JSONField(blank=True, default=list)),
                ("cons", models.JSONField(blank=True, default=list)),
                ("faq", models.JSONField(blank=True, default=list, help_text="[{question, answer}]")),
                ("gallery", models.JSONField(blank=True, default=list, help_text="Public media asset uids.")),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")], default="DRAFT", max_length=12)),
                ("component", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="public_profile", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_component_public_profile",
                "ordering": ["-kerala_climate_score", "slug", "id"],
            },
        ),
        migrations.CreateModel(
            name="ComponentTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tiers", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_component_tier",
                "ordering": ["component_id", "tier"],
            },
        ),
        migrations.CreateModel(
            name="InverterSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("kw", models.DecimalField(decimal_places=3, help_text="Rated AC output in kW (watts kept exactly).", max_digits=7)),
                ("phase", models.CharField(blank=True, choices=[("1P", "Single phase"), ("3P", "Three phase")], max_length=8, null=True)),
                ("inverter_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid")], max_length=8)),
                ("topology", models.CharField(blank=True, choices=[("STRING", "String"), ("MICRO", "Microinverter"), ("OPTIMIZED_STRING", "Optimised string")], max_length=16, null=True)),
                ("device_type", models.CharField(blank=True, default="", help_text="Flarize deviceType (per-panel allocation).", max_length=24)),
                ("panels_per_device", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("mppt_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("mppt_voltage_min_v", models.PositiveIntegerField(blank=True, null=True)),
                ("mppt_voltage_max_v", models.PositiveIntegerField(blank=True, null=True)),
                ("start_voltage_v", models.PositiveIntegerField(blank=True, null=True)),
                ("max_pv_voltage_v", models.PositiveIntegerField(blank=True, null=True)),
                ("max_input_current_a", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_input_current_text", models.CharField(blank=True, default="", help_text="Display text, e.g. '16 A per MPPT'.", max_length=50)),
                ("max_strings_per_mppt", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_isc_a", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_dc_input_kw", models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ("battery_voltage_v", models.PositiveIntegerField(blank=True, null=True)),
                ("max_charge_current_a", models.PositiveIntegerField(blank=True, null=True)),
                ("efficiency_pct", models.DecimalField(blank=True, decimal_places=2, help_text="Maximum efficiency.", max_digits=5, null=True)),
                ("european_efficiency_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("mppt_efficiency_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("dc_oversizing_pct", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ac_overloading_pct", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weight_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("ip_rating", models.CharField(blank=True, default="", max_length=10)),
                ("display", models.CharField(blank=True, default="", max_length=100)),
                ("suitable_system_size", models.CharField(blank=True, default="", max_length=100)),
                ("pid_protection", models.BooleanField(blank=True, null=True)),
                ("iv_curve_scanning", models.CharField(blank=True, default="", max_length=100)),
                ("corrosion_protection", models.CharField(blank=True, default="", max_length=100)),
                ("operating_temperature", models.CharField(blank=True, default="", max_length=50)),
                ("cooling", models.CharField(blank=True, default="", max_length=100)),
                ("noise_level", models.CharField(blank=True, default="", max_length=50)),
                ("dc_surge_protection", models.CharField(blank=True, default="", max_length=50)),
                ("ac_surge_protection", models.CharField(blank=True, default="", max_length=50)),
                ("arc_fault_detection", models.CharField(blank=True, default="", max_length=50)),
                ("grid_protection", models.BooleanField(blank=True, null=True)),
                ("monitoring_app", models.CharField(blank=True, default="", max_length=100)),
                ("real_time_monitoring", models.BooleanField(blank=True, null=True)),
                ("remote_diagnostics", models.CharField(blank=True, default="", max_length=100)),
                ("firmware_updates", models.CharField(blank=True, default="", max_length=100)),
                ("connectivity", models.CharField(blank=True, default="", max_length=100)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("brand_trust", models.CharField(blank=True, default="", max_length=50)),
                ("year_founded", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("countries_served", models.CharField(blank=True, default="", max_length=50)),
                ("global_installations", models.CharField(blank=True, default="", max_length=50)),
                ("communication", models.JSONField(blank=True, default=list, help_text="Supported protocols/interfaces.")),
                ("compatible_battery_families", models.JSONField(blank=True, default=list, help_text="catalog_battery_family slugs (battery-compatibility engine).")),
                ("system_controller_required", models.BooleanField(blank=True, help_text="PBC-M-003; NULL = not recorded.", null=True)),
                ("component", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="inverter_spec", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_inverter_spec",
            },
        ),
        migrations.CreateModel(
            name="PanelSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("wattage_w", models.PositiveIntegerField()),
                (
                    "panel_type",
                    models.CharField(blank=True, choices=[("MONOCRYSTALLINE", "Monocrystalline"), ("POLYCRYSTALLINE", "Polycrystalline"), ("BIFACIAL", "Bifacial")], max_length=24, null=True),
                ),
                ("technology", models.CharField(blank=True, choices=[("N_TYPE_TOPCON", "N-Type TOPCon"), ("P_TYPE_PERC", "P-Type PERC"), ("HJT", "HJT"), ("IBC", "IBC")], max_length=24, null=True)),
                ("cell_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("efficiency_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("temperature_coefficient", models.DecimalField(blank=True, decimal_places=3, help_text="Pmax %/°C.", max_digits=5, null=True)),
                ("temperature_coefficient_voc", models.DecimalField(blank=True, decimal_places=3, help_text="Voc %/°C.", max_digits=5, null=True)),
                ("noct_c", models.SmallIntegerField(blank=True, null=True)),
                ("real_output_at_60c_pct", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("voc_v", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("vmp_v", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("isc_a", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("imp_a", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_system_voltage_v", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_rating", models.CharField(blank=True, default="", max_length=10)),
                ("wind_load_pa", models.PositiveIntegerField(blank=True, null=True)),
                ("snow_load_pa", models.PositiveIntegerField(blank=True, null=True)),
                ("moisture_protection", models.CharField(blank=True, default="", max_length=50)),
                ("weight_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("dimensions_mm", models.CharField(blank=True, default="", max_length=32)),
                ("bifacial_gain_pct", models.SmallIntegerField(blank=True, null=True)),
                ("first_year_drop_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("annual_degradation_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("output_at_year_25_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("is_dcr", models.BooleanField(blank=True, help_text="Domestic Content Requirement (subsidy) module.", null=True)),
                ("bis_certified", models.BooleanField(blank=True, null=True)),
                ("bloomberg_tier1", models.BooleanField(blank=True, null=True)),
                ("pvel_top_performer", models.BooleanField(blank=True, null=True)),
                ("independent_audit", models.BooleanField(blank=True, null=True)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("manufacturing_capacity", models.CharField(blank=True, default="", max_length=50)),
                ("component", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="panel_spec", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_panel_spec",
            },
        ),
        migrations.CreateModel(
            name="StructureSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "structure_type",
                    models.CharField(blank=True, choices=[("FLAT_ROOF", "Flat roof"), ("ELEVATED", "Elevated"), ("SHEET_ROOF", "Sheet roof"), ("GROUND", "Ground mount")], max_length=16, null=True),
                ),
                ("material", models.CharField(blank=True, choices=[("GP", "Galvanised plain (GP)"), ("GI", "Galvanised iron (GI)"), ("AL", "Aluminium")], max_length=8, null=True)),
                ("tube_size", models.CharField(blank=True, default="", max_length=12)),
                ("weight_kg_per_m", models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ("structure_role", models.CharField(blank=True, default="", help_text="Flarize structureRole (e.g. PRIMARY_TUBE).", max_length=24)),
                ("specification", models.CharField(blank=True, default="", max_length=255)),
                ("component", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="structure_spec", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "catalog_structure_spec",
            },
        ),
        migrations.AddConstraint(
            model_name="batteryfamily",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="catalog_battery_family_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="batteryfamily",
            constraint=models.CheckConstraint(condition=models.Q(("voltage_class__in", ["48V", "HV"])), name="catalog_battery_family_voltage_class_valid"),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True)), name="catalog_brand_name_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="catalog_brand_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="catalog_brand_name_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="catalog_category_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("sku_prefix"), condition=models.Q(("deleted_at__isnull", True)), name="catalog_category_sku_prefix_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("bom_role__in", ["MAIN_PANEL", "MAIN_INVERTER", "BATTERY", "PROTECTION", "CABLE", "EARTHING", "STRUCTURE", "SERVICE", "MISC"])),
                name="catalog_category_bom_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(condition=models.Q(("unit__in", ["NOS", "M", "KG", "SET"])), name="catalog_category_unit_valid"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(condition=models.Q(("gst_rate__gte", 0), ("gst_rate__lte", 1)), name="catalog_category_gst_rate_fraction"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(condition=models.Q(("sku_prefix__regex", "^[A-Z][A-Z0-9]{1,7}$")), name="catalog_category_sku_prefix_format"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["category", "status"], name="catalog_comp_category_status"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search"], name="catalog_comp_search_gin"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=django.contrib.postgres.indexes.GinIndex(fields=["attributes"], name="catalog_comp_attributes_gin"),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("sku"), condition=models.Q(("deleted_at__isnull", True)), name="catalog_component_sku_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(condition=models.Q(("sku__regex", "^[A-Za-z0-9][A-Za-z0-9_.-]{0,31}$")), name="catalog_component_sku_format"),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "ACTIVE", "DEPRECATED", "RETIRED"])), name="catalog_component_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_override", ""), ("unit_override__in", ["NOS", "M", "KG", "SET"]), _connector="OR"), name="catalog_component_unit_override_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(
                condition=models.Q(("gst_rate_override__isnull", True), models.Q(("gst_rate_override__gte", 0), ("gst_rate_override__lte", 1)), _connector="OR"),
                name="catalog_component_gst_override_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(
                condition=models.Q(("replacement__isnull", True), models.Q(("replacement", models.F("id")), _negated=True), _connector="OR"), name="catalog_component_not_own_replacement"
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="catalog_component_name_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="batteryspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("chemistry__isnull", True), ("chemistry__in", ["LFP", "LEAD_ACID", "NMC"]), _connector="OR"), name="catalog_battery_spec_chemistry_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="batteryspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("engineering_status__in", ["DRAFT", "PENDING_ENGINEERING_APPROVAL", "APPROVED", "REJECTED", "WITHDRAWN"])), name="catalog_battery_spec_engineering_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="batteryspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("procurement_status__in", ["ACTIVE", "INACTIVE", "DISCONTINUED", "PENDING_SOURCING"])), name="catalog_battery_spec_procurement_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="batteryspec",
            constraint=models.CheckConstraint(condition=models.Q(("dod_pct__isnull", True), ("dod_pct__lte", 100), _connector="OR"), name="catalog_battery_spec_dod_pct"),
        ),
        migrations.AddIndex(
            model_name="componentchange",
            index=models.Index(fields=["component", "-at"], name="catalog_comp_change_comp_at"),
        ),
        migrations.AddIndex(
            model_name="componentpublicprofile",
            index=models.Index(fields=["status", "-kerala_climate_score"], name="catalog_profile_status_score"),
        ),
        migrations.AddConstraint(
            model_name="componentpublicprofile",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="catalog_profile_slug_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="componentpublicprofile",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "PUBLISHED"])), name="catalog_profile_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="componentpublicprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("overall_rating__isnull", True), ("overall_rating__in", ["EXCELLENT", "VERY_GOOD", "GOOD"]), _connector="OR"), name="catalog_profile_overall_rating_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentpublicprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating_tier__isnull", True), ("rating_tier__in", ["PREMIUM", "MID_RANGE", "VALUE"]), _connector="OR"), name="catalog_profile_rating_tier_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentpublicprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("kerala_climate_score__isnull", True), ("kerala_climate_score__lte", 100), _connector="OR"), name="catalog_profile_kerala_score_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentpublicprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "PUBLISHED"), _negated=True), ("published_at__isnull", False), _connector="OR"), name="catalog_profile_published_has_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="componenttier",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("component", "tier"), name="catalog_component_tier_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="componenttier",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="catalog_component_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="inverterspec",
            constraint=models.CheckConstraint(condition=models.Q(("kw__gt", 0)), name="catalog_inverter_spec_kw_positive"),
        ),
        migrations.AddConstraint(
            model_name="inverterspec",
            constraint=models.CheckConstraint(condition=models.Q(("phase__isnull", True), ("phase__in", ["1P", "3P"]), _connector="OR"), name="catalog_inverter_spec_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="inverterspec",
            constraint=models.CheckConstraint(condition=models.Q(("inverter_type__in", ["ONGRID", "HYBRID"])), name="catalog_inverter_spec_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="inverterspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("topology__isnull", True), ("topology__in", ["STRING", "MICRO", "OPTIMIZED_STRING"]), _connector="OR"), name="catalog_inverter_spec_topology_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="panelspec",
            constraint=models.CheckConstraint(condition=models.Q(("wattage_w__gt", 0)), name="catalog_panel_spec_wattage_positive"),
        ),
        migrations.AddConstraint(
            model_name="panelspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("panel_type__isnull", True), ("panel_type__in", ["MONOCRYSTALLINE", "POLYCRYSTALLINE", "BIFACIAL"]), _connector="OR"), name="catalog_panel_spec_panel_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="panelspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("technology__isnull", True), ("technology__in", ["N_TYPE_TOPCON", "P_TYPE_PERC", "HJT", "IBC"]), _connector="OR"), name="catalog_panel_spec_technology_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="panelspec",
            constraint=models.CheckConstraint(
                condition=models.Q(("efficiency_pct__isnull", True), models.Q(("efficiency_pct__gte", 0), ("efficiency_pct__lte", 100)), _connector="OR"), name="catalog_panel_spec_efficiency_pct"
            ),
        ),
        migrations.AddConstraint(
            model_name="structurespec",
            constraint=models.CheckConstraint(
                condition=models.Q(("structure_type__isnull", True), ("structure_type__in", ["FLAT_ROOF", "ELEVATED", "SHEET_ROOF", "GROUND"]), _connector="OR"),
                name="catalog_structure_spec_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="structurespec",
            constraint=models.CheckConstraint(condition=models.Q(("material__isnull", True), ("material__in", ["GP", "GI", "AL"]), _connector="OR"), name="catalog_structure_spec_material_valid"),
        ),
    ]
