# Generated by Django 6.0.8 on 2026-09-28 19:31

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import flarize.crypto
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("label", models.CharField(max_length=80)),
                ("bank", models.CharField(max_length=120)),
                ("account_name", models.CharField(max_length=160)),
                ("account_number", flarize.crypto.EncryptedTextField()),
                ("ifsc", models.CharField(max_length=11)),
                ("branch", models.CharField(blank=True, default="", max_length=160)),
                ("upi_id", models.CharField(blank=True, default="", max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "company_bank_account",
                "ordering": ["-is_primary", "label", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("is_primary", True)), fields=("is_primary",), name="company_bank_account_one_primary"),
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("label",), name="company_bank_account_label_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("ifsc__regex", "^[A-Z]{4}0[A-Z0-9]{6}$")), name="company_bank_account_ifsc_format"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("legal_name", models.CharField(blank=True, default="", max_length=200)),
                ("trade_name", models.CharField(blank=True, default="", max_length=160)),
                ("gstin", models.CharField(blank=True, default="", max_length=15)),
                ("pan", models.CharField(blank=True, default="", max_length=10)),
                ("cin", models.CharField(blank=True, default="", max_length=21)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone_e164", models.CharField(blank=True, default="", max_length=16)),
                ("website", models.URLField(blank=True, default="")),
                ("address_line", models.CharField(blank=True, default="", max_length=255)),
                ("address_locality", models.CharField(blank=True, default="", max_length=120)),
                ("address_region", models.CharField(blank=True, default="", max_length=120)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("country_code", models.CharField(default="IN", max_length=2)),
                ("trust_stats", models.JSONField(blank=True, default=list)),
                ("social", models.JSONField(blank=True, default=dict)),
                ("default_meta_description", models.TextField(blank=True, default="")),
                ("lead_notification_emails", django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list)),
                ("application_notification_emails", django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list)),
                ("notify_on_new_lead", models.BooleanField(default=True)),
                ("notify_on_new_application", models.BooleanField(default=True)),
                ("careers_accepting_general_applications", models.BooleanField(default=True)),
                ("careers_intro", models.TextField(blank=True, default="")),
                ("blog_revalidate_url", models.URLField(blank=True, default="", max_length=500)),
                ("blog_revalidate_secret", flarize.crypto.EncryptedTextField(blank=True, null=True)),
                ("quotation_offer_enabled", models.BooleanField(default=True)),
                ("quotation_offer_title", models.CharField(blank=True, default="Priority 10-Day Installation", max_length=150)),
                ("quotation_offer_description", models.CharField(blank=True, default="Fast-tracked scheduling and execution", max_length=300)),
                ("quotation_offer_details", models.CharField(blank=True, default="", max_length=300)),
                ("quotation_offer_title_ml", models.CharField(blank=True, default="10 ദിവസത്തിനുള്ളിൽ മുൻഗണനാ ഇൻസ്റ്റലേഷൻ", max_length=150)),
                ("quotation_offer_description_ml", models.CharField(blank=True, default="വേഗത്തിലുള്ള ഷെഡ്യൂളിംഗും ഇൻസ്റ്റലേഷനും", max_length=300)),
                ("quotation_offer_details_ml", models.CharField(blank=True, default="", max_length=300)),
                ("quotation_offer_valid_from", models.DateField(blank=True, null=True)),
                ("quotation_offer_valid_until", models.DateField(blank=True, null=True)),
                ("quotation_offer_image_url", models.URLField(blank=True, default="https://golden-ray.b-cdn.net/icons/37.png", max_length=500)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                (
                    "default_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Public image used when a page has no Open Graph image (SiteSettings.default_og_image).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
                ("letterhead", models.ForeignKey(blank=True, help_text="Document letterhead image.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True, help_text="Public image: website header and documents.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset"
                    ),
                ),
                (
                    "quotation_offer_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Public offer banner image (wins over quotation_offer_image_url).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "seal",
                    models.ForeignKey(blank=True, help_text="Company seal printed on documents.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset"),
                ),
                (
                    "signature",
                    models.ForeignKey(
                        blank=True, help_text="Authorised signatory's signature (private).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset"
                    ),
                ),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                (
                    "upi_qr",
                    models.ForeignKey(blank=True, help_text="UPI QR code printed on documents.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset"),
                ),
            ],
            options={
                "db_table": "company_profile",
                "constraints": [
                    models.UniqueConstraint(models.Value(1), condition=models.Q(("deleted_at__isnull", True)), name="company_profile_singleton"),
                    models.CheckConstraint(condition=models.Q(("country_code__regex", "^[A-Z]{2}$")), name="company_profile_country_code_iso"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quotation_offer_valid_from__isnull", True),
                            ("quotation_offer_valid_until__isnull", True),
                            ("quotation_offer_valid_until__gte", models.F("quotation_offer_valid_from")),
                            _connector="OR",
                        ),
                        name="company_profile_offer_dates_ordered",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(choices=[("TWILIO", "Twilio Verify"), ("BUNNY", "Bunny storage / CDN"), ("SMTP", "SMTP e-mail")], max_length=16)),
                ("config", flarize.crypto.EncryptedJSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "company_integration",
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("key",), name="company_integration_key_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("key__in", ["TWILIO", "BUNNY", "SMTP"])), name="company_integration_key_valid"),
                ],
            },
        ),
    ]
