# Generated by Django 6.0.8 on 2026-09-29 06:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("slug", models.CharField(help_text="flat_roof, elevated, sheet_roof …", max_length=32)),
                ("name", models.CharField(max_length=100)),
                ("labour_rate_key", models.CharField(blank=True, default="", help_text="pricing_cost_config key of the roof type's rate (e.g. elevated_structure_rate).", max_length=48)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "bom_structure_template",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StructureTemplateItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("item_type", models.CharField(choices=[("TUBE", "Tube (priced by weight)"), ("FIXED", "Fixed item (priced per unit)")], max_length=8)),
                ("tube_size", models.CharField(blank=True, default="", max_length=12)),
                ("weight_kg", models.DecimalField(blank=True, decimal_places=4, help_text="TUBE: weight of one tube length in kg.", max_digits=8, null=True)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, help_text="FIXED: price per unit.", max_digits=14, null=True)),
                ("unit", models.CharField(blank=True, default="", max_length=12)),
                ("length_m_per_kw", models.DecimalField(blank=True, decimal_places=3, help_text="Tube metres per kW (PLAN; not used by the legacy sources).", max_digits=8, null=True)),
                ("qty_rule", models.JSONField(help_text="Quantity rule document (bom.schemas.QTY_RULE_SCHEMA), usually kw_interpolated.")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="bom.structuretemplate")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "bom_structure_template_item",
                "ordering": ["template_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("system_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid"), ("UPGRADE", "Upgrade")], max_length=8)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("sizes", models.JSONField(blank=True, default=list, help_text='Offered sizes in display order: [{"key": "5sp", "label": "5kW 1P"}, …].')),
                ("three_phase_sizes", models.JSONField(blank=True, default=list, help_text="Size keys that are three-phase systems.")),
                ("tiers", models.JSONField(blank=True, default=list, help_text="Offered tiers (lower case, source order).")),
                ("battery_configs", models.JSONField(blank=True, default=list, help_text="Hybrid battery bands offered ('0', '1', '2').")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "bom_template",
                "ordering": ["system_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="Slot key (the category slug for imported templates: panel, inverter, dcdb …).", max_length=32)),
                ("qty_rule", models.JSONField(help_text="Quantity rule document (bom.schemas.QTY_RULE_SCHEMA).")),
                ("required", models.BooleanField(default=True, help_text="bom/build/ warns when a required slot needs a component and none is eligible.")),
                ("sort_order", models.IntegerField(default=0, help_text="Line position (legacy BomSlot.pos).")),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("gst_rate", models.DecimalField(blank=True, decimal_places=4, help_text="GST fraction for the line; null = the category's rate.", max_digits=5, null=True)),
                ("is_variable", models.BooleanField(default=True)),
                ("filter_type", models.CharField(blank=True, choices=[("", "Any"), ("ONGRID", "On-grid only (or untyped)"), ("HYBRID", "Hybrid only")], default="", max_length=8)),
                ("filter_phase", models.CharField(blank=True, choices=[("", "Phase of the system"), ("HYB", "Hybrid phase codes only")], default="", max_length=8)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bom_slots", to="catalog.category")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="bom.template")),
            ],
            options={
                "db_table": "bom_slot",
                "ordering": ["template_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FixedItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(blank=True, default="", help_text="Source identifier (Flarize fixed item id, e.g. fi_mc4_connector).", max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=2, help_text="Reference price of a template consumable; null = the component's current LIST price.", max_digits=14, null=True),
                ),
                ("gst_rate", models.DecimalField(blank=True, decimal_places=4, help_text="GST fraction; null = the category's rate (18 % without one).", max_digits=5, null=True)),
                ("qty", models.DecimalField(blank=True, decimal_places=3, help_text="Constant quantity (when there is no qty_rule).", max_digits=12, null=True)),
                ("qty_rule", models.JSONField(blank=True, help_text="Quantity rule document (bom.schemas.QTY_RULE_SCHEMA); wins over qty.", null=True)),
                ("condition", models.JSONField(blank=True, default=dict, help_text="When the item applies (bom.schemas.CONDITION_SCHEMA); {} = always.")),
                ("section", models.CharField(blank=True, default="", help_text="Quote section / upgrade section (battery, hybridInv …).", max_length=32)),
                ("unit", models.CharField(blank=True, default="", max_length=12)),
                ("is_tube", models.BooleanField(default=False, help_text="Priced through the structure cost, never as a BOM line.")),
                ("sort_order", models.IntegerField(default=0)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bom_fixed_items", to="catalog.category")),
                ("component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bom_fixed_items", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fixed_items", to="bom.template")),
            ],
            options={
                "db_table": "bom_fixed_item",
                "ordering": ["template_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TubeWeight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("tube_size", models.CharField(max_length=12)),
                ("weight_kg", models.DecimalField(decimal_places=4, help_text="Weight of one tube length in kg.", max_digits=8)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "bom_tube_weight",
                "ordering": ["tube_size", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackageProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(help_text="Flarize packageKey (ongrid_base, hybrid_value, premium …).", max_length=32)),
                ("label", models.CharField(max_length=100)),
                ("structure_material", models.CharField(choices=[("GP", "GP (galvanised plain)"), ("GI", "GI (galvanised iron)"), ("AL", "Aluminium")], max_length=4)),
                ("inverter_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid"), ("MICRO", "Micro-inverter")], max_length=8)),
                ("battery_included", models.BooleanField(default=False)),
                ("battery_brand", models.CharField(blank=True, default="", max_length=100)),
                ("battery_model", models.CharField(blank=True, default="", max_length=100)),
                ("battery_capacity_kwh", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("battery_quantity", models.PositiveSmallIntegerField(default=0)),
                ("structure_labor_override", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("repair_margin_override", models.DecimalField(blank=True, decimal_places=4, help_text="Fraction (0.1 = 10 %).", max_digits=7, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("battery_component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bom_package_profiles", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "bom_package_profile",
                "ordering": ["key", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("key",), name="bom_package_profile_key_uniq"),
                    models.CheckConstraint(condition=models.Q(("key__regex", "^[a-z0-9][a-z0-9_]*$")), name="bom_package_profile_key_format"),
                    models.CheckConstraint(condition=models.Q(("structure_material__in", ["GP", "GI", "AL"])), name="bom_package_profile_material_valid"),
                    models.CheckConstraint(condition=models.Q(("inverter_type__in", ["ONGRID", "HYBRID", "MICRO"])), name="bom_package_profile_inverter_valid"),
                    models.CheckConstraint(condition=models.Q(("battery_capacity_kwh__gte", 0)), name="bom_package_profile_capacity_not_negative"),
                    models.CheckConstraint(condition=models.Q(("battery_quantity__lte", 2)), name="bom_package_profile_battery_quantity_band"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="structuretemplate",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="bom_structure_template_slug_uniq"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplate",
            constraint=models.CheckConstraint(condition=models.Q(("slug__regex", "^[a-z0-9][a-z0-9_]*$")), name="bom_structure_template_slug_format"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplate",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="bom_structure_template_name_not_blank"),
        ),
        migrations.AddIndex(
            model_name="structuretemplateitem",
            index=models.Index(fields=["template", "sort_order"], name="bom_structure_item_order"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplateitem",
            constraint=models.CheckConstraint(condition=models.Q(("item_type__in", ["TUBE", "FIXED"])), name="bom_structure_item_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplateitem",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="bom_structure_item_name_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplateitem",
            constraint=models.CheckConstraint(condition=models.Q(("weight_kg__isnull", True), ("weight_kg__gte", 0), _connector="OR"), name="bom_structure_item_weight_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplateitem",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__isnull", True), ("unit_price__gte", 0), _connector="OR"), name="bom_structure_item_price_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="structuretemplateitem",
            constraint=models.CheckConstraint(condition=models.Q(("length_m_per_kw__isnull", True), ("length_m_per_kw__gte", 0), _connector="OR"), name="bom_structure_item_length_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("system_type",), name="bom_template_system_type_uniq"),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID", "UPGRADE"])), name="bom_template_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="bom_template_name_not_blank"),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(fields=["template", "sort_order"], name="bom_slot_template_order"),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("template", "key"), name="bom_slot_template_key_uniq"),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[a-z0-9][a-z0-9_]*$")), name="bom_slot_key_format"),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(condition=models.Q(("filter_type__in", ["", "ONGRID", "HYBRID"])), name="bom_slot_filter_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(condition=models.Q(("filter_phase__in", ["", "HYB"])), name="bom_slot_filter_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(condition=models.Q(("gst_rate__isnull", True), models.Q(("gst_rate__gte", 0), ("gst_rate__lte", 1)), _connector="OR"), name="bom_slot_gst_rate_fraction"),
        ),
        migrations.AddIndex(
            model_name="fixeditem",
            index=models.Index(fields=["template", "sort_order"], name="bom_fixed_item_template_order"),
        ),
        migrations.AddConstraint(
            model_name="fixeditem",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="bom_fixed_item_name_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="fixeditem",
            constraint=models.CheckConstraint(condition=models.Q(("qty__isnull", False), ("qty_rule__isnull", False), _connector="OR"), name="bom_fixed_item_has_quantity"),
        ),
        migrations.AddConstraint(
            model_name="fixeditem",
            constraint=models.CheckConstraint(condition=models.Q(("qty__isnull", True), ("qty__gte", 0), _connector="OR"), name="bom_fixed_item_qty_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="fixeditem",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__isnull", True), ("unit_price__gte", 0), _connector="OR"), name="bom_fixed_item_price_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="fixeditem",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__isnull", False), ("component__isnull", False), _connector="OR"), name="bom_fixed_item_priced"),
        ),
        migrations.AddConstraint(
            model_name="fixeditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("gst_rate__isnull", True), models.Q(("gst_rate__gte", 0), ("gst_rate__lte", 1)), _connector="OR"), name="bom_fixed_item_gst_rate_fraction"
            ),
        ),
        migrations.AddConstraint(
            model_name="tubeweight",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("tube_size",), name="bom_tube_weight_size_uniq"),
        ),
        migrations.AddConstraint(
            model_name="tubeweight",
            constraint=models.CheckConstraint(condition=models.Q(("tube_size", ""), _negated=True), name="bom_tube_weight_size_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="tubeweight",
            constraint=models.CheckConstraint(condition=models.Q(("weight_kg__gt", 0)), name="bom_tube_weight_positive"),
        ),
    ]
