"""Configuration (the agent.ini Studio downloads), identity helpers and the durable queue (incl. the eSSL upgrade)."""

import sqlite3
from datetime import datetime, timedelta, timezone

import pytest
from essl_agent.config import AgentConfig, ConfigError
from essl_agent.identity import display_mac, macs_match, normalize_mac, serials_match
from essl_agent.store import Store

PLATFORM_INI = """# Flarize office agent configuration — generated by the platform.
[agent]
server_url = https://api.flarize.test/
api_version = v1
token = fl_ab12cd34_secret
agent_code = OFFICE-001-AGENT
queue_path = agent_queue.sqlite3
heartbeat_interval = 90
sync_interval = 120
upload_batch_size = 200
verify_tls = true

[device:1]
name = MARS-01
ip = 192.168.1.209
expected_serial = NCD8253601138
expected_mac = 00:17:61:12:9c:49
force_udp = true
"""


class TestConfig:
    def test_the_platform_rendered_file(self, tmp_path):
        path = tmp_path / "agent.ini"
        path.write_text(PLATFORM_INI, encoding="utf-8")
        cfg = AgentConfig.load(path)
        assert cfg.api_base == "https://api.flarize.test/api/agent/v1" and cfg.heartbeat_interval == 90 and cfg.sync_interval == 120
        assert (cfg.announce_interval, cfg.users_refresh_hours, cfg.sent_retention_days) == (3600, 24, 7)
        [device] = cfg.devices
        assert (device.name, device.expected_serial, device.force_udp, device.port) == ("MARS-01", "NCD8253601138", True, 4370)

    def test_environment_overrides_and_limits(self, tmp_path, monkeypatch):
        path = tmp_path / "agent.ini"
        path.write_text(PLATFORM_INI, encoding="utf-8")
        monkeypatch.setenv("ESSL_AGENT_UPLOAD_BATCH_SIZE", "5000")
        monkeypatch.setenv("ESSL_AGENT_HEARTBEAT_INTERVAL", "1")
        cfg = AgentConfig.load(path)
        assert cfg.upload_batch_size == 200 and cfg.heartbeat_interval == 10
        monkeypatch.setenv("ESSL_AGENT_SYNC_INTERVAL", "often")
        with pytest.raises(ConfigError):
            AgentConfig.load(path)

    def test_missing_or_essl_credentials_are_refused(self, tmp_path, monkeypatch):
        with pytest.raises(ConfigError, match="server_url and token"):
            AgentConfig.load(tmp_path / "missing.ini")
        monkeypatch.setenv("ESSL_AGENT_SERVER_URL", "https://api.flarize.test")
        monkeypatch.setenv("ESSL_AGENT_TOKEN", "essl_3_oldsecret")
        with pytest.raises(ConfigError, match="not a Flarize agent credential"):
            AgentConfig.load(tmp_path / "missing.ini")


def test_identity_helpers():
    assert normalize_mac("00-17-61-12-9C-49") == "001761129c49" and normalize_mac("zz") is None and display_mac("001761129C49") == "00:17:61:12:9c:49"
    assert macs_match("00:17:61:12:9c:49", "001761129C49") is True and macs_match(None, "001761129c49") is None and macs_match("00:17:61:12:9c:49", "00:17:61:12:9c:48") is False
    assert serials_match(" NCD1 ", "NCD1") is True and serials_match("", "NCD1") is None and serials_match("NCD1", "NCD2") is False


class TestStore:
    def test_queue_dedups_and_retires_only_confirmed_rows(self, tmp_path):
        store = Store(tmp_path / "q.sqlite3")
        record = {"device_record_uid": 1, "pin": 7, "device_time": datetime(2026, 9, 22, 9, 31, 5), "status": 15, "punch": 0}
        assert store.enqueue_many("NCD1", [record, record]) == 1 and store.enqueue_many("NCD1", [record]) == 0
        [row] = store.pending()
        assert (row["pin"], row["device_time"]) == ("7", "2026-09-22T09:31:05")
        store.mark_failed([row["id"]], "HTTP 503")
        assert store.failed_count() == 1 and store.pending_count("NCD1") == 1 and store.pending_count("OTHER") == 0
        store.mark_sent([row["id"]])
        assert store.pending_count() == 0 and store.stats()["queue_sent"] == 1
        assert store.purge_sent(7) == 0  # delivered just now: kept for troubleshooting
        assert store.purge_sent(7, now=datetime.now(timezone.utc) + timedelta(days=8)) == 1
        store.close()

    def test_sync_state_meta_blocks_and_events(self, tmp_path):
        store = Store(tmp_path / "q.sqlite3")
        store.set_sync_state("NCD1", last_record_uid=5, users_hash="abc")
        store.set_sync_state("NCD1", last_device_time="2026-09-22T09:00:00")
        assert store.get_sync_state("NCD1")["last_record_uid"] == 5 and store.get_sync_state("NCD1")["users_hash"] == "abc" and store.get_sync_state("X") == {}
        with pytest.raises(ValueError):
            store.set_sync_state("NCD1", bogus=1)
        store.set_identity_block("192.168.1.209:4370", "IDENTITY_MISMATCH …")
        assert store.identity_block("192.168.1.209:4370")["message"].startswith("IDENTITY_MISMATCH") and store.stats()["identity_blocks"] == 1
        store.clear_identity_block("192.168.1.209:4370")
        assert store.identity_block("192.168.1.209:4370") is None
        store.upsert_device("NCD1", uid="u1", last_error="x")
        store.clear_device_error("NCD1")
        assert store.get_device("NCD1")["uid"] == "u1" and store.get_device("NCD1")["last_error"] is None
        store.log("INFO", "hello")
        assert store.recent_events(1)[0]["message"] == "hello"
        store.close()

    def test_an_essl_queue_file_is_upgraded_without_losing_a_punch(self, tmp_path):
        path = tmp_path / "queue-office1.sqlite3"
        legacy = sqlite3.connect(path)
        legacy.executescript("""
            CREATE TABLE devices (serial TEXT PRIMARY KEY, central_id INTEGER, name TEXT, ip TEXT, port INTEGER, firmware TEXT, platform TEXT, last_seen_at TEXT, last_error TEXT);
            CREATE TABLE queue (id INTEGER PRIMARY KEY AUTOINCREMENT, device_serial TEXT NOT NULL, device_record_uid INTEGER, device_user_id TEXT NOT NULL,
                punch_time TEXT NOT NULL, status INTEGER, punch INTEGER, raw_payload TEXT NOT NULL DEFAULT '{}', enqueued_at TEXT NOT NULL,
                attempts INTEGER NOT NULL DEFAULT 0, last_attempt_at TEXT, last_error TEXT, sent_at TEXT);
            CREATE UNIQUE INDEX ux_queue_identity ON queue (device_serial, device_record_uid, device_user_id, punch_time);
            CREATE TABLE sync_state (device_serial TEXT PRIMARY KEY, last_record_uid INTEGER, last_sync_at TEXT, last_upload_at TEXT);
            INSERT INTO devices(serial, central_id) VALUES ('NCD1', 1);
            INSERT INTO queue(device_serial, device_record_uid, device_user_id, punch_time, enqueued_at) VALUES ('NCD1', 41, '7', '2026-09-22T09:31:05', '2026-09-22T09:32:00');
            INSERT INTO sync_state(device_serial, last_record_uid) VALUES ('NCD1', 41);
            """)
        legacy.commit()
        legacy.close()
        store = Store(path)
        [row] = store.pending()
        assert (row["pin"], row["device_time"], row["device_record_uid"]) == ("7", "2026-09-22T09:31:05", 41)
        assert store.enqueue_many("NCD1", [{"device_record_uid": 41, "pin": "7", "device_time": "2026-09-22T09:31:05"}]) == 0  # identity index kept
        assert store.get_sync_state("NCD1")["last_record_uid"] == 41 and store.get_device("NCD1")["uid"] is None
        store.close()
        Store(path).close()  # opening an upgraded file again changes nothing
