# Generated by Django 6.0.8 on 2026-09-28 21:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("sitepages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True, help_text="inactive categories stay on their FAQs but are not offered")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "FAQ categories",
                "db_table": "faqs_category",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("seo_title", models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ("meta_description", models.TextField(blank=True, help_text="70–160 characters reads best in results")),
                ("canonical_url", models.URLField(blank=True, help_text="only when this URL duplicates another", max_length=1000)),
                ("og_title", models.CharField(blank=True, help_text="social share title; falls back to the SEO title", max_length=255)),
                ("og_description", models.TextField(blank=True, help_text="social share description; falls back to the meta description")),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("none", "No structured data"),
                            ("WebPage", "Web page"),
                            ("Article", "Article"),
                            ("FAQPage", "FAQ page"),
                            ("JobPosting", "Job posting"),
                            ("Organization", "Organization"),
                            ("BreadcrumbList", "Breadcrumb list"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("schema_extra", models.JSONField(blank=True, default=dict, help_text="only the structured fields the generator cannot infer from the record")),
                ("noindex", models.BooleanField(default=False, help_text="ask search engines not to index this URL")),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField(blank=True, default="", help_text="plain text or light HTML; the FAQPage schema carries it as is")),
                ("section", models.CharField(blank=True, default="", help_text="block within the page when it carries several FAQ lists", max_length=80)),
                ("sort_order", models.IntegerField(default=0, help_text="order within the page/section (legacy display_order)")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, help_text="first publication; never cleared", null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, help_text="content reviewed; cleared by every content change", null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("og_image", models.ForeignKey(blank=True, help_text="social share image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="faqs", to="sitepages.page")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="faqs", to="faqs.faqcategory")),
            ],
            options={
                "db_table": "faqs_faq",
                "ordering": ["page_id", "section", "sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="faqcategory",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="faqs_category_name_uniq"),
        ),
        migrations.AddConstraint(
            model_name="faqcategory",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="faqs_category_slug_uniq"),
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(fields=["page", "section", "sort_order"], name="faqs_faq_page_section_sort"),
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(fields=["status", "updated_at"], name="faqs_faq_status_updated"),
        ),
        migrations.AddConstraint(
            model_name="faq",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "ARCHIVED"])), name="faqs_faq_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="faq",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_type__in", ["none", "WebPage", "Article", "FAQPage", "JobPosting", "Organization", "BreadcrumbList"])), name="faqs_faq_schema_type_valid"
            ),
        ),
    ]
