# Generated by Django 6.0.8 on 2026-09-29 03:23

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("name", models.CharField(max_length=160)),
                ("abbr", models.CharField(help_text='Logo initials, e.g. "SBI".', max_length=12)),
                ("slug", models.SlugField(max_length=64)),
                ("logo_bg", models.CharField(default="#074A4D", help_text="Hex colour behind the logo initials.", max_length=9)),
                ("annual_rate", models.DecimalField(decimal_places=4, help_text="Headline annual rate as a fraction (0.0565 = 5.65 %), used for sorting and display.", max_digits=6)),
                ("min_loan", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("max_loan", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="0 = no published maximum.", max_digits=14)),
                ("upfront_requirement", models.CharField(blank=True, default="", max_length=160)),
                ("eligibility", models.CharField(blank=True, default="", max_length=255)),
                ("cibil_required", models.PositiveSmallIntegerField(default=0, help_text="0 = no published minimum.")),
                ("processing_fee_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), help_text="Processing fee as a fraction of the loan.", max_digits=6)),
                ("processing_fee_note", models.CharField(blank=True, default="", help_text='Shown instead of the percentage when set, e.g. "₹500 flat".', max_length=120)),
                ("approval_min_days", models.PositiveSmallIntegerField(default=0)),
                ("approval_max_days", models.PositiveSmallIntegerField(default=0)),
                ("max_tenure_years", models.PositiveSmallIntegerField(default=0)),
                ("features", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Bullet points shown on the bank's card.")),
                ("best_for", models.CharField(blank=True, default="", max_length=255)),
                ("is_recommended", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "emi_bank",
                "ordering": ["sort_order", "annual_rate", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("slug",), name="emi_bank_slug_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("slug__regex", "^[a-z0-9]+(?:-[a-z0-9]+)*$")), name="emi_bank_slug_format"),
                    models.CheckConstraint(condition=models.Q(("logo_bg__regex", "^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$")), name="emi_bank_logo_bg_hex"),
                    models.CheckConstraint(
                        condition=models.Q(("annual_rate__gte", 0), ("annual_rate__lt", 1), ("processing_fee_pct__gte", 0), ("processing_fee_pct__lt", 1)), name="emi_bank_rates_fraction"
                    ),
                    models.CheckConstraint(condition=models.Q(("min_loan__gte", 0), ("max_loan__gte", 0)), name="emi_bank_loans_non_negative"),
                    models.CheckConstraint(condition=models.Q(("max_loan", 0), ("min_loan__lte", models.F("max_loan")), _connector="OR"), name="emi_bank_loan_band_ordered"),
                    models.CheckConstraint(
                        condition=models.Q(("approval_max_days", 0), ("approval_min_days__lte", models.F("approval_max_days")), _connector="OR"), name="emi_bank_approval_days_ordered"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmiSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("tenure_min_years", models.PositiveSmallIntegerField(default=1)),
                ("tenure_max_years", models.PositiveSmallIntegerField(default=10)),
                ("tenure_default_years", models.PositiveSmallIntegerField(default=5)),
                ("daily_saving_divisor", models.PositiveSmallIntegerField(default=30, help_text="Daily amount = monthly EMI ÷ this.")),
                ("price_step", models.DecimalField(decimal_places=2, default=Decimal("5000.00"), help_text="Step of the price slider (₹).", max_digits=14)),
                (
                    "down_payment_min_pct",
                    models.DecimalField(decimal_places=4, default=Decimal("0.1000"), help_text="Down-payment slider floor (fraction of the price); also the default down payment.", max_digits=6),
                ),
                ("down_payment_max_pct", models.DecimalField(decimal_places=4, default=Decimal("0.9000"), max_digits=6)),
                ("down_payment_step_pct", models.DecimalField(decimal_places=4, default=Decimal("0.0500"), max_digits=6)),
                (
                    "down_payment_quick_adds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=2, max_digits=14), blank=True, default=list, help_text="₹ amounts offered as one-tap chips."
                    ),
                ),
                ("rate_max", models.DecimalField(decimal_places=4, default=Decimal("0.1800"), help_text="Upper end of the rate slider (fraction).", max_digits=6)),
                ("default_annual_rate", models.DecimalField(decimal_places=4, default=Decimal("0.0950"), help_text="Rate when no interest rule matches (fraction).", max_digits=6)),
                ("panel_life_years", models.PositiveSmallIntegerField(default=25)),
                ("disclaimer_en", models.TextField(blank=True, default="")),
                ("disclaimer_ml", models.TextField(blank=True, default="", help_text="Malayalam; falls back to English.")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "emi_settings",
                "constraints": [
                    models.UniqueConstraint(models.Value(1), condition=models.Q(("deleted_at__isnull", True)), name="emi_settings_singleton"),
                    models.CheckConstraint(
                        condition=models.Q(("tenure_min_years__gte", 1), ("tenure_min_years__lte", models.F("tenure_default_years")), ("tenure_default_years__lte", models.F("tenure_max_years"))),
                        name="emi_settings_tenure_ordered",
                    ),
                    models.CheckConstraint(condition=models.Q(("daily_saving_divisor__gte", 1), ("price_step__gt", 0)), name="emi_settings_steps_positive"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("down_payment_min_pct__gt", 0), ("down_payment_min_pct__lte", models.F("down_payment_max_pct")), ("down_payment_max_pct__lte", 1), ("down_payment_step_pct__gt", 0)
                        ),
                        name="emi_settings_down_payment_band",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate_max__gte", 0), ("rate_max__lt", 1), ("default_annual_rate__gte", 0), ("default_annual_rate__lt", 1)), name="emi_settings_rates_fraction"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InterestRateRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("label", models.CharField(max_length=120)),
                ("min_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("min_system_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("max_system_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("min_amount", models.DecimalField(blank=True, decimal_places=2, help_text="Loan band lower bound (price − down payment), inclusive.", max_digits=14, null=True)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=2, help_text="Loan band upper bound, inclusive.", max_digits=14, null=True)),
                ("annual_rate", models.DecimalField(decimal_places=4, help_text="Starting annual rate as a fraction.", max_digits=6)),
                ("min_annual_rate", models.DecimalField(decimal_places=4, help_text="Floor: a customer-requested rate is raised to it.", max_digits=6)),
                ("is_locked", models.BooleanField(default=False, help_text="Locked rules ignore a customer-requested rate.")),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, help_text="Empty = in force since before the platform.", null=True)),
                ("effective_to", models.DateField(blank=True, help_text="Last day in force; empty = open-ended.", null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "emi_interest_rate_rule",
                "ordering": [
                    "-priority",
                    models.OrderBy(models.F("min_kw"), nulls_last=True),
                    models.OrderBy(models.F("min_system_cost"), nulls_last=True),
                    models.OrderBy(models.F("min_amount"), nulls_last=True),
                    "id",
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("min_kw__isnull", True), ("max_kw__isnull", True), ("min_kw__lte", models.F("max_kw")), _connector="OR"), name="emi_interest_rate_rule_min_kw_le_max_kw"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_system_cost__isnull", True), ("max_system_cost__isnull", True), ("min_system_cost__lte", models.F("max_system_cost")), _connector="OR"),
                        name="emi_interest_rate_rule_min_system_cost_le_max_system_cost",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_amount__isnull", True), ("max_amount__isnull", True), ("min_amount__lte", models.F("max_amount")), _connector="OR"),
                        name="emi_interest_rate_rule_min_amount_le_max_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("effective_from__isnull", True), ("effective_to__isnull", True), ("effective_from__lte", models.F("effective_to")), _connector="OR"),
                        name="emi_interest_rate_rule_effective_from_le_effective_to",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_annual_rate__gte", 0), ("annual_rate__lt", 1), ("annual_rate__gte", models.F("min_annual_rate"))), name="emi_interest_rate_rule_rates_valid"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubsidyRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("scheme", models.CharField(choices=[("PM_SURYA_GHAR", "PM Surya Ghar"), ("OTHER", "Other")], default="PM_SURYA_GHAR", max_length=24)),
                ("label", models.CharField(max_length=120)),
                ("kw_from", models.DecimalField(blank=True, decimal_places=2, help_text="Inclusive lower bound; empty = no lower bound.", max_digits=6, null=True)),
                ("kw_to", models.DecimalField(blank=True, decimal_places=2, help_text="Inclusive upper bound; empty = no upper bound.", max_digits=6, null=True)),
                ("amount", models.DecimalField(decimal_places=2, help_text="Flat subsidy (₹).", max_digits=14)),
                ("amount_per_kw", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="Added per kW of the system.", max_digits=14)),
                ("cap_amount", models.DecimalField(blank=True, decimal_places=2, help_text="Upper limit of the subsidy; empty = none.", max_digits=14, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "emi_subsidy_rule",
                "ordering": ["-priority", models.OrderBy(models.F("kw_from"), nulls_last=True), "id"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("scheme__in", ["PM_SURYA_GHAR", "OTHER"])), name="emi_subsidy_rule_scheme_valid"),
                    models.CheckConstraint(
                        condition=models.Q(("kw_from__isnull", True), ("kw_to__isnull", True), ("kw_from__lte", models.F("kw_to")), _connector="OR"), name="emi_subsidy_rule_kw_from_le_kw_to"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("effective_from__isnull", True), ("effective_to__isnull", True), ("effective_from__lte", models.F("effective_to")), _connector="OR"),
                        name="emi_subsidy_rule_effective_from_le_effective_to",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0), ("amount_per_kw__gte", 0), models.Q(("cap_amount__isnull", True), ("cap_amount__gte", 0), _connector="OR")),
                        name="emi_subsidy_rule_money_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("label", models.CharField(help_text='Shown on the tile, e.g. "3kW".', max_length=32)),
                ("capacity_kw", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price_per_kw", models.DecimalField(decimal_places=2, help_text="System cost = this × capacity.", max_digits=14)),
                ("price_min", models.DecimalField(blank=True, decimal_places=2, help_text="Floor of the customer's price slider; empty = the default price.", max_digits=14, null=True)),
                ("price_max", models.DecimalField(blank=True, decimal_places=2, help_text="Ceiling of the customer's price slider; empty = the default price.", max_digits=14, null=True)),
                ("monthly_bill_reference", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="Typical monthly bill for this size (the savings comparison).", max_digits=14)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "emi_system_size",
                "ordering": ["sort_order", "capacity_kw", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("capacity_kw",), name="emi_system_size_capacity_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("capacity_kw__gt", 0), ("price_per_kw__gt", 0)), name="emi_system_size_positive"),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("price_min__isnull", True), ("price_min__gte", 0), _connector="OR"),
                            models.Q(("price_max__isnull", True), ("price_max__gte", 0), _connector="OR"),
                            ("monthly_bill_reference__gte", 0),
                        ),
                        name="emi_system_size_money_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_min__isnull", True), ("price_max__isnull", True), ("price_min__lte", models.F("price_max")), _connector="OR"),
                        name="emi_system_size_price_min_le_price_max",
                    ),
                ],
            },
        ),
    ]
