# Generated by Django 6.0.8 on 2026-09-29 03:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillRangeSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("bill_range", models.PositiveIntegerField(help_text="Upper end (₹) of the monthly bill band this row prices.")),
                ("property_type", models.CharField(choices=[("RESIDENTIAL", "Residential"), ("COMMERCIAL", "Commercial")], max_length=16)),
                ("power_capacity_kw", models.DecimalField(decimal_places=3, max_digits=7)),
                ("installation_days_range", models.CharField(help_text='Installation time shown to the visitor, e.g. "3-7" (days).', max_length=255)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_subsidy", models.DecimalField(decimal_places=2, max_digits=14)),
                ("area_required_sqft", models.PositiveIntegerField()),
                (
                    "loan_available",
                    models.CharField(blank=True, default="", help_text='Loan range as shown, e.g. "2,00,000-6,00,000" or "N/A"; its first number is the graph\'s loan.', max_length=255),
                ),
                ("per_kw_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("final_cost", models.DecimalField(blank=True, decimal_places=2, help_text="Price after subsidy; the EMI is computed on it.", max_digits=14, null=True)),
                ("interest_rate", models.DecimalField(blank=True, decimal_places=4, help_text="Annual EMI interest rate as a fraction (0.0650 = 6.5 %).", max_digits=6, null=True)),
                ("inverter_price", models.DecimalField(blank=True, decimal_places=2, help_text="Hybrid inverter price added to a backup battery.", max_digits=14, null=True)),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are ignored by the calculators.")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "calculators_bill_range_size",
                "ordering": ["property_type", "bill_range", "id"],
                "indexes": [models.Index(fields=["property_type", "bill_range"], name="calculators_brs_type_range")],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("bill_range", "property_type"), name="calculators_bill_range_size_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("property_type__in", ["RESIDENTIAL", "COMMERCIAL"])), name="calculators_bill_range_size_type_valid"),
                    models.CheckConstraint(condition=models.Q(("bill_range__gt", 0)), name="calculators_bill_range_size_range_positive"),
                    models.CheckConstraint(condition=models.Q(("power_capacity_kw__gt", 0)), name="calculators_bill_range_size_kw_positive"),
                    models.CheckConstraint(condition=models.Q(("total_cost__gte", 0), ("total_subsidy__gte", 0)), name="calculators_bill_range_size_money_non_negative"),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("per_kw_rate__isnull", True), ("per_kw_rate__gte", 0), _connector="OR"),
                            models.Q(("final_cost__isnull", True), ("final_cost__gte", 0), _connector="OR"),
                            models.Q(("inverter_price__isnull", True), ("inverter_price__gte", 0), _connector="OR"),
                        ),
                        name="calculators_bill_range_size_prices_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("interest_rate__isnull", True), models.Q(("interest_rate__gte", 0), ("interest_rate__lt", 1)), _connector="OR"),
                        name="calculators_bill_range_size_rate_fraction",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapacitySize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("power_capacity_kw", models.DecimalField(decimal_places=3, help_text="System size (kW); the basic calculator looks rows up by it.", max_digits=7)),
                ("installation_days", models.PositiveIntegerField(help_text="Installation time in days (legacy time_to_complete).")),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_subsidy", models.DecimalField(decimal_places=2, max_digits=14)),
                ("area_required_sqft", models.PositiveIntegerField(help_text="Roof area in square feet (legacy area_required).")),
                ("is_active", models.BooleanField(default=True, help_text="Inactive rows are ignored by the calculators.")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "calculators_capacity_size",
                "ordering": ["power_capacity_kw", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("power_capacity_kw",), name="calculators_capacity_size_kw_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("power_capacity_kw__gt", 0)), name="calculators_capacity_size_kw_positive"),
                    models.CheckConstraint(condition=models.Q(("total_cost__gte", 0), ("total_subsidy__gte", 0)), name="calculators_capacity_size_money_non_negative"),
                ],
            },
        ),
    ]
