# Generated by Django 6.0.8 on 2026-09-28 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("visibility", models.CharField(choices=[("PUBLIC", "Public (CDN)"), ("PRIVATE", "Private (signed URL)")], max_length=8)),
                ("kind", models.CharField(choices=[("IMAGE", "Image"), ("DOCUMENT", "Document"), ("SIGNATURE", "Signature"), ("RESUME", "Resume"), ("PHOTO", "Photo")], max_length=16)),
                ("file", models.CharField(max_length=512)),
                ("cdn_url", models.CharField(blank=True, default="", max_length=512)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField()),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("alternative_text", models.CharField(blank=True, default="", max_length=255)),
                ("caption", models.TextField(blank=True, default="")),
                ("thumbnail_key", models.CharField(blank=True, default="", max_length=512)),
                ("folder", models.CharField(blank=True, default="", max_length=120)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "media_asset",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["visibility", "kind", "created_at"], name="media_asset_vis_kind_created"),
                    models.Index(fields=["folder", "created_at"], name="media_asset_folder_created"),
                ],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("visibility__in", ["PUBLIC", "PRIVATE"])), name="media_asset_visibility_valid"),
                    models.CheckConstraint(condition=models.Q(("kind__in", ["IMAGE", "DOCUMENT", "SIGNATURE", "RESUME", "PHOTO"])), name="media_asset_kind_valid"),
                    models.CheckConstraint(condition=models.Q(("visibility", "PUBLIC"), ("cdn_url", ""), _connector="OR"), name="media_asset_cdn_url_public_only"),
                    models.CheckConstraint(
                        condition=models.Q(models.Q(("kind__in", ["RESUME", "SIGNATURE"]), _negated=True), ("visibility", "PRIVATE"), _connector="OR"), name="media_asset_sensitive_kinds_private"
                    ),
                    models.CheckConstraint(condition=models.Q(("size_bytes__gte", 0)), name="media_asset_size_non_negative"),
                    models.UniqueConstraint(fields=("visibility", "file"), name="media_asset_storage_key_uniq"),
                ],
            },
        ),
    ]
