# Generated by Django 6.0.8 on 2026-09-29 03:35

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("gstin", models.CharField(blank=True, default="", max_length=15)),
                ("contact", models.JSONField(blank=True, default=dict)),
                ("address", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "procurement_supplier",
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.CharField(max_length=32)),
                ("invoice_no", models.CharField(blank=True, default="", max_length=64)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("COMMITTED", "Committed"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=10)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("charges_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("allocation_method", models.CharField(default="PURCHASE_VALUE_PROPORTION", max_length=32)),
                ("note", models.TextField(blank=True, default="")),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("commit_reason", models.TextField(blank=True, default="")),
                ("is_seed", models.BooleanField(default=False)),
                ("other_charges_declared", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("committed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("reverses", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reversals", to="procurement.batch")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="batches", to="procurement.supplier")),
            ],
            options={
                "db_table": "procurement_batch",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BatchCharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("kind", models.CharField(choices=[("FREIGHT", "Freight"), ("INSURANCE", "Insurance"), ("HANDLING", "Handling"), ("DUTY", "Duty"), ("OTHER", "Other")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("note", models.TextField(blank=True, default="")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="charges", to="procurement.batch")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "procurement_batch_charge",
                "ordering": ["batch_id", "id"],
                "constraints": [models.CheckConstraint(condition=models.Q(("kind__in", ["FREIGHT", "INSURANCE", "HANDLING", "DUTY", "OTHER"])), name="procurement_batch_charge_kind_valid")],
            },
        ),
        migrations.CreateModel(
            name="BatchLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_purchase_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "line_value",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(models.F("qty"), "*", models.F("unit_purchase_price")),
                        output_field=models.DecimalField(decimal_places=5, max_digits=27),
                    ),
                ),
                ("landed_unit_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("allocated_charges", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("allocation_pct", models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="procurement.batch")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="batch_lines", to="catalog.component")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("landed_row", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="pricing.price")),
                ("price_row", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="pricing.price")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "procurement_batch_line",
                "ordering": ["batch_id", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("batch", "component"), name="procurement_batch_line_component_uniq"),
                    models.CheckConstraint(condition=models.Q(("qty", 0), _negated=True), name="procurement_batch_line_qty_not_zero"),
                    models.CheckConstraint(condition=models.Q(("unit_purchase_price__gte", 0)), name="procurement_batch_line_price_not_negative"),
                    models.CheckConstraint(condition=models.Q(("landed_unit_cost__isnull", True), ("landed_unit_cost__gte", 0), _connector="OR"), name="procurement_batch_line_landed_not_negative"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("code"), condition=models.Q(("deleted_at__isnull", True)), name="procurement_supplier_code_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.CheckConstraint(condition=models.Q(("code__regex", "^[A-Za-z0-9][A-Za-z0-9_.-]{0,31}$")), name="procurement_supplier_code_format"),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.CheckConstraint(condition=models.Q(("gstin", ""), ("gstin__regex", "^[0-9]{2}[A-Z0-9]{10}[0-9A-Z]{3}$"), _connector="OR"), name="procurement_supplier_gstin_format"),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.CheckConstraint(condition=models.Q(("name", ""), _negated=True), name="procurement_supplier_name_not_blank"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["status", "-created_at"], name="procurement_batch_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("number",), name="procurement_batch_number_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("reverses__isnull", False)), fields=("reverses",), name="procurement_batch_one_reversal"),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "COMMITTED", "CANCELLED"])), name="procurement_batch_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.CheckConstraint(condition=models.Q(("allocation_method", "PURCHASE_VALUE_PROPORTION")), name="procurement_batch_allocation_method_valid"),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "COMMITTED"), _negated=True), models.Q(("committed_at__isnull", False), ("effective_from__isnull", False)), _connector="OR"),
                name="procurement_batch_committed_stamped",
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.CheckConstraint(
                condition=models.Q(("reverses__isnull", True), models.Q(("reverses", models.F("id")), _negated=True), _connector="OR"), name="procurement_batch_not_own_reversal"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.CheckConstraint(condition=models.Q(("number__regex", "^[A-Z0-9][A-Z0-9_.-]{0,31}$")), name="procurement_batch_number_format"),
        ),
    ]
