# Generated by Django 6.0.8 on 2026-09-28 22:18

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("page", models.CharField(help_text="route key without leading/trailing slash; 'home' for /", max_length=200)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("keywords", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ("og_type", models.CharField(default="website", max_length=32)),
                ("og_image_url", models.CharField(blank=True, default="", help_text="site-relative or absolute image URL", max_length=500)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("og_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "seo_page_metadata",
                "ordering": ["page", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("page",), name="seo_page_metadata_page_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("page__regex", "^[a-z0-9][a-z0-9._~-]*(/[a-z0-9._~-]+)*$")), name="seo_page_metadata_page_format"),
                    models.CheckConstraint(condition=models.Q(("og_type__regex", "^[a-z][a-z0-9._:-]*$")), name="seo_page_metadata_og_type_format"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("from_path", models.CharField(help_text="site-relative source path, e.g. /old-blog/:slug", max_length=500)),
                ("to_path", models.CharField(help_text="site-relative path or absolute https URL", max_length=1000)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[(301, "301 Moved permanently"), (302, "302 Found (temporary)"), (307, "307 Temporary redirect"), (308, "308 Permanent redirect")], default=308
                    ),
                ),
                ("hits", models.PositiveIntegerField(default=0, help_text="reserved for a future hit counter (redirects run inside the Next.js build)")),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "seo_redirect",
                "ordering": ["from_path", "id"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("from_path",), name="seo_redirect_from_path_live_uniq"),
                    models.CheckConstraint(condition=models.Q(("status_code__in", [301, 302, 307, 308])), name="seo_redirect_status_code_valid"),
                    models.CheckConstraint(condition=models.Q(("from_path__startswith", "/"), models.Q(("from_path__startswith", "//"), _negated=True)), name="seo_redirect_from_path_site_relative"),
                    models.CheckConstraint(condition=models.Q(("from_path", models.F("to_path")), _negated=True), name="seo_redirect_not_to_itself"),
                ],
            },
        ),
    ]
