# Generated by Django 6.0.8 on 2026-09-29 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_initial"),
        ("documents", "0001_initial"),
        ("engineering", "0002_seed_rule_sets"),
        ("media", "0001_initial"),
        ("packs", "0001_initial"),
        ("pricing", "0003_current_price_view_and_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("SUPERSEDED", "Superseded")], default="DRAFT", max_length=10)),
                ("language_payload", models.JSONField(help_text="Bilingual content (labels, terms, timeline, appliances … every text {en, ml}).")),
                ("fit_report", models.JSONField(blank=True, default=dict, help_text="engines.content_fit.fit_summary of language_payload.")),
                ("release_payload", models.JSONField(blank=True, help_text="Frozen at publish: inclusions, tier names, testimonials, campaign.", null=True)),
                ("release_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("note", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_content_version",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="Inclusion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("key", models.CharField(max_length=64)),
                ("kind", models.CharField(choices=[("COMPONENT", "Component inclusion"), ("SERVICE", "Service matrix row")], default="COMPONENT", max_length=10)),
                ("label_en", models.CharField(max_length=160)),
                ("label_ml", models.CharField(blank=True, default="", max_length=200)),
                ("default_on", models.BooleanField(default=True)),
                ("applies_to", models.JSONField(default=dict, help_text='Per tier: {"BASE": true|false|null|"text", "VALUE": …, "PREMIUM": …}.')),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_inclusion",
                "ordering": ["kind", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GR-<n> (core.sequences QUO), taken at the first issue; blank while never issued. Imported Flarize numbers are kept as printed.",
                        max_length=48,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("ACCEPTED", "Accepted"), ("EXPIRED", "Expired"), ("SUPERSEDED", "Superseded"), ("CANCELLED", "Cancelled")],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, help_text="First issue.", null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reason", models.TextField(blank=True, default="")),
                ("source", models.CharField(choices=[("DIRECT", "Direct"), ("AFFILIATE", "Affiliate"), ("DISTRICT", "District")], default="DIRECT", max_length=10)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("affiliate_ref", models.CharField(blank=True, default="", max_length=64)),
                ("legacy", models.BooleanField(default=False, help_text="Imported from Flarize (quotation-state.json).")),
                ("legacy_ref", models.CharField(blank=True, default="", help_text="Flarize quotationId of an imported quotation.", max_length=96)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quotations", to="customers.customer")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_quotation",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("customer_name", models.CharField(max_length=80)),
                ("location", models.CharField(blank=True, default="", max_length=80)),
                ("capacity_kw", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("system_label", models.CharField(blank=True, default="", help_text='Printed system label, e.g. "5 kW System".', max_length=40)),
                ("installed_on", models.DateField(blank=True, help_text="Only month and year are printed.", null=True)),
                ("installed_on_label", models.CharField(blank=True, default="", help_text="Free-text install date when no date is known (Flarize).", max_length=40)),
                ("quote_en", models.TextField(max_length=1000)),
                ("quote_ml", models.TextField(blank=True, default="", max_length=1000)),
                ("bill_before", models.DecimalField(blank=True, decimal_places=2, help_text="Monthly bill before solar (INR).", max_digits=14, null=True)),
                ("bill_after", models.DecimalField(blank=True, decimal_places=2, help_text="Monthly bill after solar (INR).", max_digits=14, null=True)),
                ("photo_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("show_on_website", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("photo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_testimonial",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TierDisplayName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("system_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid")], max_length=8)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("name_en", models.CharField(max_length=80)),
                ("name_ml", models.CharField(blank=True, default="", max_length=120)),
                ("is_recommended", models.BooleanField(default=False)),
                ("badge_en", models.CharField(blank=True, default="", max_length=80)),
                ("badge_ml", models.CharField(blank=True, default="", max_length=120)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_tier_display_name",
                "ordering": ["system_type", "tier"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("number", models.PositiveSmallIntegerField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("SUPERSEDED", "Superseded")], default="DRAFT", max_length=10)),
                ("system_type", models.CharField(choices=[("ONGRID", "On-grid"), ("HYBRID", "Hybrid")], max_length=8)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("size_key", models.CharField(help_text="Pack size key: 3, 5sp, 5tp, 8 …", max_length=10)),
                ("size_kw", models.DecimalField(decimal_places=2, max_digits=6)),
                ("phase", models.CharField(choices=[("1P", "Single phase"), ("3P", "Three phase")], max_length=2)),
                ("battery_config", models.CharField(blank=True, default="", help_text="Hybrid battery quantity 0/1/2; blank for on-grid.", max_length=1)),
                ("future_size_key", models.CharField(blank=True, default="", help_text="Future-ready (upgrade) target size key.", max_length=10)),
                ("structure_type", models.CharField(blank=True, default="", help_text="Structure template of the roof type (flatRoof, sheetRoof, elevated).", max_length=24)),
                ("roof_type", models.CharField(choices=[("FLAT", "Flat roof"), ("SHEET", "Sheet roof"), ("ELEVATED", "Elevated structure")], default="FLAT", max_length=10)),
                ("distance_km", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("vehicle_type", models.CharField(blank=True, default="", max_length=32)),
                ("subsidy_type", models.CharField(choices=[("residential", "Residential (PM Surya Ghar)"), ("ghs", "Group housing society"), ("none", "No subsidy")], default="none", max_length=12)),
                ("ghs_houses", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("language", models.CharField(choices=[("en", "English"), ("ml", "Malayalam")], default="en", max_length=2)),
                ("selections", models.JSONField(blank=True, default=dict, help_text="Swaps per tier, offer code, appliance rows, recommended tier (validated).")),
                ("customer_price_incl_gst", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("transport_extra", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("offer_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, help_text="Sum of APPROVED discount requests.", max_digits=14)),
                ("final_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("gross_margin_pct", models.DecimalField(blank=True, decimal_places=4, help_text="Internal (pricing_internal): fraction vs. the reference cost.", max_digits=10, null=True)),
                ("gate_report", models.JSONField(blank=True, null=True)),
                ("notices", models.JSONField(blank=True, default=list, help_text="Warnings raised while the version was a draft (e.g. a newer PackRelease).")),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("document_payload", models.JSONField(blank=True, help_text="The deep-frozen issued document (payload, alternatives, freeze, pins).", null=True)),
                ("document_payload_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("legacy", models.BooleanField(default=False)),
                ("content_release", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="quotations.contentversion")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("document_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="documents.renderjob")),
                ("document_job_ml", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="documents.renderjob")),
                ("issued_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("pack_release", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="packs.packrelease")),
                ("price_release", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="pricing.pricerelease")),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="quotations.quotation")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_version",
                "ordering": ["quotation_id", "number"],
            },
        ),
        migrations.AddField(
            model_name="quotation",
            name="current_version",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="quotations.version"),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("EMAIL", "E-mail"), ("LEGACY_LINK", "Legacy website quote link")], default="EMAIL", max_length=12)),
                ("to", models.CharField(help_text="Recipient e-mail address (legacy rows: the phone number).", max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("language", models.CharField(choices=[("en", "English"), ("ml", "Malayalam")], default="en", max_length=2)),
                ("status", models.CharField(choices=[("QUEUED", "Queued"), ("SENT", "Sent"), ("FAILED", "Failed")], default="QUEUED", max_length=8)),
                ("provider_id", models.CharField(blank=True, default="", max_length=128)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("legacy_ref", models.CharField(blank=True, default="", help_text="sent_quotes.quote_id of an imported row.", max_length=64)),
                ("legacy_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="quotations.version")),
            ],
            options={
                "db_table": "quotations_email_log",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.TextField()),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=10)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("quotation_version", models.ForeignKey(db_column="version_id", on_delete=django.db.models.deletion.CASCADE, related_name="discount_requests", to="quotations.version")),
            ],
            options={
                "db_table": "quotations_discount_request",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommercialSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("is_primary", models.BooleanField(default=True)),
                ("cost_lines", models.JSONField(default=dict, help_text="cost / pricing / pack / offer domains of the snapshot (internal).")),
                ("pins", models.JSONField(default=dict, help_text="The 13 pinned versions + the platform release numbers.")),
                ("margin_check", models.JSONField(blank=True, default=dict, help_text="landedCostCheck + reference margin (internal).")),
                ("customer_total_incl_gst", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("record", models.JSONField(help_text="The frozen ISSUED commercial snapshot.")),
                ("legacy_ref", models.CharField(blank=True, default="", help_text="Flarize commercial snapshotId of an imported snapshot.", max_length=96)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("quotation_version", models.ForeignKey(db_column="version_id", on_delete=django.db.models.deletion.CASCADE, related_name="commercial_snapshots", to="quotations.version")),
            ],
            options={
                "db_table": "quotations_commercial_snapshot",
                "ordering": ["quotation_version_id", "-is_primary", "tier"],
            },
        ),
        migrations.CreateModel(
            name="BomSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("tier", models.CharField(choices=[("BASE", "Base"), ("VALUE", "Value"), ("PREMIUM", "Premium")], max_length=8)),
                ("is_primary", models.BooleanField(default=True)),
                ("lines", models.JSONField(default=list)),
                ("lock_acknowledgements", models.JSONField(blank=True, default=list)),
                ("engineering_status", models.CharField(blank=True, default="", help_text="VALID / WARNING / BLOCKED (checker verdict at lock).", max_length=8)),
                ("record", models.JSONField(help_text="The frozen LOCKED BOM snapshot (bomLock/bomSnapshot record).")),
                ("legacy_ref", models.CharField(blank=True, default="", help_text="Flarize bomSnapshotId of an imported snapshot.", max_length=96)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("engineering_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="engineering.run")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("quotation_version", models.ForeignKey(db_column="version_id", on_delete=django.db.models.deletion.CASCADE, related_name="bom_snapshots", to="quotations.version")),
            ],
            options={
                "db_table": "quotations_bom_snapshot",
                "ordering": ["quotation_version_id", "-is_primary", "tier"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("title", models.CharField(max_length=150)),
                ("body_en", models.TextField(blank=True, default="")),
                ("body_ml", models.TextField(blank=True, default="")),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.mediaasset")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "quotations_campaign",
                "ordering": ["-starts_on", "-id"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("title", ""), _negated=True), name="quotations_campaign_title_present"),
                    models.CheckConstraint(
                        condition=models.Q(("starts_on__isnull", True), ("ends_on__isnull", True), ("ends_on__gte", models.F("starts_on")), _connector="OR"), name="quotations_campaign_dates_ordered"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.UniqueConstraint(fields=("number",), name="quotations_content_version_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "DRAFT")), fields=("status",), name="quotations_content_version_one_draft"),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "PUBLISHED")), fields=("status",), name="quotations_content_version_one_published"),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "SUPERSEDED"])), name="quotations_content_version_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="quotations_content_version_number_positive"),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", "DRAFT"), models.Q(("published_at__isnull", False), ("release_payload__isnull", False)), _connector="OR"),
                name="quotations_content_version_published_is_frozen",
            ),
        ),
        migrations.AddConstraint(
            model_name="inclusion",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("key",), name="quotations_inclusion_key_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="inclusion",
            constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["COMPONENT", "SERVICE"])), name="quotations_inclusion_kind_valid"),
        ),
        migrations.AddConstraint(
            model_name="inclusion",
            constraint=models.CheckConstraint(condition=models.Q(("key__regex", "^[A-Za-z][A-Za-z0-9_]{0,63}$")), name="quotations_inclusion_key_format"),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(fields=["show_on_website", "is_active", "sort_order"], name="quotations_testimonial_public"),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(condition=models.Q(("customer_name", ""), _negated=True), name="quotations_testimonial_name_present"),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(condition=models.Q(("quote_en", ""), _negated=True), name="quotations_testimonial_quote_present"),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(condition=models.Q(("capacity_kw__isnull", True), ("capacity_kw__gt", 0), _connector="OR"), name="quotations_testimonial_capacity_positive"),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(condition=models.Q(("bill_before__isnull", True), ("bill_before__gte", 0), _connector="OR"), name="quotations_testimonial_bill_before_positive"),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(condition=models.Q(("bill_after__isnull", True), ("bill_after__gte", 0), _connector="OR"), name="quotations_testimonial_bill_after_positive"),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(
                condition=models.Q(("bill_before__isnull", True), ("bill_after__isnull", True), ("bill_after__lte", models.F("bill_before")), _connector="OR"),
                name="quotations_testimonial_bill_after_not_above_before",
            ),
        ),
        migrations.AddConstraint(
            model_name="tierdisplayname",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("system_type", "tier"), name="quotations_tier_display_name_uniq"),
        ),
        migrations.AddConstraint(
            model_name="tierdisplayname",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_recommended", True)), fields=("system_type",), name="quotations_tier_display_name_one_recommended"
            ),
        ),
        migrations.AddConstraint(
            model_name="tierdisplayname",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID"])), name="quotations_tier_display_name_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="tierdisplayname",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="quotations_tier_display_name_tier_valid"),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(fields=["status", "pack_release"], name="quotations_version_release"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(fields=("quotation", "number"), name="quotations_version_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "DRAFT")), fields=("quotation",), name="quotations_version_one_draft"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "ISSUED", "SUPERSEDED"])), name="quotations_version_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("system_type__in", ["ONGRID", "HYBRID"])), name="quotations_version_system_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="quotations_version_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["1P", "3P"])), name="quotations_version_phase_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("roof_type__in", ["FLAT", "SHEET", "ELEVATED"])), name="quotations_version_roof_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("subsidy_type__in", ["residential", "ghs", "none"])), name="quotations_version_subsidy_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("language__in", ["en", "ml"])), name="quotations_version_language_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("battery_config__in", ["", "0", "1", "2"])), name="quotations_version_battery_config_valid"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("size_key__regex", "^[0-9]+(\\.[0-9]{1,2})?(sp|tp)?$")), name="quotations_version_size_key_format"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(
                condition=models.Q(("future_size_key", ""), ("future_size_key__regex", "^[0-9]+(\\.[0-9]{1,2})?(sp|tp)?$"), _connector="OR"), name="quotations_version_future_size_key_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="quotations_version_number_positive"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("size_kw__gt", 0)), name="quotations_version_size_positive"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("distance_km__gte", 0)), name="quotations_version_distance_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(condition=models.Q(("offer_total__gte", 0), ("discount_total__gte", 0)), name="quotations_version_reductions_not_negative"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(
                condition=models.Q(("legacy", True), models.Q(("pack_release__isnull", False), ("price_release__isnull", False)), _connector="OR"), name="quotations_version_releases_pinned"
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "DRAFT"), models.Q(("document_payload__isnull", False), ("document_payload_sha256__regex", "^[0-9a-f]{64}$"), ("issued_at__isnull", False)), _connector="OR"
                ),
                name="quotations_version_issued_is_frozen",
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("status", "DRAFT"), _negated=True), models.Q(("document_payload__isnull", True), ("document_payload_sha256", "")), _connector="OR"),
                name="quotations_version_draft_not_frozen",
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["owner", "-created_at"], name="quotations_quotation_owner"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["customer", "-created_at"], name="quotations_quotation_customer"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["status", "valid_until"], name="quotations_quotation_expiry"),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("number", ""), _negated=True)), fields=("number",), name="quotations_quotation_number_live_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("legacy_ref", ""), _negated=True)), fields=("legacy_ref",), name="quotations_quotation_legacy_ref_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["DRAFT", "ISSUED", "ACCEPTED", "EXPIRED", "SUPERSEDED", "CANCELLED"])), name="quotations_quotation_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(condition=models.Q(("source__in", ["DIRECT", "AFFILIATE", "DISTRICT"])), name="quotations_quotation_source_valid"),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "CANCELLED"]), models.Q(("number", ""), _negated=True), _connector="OR"), name="quotations_quotation_issued_has_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(condition=models.Q(("affiliate_ref", ""), ("source", "AFFILIATE"), _connector="OR"), name="quotations_quotation_affiliate_only_for_affiliate"),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("source", "DISTRICT"), _negated=True), models.Q(("district", ""), _negated=True), _connector="OR"), name="quotations_quotation_district_required"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(condition=models.Q(("accepted_at__isnull", True), ("status", "ACCEPTED"), _connector="OR"), name="quotations_quotation_accepted_at_only_accepted"),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("accepted_at__isnull", False), ("status", "ACCEPTED")), models.Q(("status", "ACCEPTED"), _negated=True), _connector="OR"),
                name="quotations_quotation_accepted_has_at",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["version", "-created_at"], name="quotations_email_log_version"),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.UniqueConstraint(condition=models.Q(("legacy_ref", ""), _negated=True), fields=("legacy_ref",), name="quotations_email_log_legacy_ref_uniq"),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.CheckConstraint(condition=models.Q(("channel__in", ["EMAIL", "LEGACY_LINK"])), name="quotations_email_log_channel_valid"),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["QUEUED", "SENT", "FAILED"])), name="quotations_email_log_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.CheckConstraint(condition=models.Q(("language__in", ["en", "ml"])), name="quotations_email_log_language_valid"),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__isnull", False), models.Q(("legacy_ref", ""), _negated=True), _connector="OR"), name="quotations_email_log_version_or_legacy"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("status", "SENT"), _negated=True), ("sent_at__isnull", False), _connector="OR"), name="quotations_email_log_sent_has_at"),
        ),
        migrations.AddConstraint(
            model_name="discountrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "PENDING")), fields=("quotation_version",), name="quotations_discount_one_pending"),
        ),
        migrations.AddConstraint(
            model_name="discountrequest",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["PENDING", "APPROVED", "REJECTED"])), name="quotations_discount_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="discountrequest",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="quotations_discount_amount_positive"),
        ),
        migrations.AddConstraint(
            model_name="discountrequest",
            constraint=models.CheckConstraint(condition=models.Q(("reason", ""), _negated=True), name="quotations_discount_reason_present"),
        ),
        migrations.AddConstraint(
            model_name="discountrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decided_at__isnull", True), ("status", "PENDING")), models.Q(models.Q(("status", "PENDING"), _negated=True), ("decided_at__isnull", False)), _connector="OR"
                ),
                name="quotations_discount_decided_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="commercialsnapshot",
            constraint=models.UniqueConstraint(fields=("quotation_version", "tier"), name="quotations_commercial_snapshot_version_tier_uniq"),
        ),
        migrations.AddConstraint(
            model_name="commercialsnapshot",
            constraint=models.UniqueConstraint(condition=models.Q(("is_primary", True)), fields=("quotation_version",), name="quotations_commercial_snapshot_one_primary"),
        ),
        migrations.AddConstraint(
            model_name="commercialsnapshot",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="quotations_commercial_snapshot_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="bomsnapshot",
            constraint=models.UniqueConstraint(fields=("quotation_version", "tier"), name="quotations_bom_snapshot_version_tier_uniq"),
        ),
        migrations.AddConstraint(
            model_name="bomsnapshot",
            constraint=models.UniqueConstraint(condition=models.Q(("is_primary", True)), fields=("quotation_version",), name="quotations_bom_snapshot_one_primary"),
        ),
        migrations.AddConstraint(
            model_name="bomsnapshot",
            constraint=models.CheckConstraint(condition=models.Q(("tier__in", ["BASE", "VALUE", "PREMIUM"])), name="quotations_bom_snapshot_tier_valid"),
        ),
        migrations.AddConstraint(
            model_name="bomsnapshot",
            constraint=models.CheckConstraint(condition=models.Q(("engineering_status__in", ["", "VALID", "WARNING", "BLOCKED"])), name="quotations_bom_snapshot_engineering_status_valid"),
        ),
    ]
