# Generated by Django 6.0.8 on 2026-09-29 07:22
#
# attendance_raw_punch is a range-partitioned table (monthly on the terminal's wall clock `device_time`, DV-91), which
# Django cannot declare: the table, its DEFAULT partition, its keys and indexes and the first monthly partitions are
# created with raw SQL (SeparateDatabaseAndState). Unlike audit_log the model stays *managed* — its state mirrors the
# SQL exactly — so test flushes truncate it together with devices_device, which it references.

import datetime

import attendance.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


RAW_PUNCH_SQL = """
CREATE TABLE attendance_raw_punch (
    id bigserial NOT NULL,
    device_id bigint NOT NULL REFERENCES devices_device (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    device_serial varchar(80) NOT NULL DEFAULT '',
    device_record_uid integer NULL,
    pin varchar(80) NOT NULL,
    device_time timestamp NOT NULL,
    punch_at timestamptz NOT NULL,
    status_code smallint NULL,
    punch_code smallint NULL,
    source varchar(12) NOT NULL,
    agent_id bigint NULL REFERENCES devices_agent (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    -- the ADMS evidence row (devices_adms_request is partitioned with a composite key): no FK (DV-91)
    adms_request_id bigint NULL,
    dedup_key varchar(64) NOT NULL,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    received_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT attendance_raw_punch_pkey PRIMARY KEY (id, device_time),
    -- A11: one row per content hash; device_time is part of the hash, so this is "dedup_key is unique"
    CONSTRAINT attendance_raw_punch_dedup_uniq UNIQUE (dedup_key, device_time),
    CONSTRAINT attendance_raw_punch_source_valid CHECK (source IN ('AGENT_PUSH', 'ADMS_PUSH', 'IMPORT')),
    CONSTRAINT attendance_raw_punch_pin_not_blank CHECK (pin <> ''),
    CONSTRAINT attendance_raw_punch_dedup_key_format CHECK (dedup_key ~ '^[0-9a-f]{64}$')
) PARTITION BY RANGE (device_time);

CREATE TABLE attendance_raw_punch_default PARTITION OF attendance_raw_punch DEFAULT;

CREATE INDEX attendance_raw_punch_pin_idx ON attendance_raw_punch (device_id, pin, device_time);
CREATE INDEX attendance_raw_punch_at_idx ON attendance_raw_punch (punch_at);
CREATE INDEX attendance_raw_punch_agent_idx ON attendance_raw_punch (agent_id);
"""

RAW_PUNCH_DROP_SQL = "DROP TABLE IF EXISTS attendance_raw_punch CASCADE;"


def _month(value, months):
    index = value.year * 12 + (value.month - 1) + months
    return datetime.date(index // 12, index % 12 + 1, 1)


def create_initial_partitions(apps, schema_editor):
    """The current month and the next two; `maintain_attendance_punches` (release + Beat) keeps the window moving."""
    today = django.utils.timezone.now().date()
    quote = schema_editor.connection.ops.quote_name
    for offset in range(3):
        start, end = _month(today, offset), _month(today, offset + 1)
        name = f"attendance_raw_punch_y{start.year:04d}m{start.month:02d}"
        schema_editor.execute(
            f"CREATE TABLE IF NOT EXISTS {quote(name)} PARTITION OF attendance_raw_punch "
            f"FOR VALUES FROM ('{start.isoformat()} 00:00:00') TO ('{end.isoformat()} 00:00:00')"
        )


def apply_append_only(apps, schema_editor):
    """REVOKE UPDATE, DELETE, TRUNCATE from DB_APP_ROLE when the app connects as a role other than the owner."""
    role = (getattr(settings, "DB_APP_ROLE", "") or "").strip()
    if not role:
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_user")
        if cursor.fetchone()[0] == role:
            return
    from attendance.services.partitions import apply_append_only_privileges

    apply_append_only_privileges(role)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("work_date", models.DateField()),
                ("first_in", attendance.models.fields.WallClockDateTimeField(blank=True, null=True)),
                ("last_out", attendance.models.fields.WallClockDateTimeField(blank=True, null=True)),
                ("punch_count", models.SmallIntegerField(default=0)),
                ("working_minutes", models.IntegerField(default=0)),
                ("break_minutes", models.IntegerField(default=0)),
                ("late_minutes", models.IntegerField(default=0)),
                ("early_exit_minutes", models.IntegerField(default=0)),
                ("overtime_minutes", models.IntegerField(default=0)),
                ("is_late", models.BooleanField(default=False)),
                ("is_early_exit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("PRESENT", "Present"), ("LATE", "Late"), ("ABSENT", "Absent"), ("HALF_DAY", "Half Day"), ("WEEKLY_OFF", "Weekly Off"), ("HOLIDAY", "Holiday"), ("ON_LEAVE", "Leave")],
                        max_length=12,
                    ),
                ),
                ("worked_on_off_day", models.BooleanField(default=False)),
                ("leave_conflict", models.BooleanField(default=False)),
                ("missing_out", models.BooleanField(default=False)),
                ("source_raw_ids", models.JSONField(blank=True, default=list)),
                ("ignored_raw_ids", models.JSONField(blank=True, default=list)),
                ("processing_version", models.CharField(max_length=24)),
                ("computed_at", models.DateTimeField()),
                ("is_corrected", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_days", to="hr.employee")),
                ("first_device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="devices.device")),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="hr.office")),
                ("shift", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="hr.shift")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "attendance_day",
                "ordering": ["-work_date", "employee_id"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("status", "status"),
                            ("first_in", "first_in"),
                            ("last_out", "last_out"),
                            ("working_minutes", "working_minutes"),
                            ("break_minutes", "break_minutes"),
                            ("late_minutes", "late_minutes"),
                            ("early_exit_minutes", "early_exit_minutes"),
                            ("overtime_minutes", "overtime_minutes"),
                            ("is_late", "is_late"),
                            ("is_early_exit", "is_early_exit"),
                        ],
                        max_length=24,
                    ),
                ),
                ("old", models.JSONField(blank=True, help_text="The value the correction replaced (restored on revoke).", null=True)),
                ("new", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("revoked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("day", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corrections", to="attendance.attendanceday")),
            ],
            options={
                "db_table": "attendance_correction",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RecomputeRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("all_employees", models.BooleanField(default=False)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("reason", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="hr.employee")),
                ("office", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="hr.office")),
            ],
            options={
                "db_table": "attendance_recompute_request",
                "ordering": ["due_at", "id"],
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(fields=["office", "work_date"], name="attendance_day_office_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(fields=["work_date"], name="attendance_day_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(fields=["employee", "work_date"], name="attendance_day_employee_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(fields=["shift"], name="attendance_day_shift_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(fields=["first_device"], name="attendance_day_device_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("employee", "work_date"), name="attendance_day_employee_date_live_uniq"),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["PRESENT", "LATE", "ABSENT", "HALF_DAY", "WEEKLY_OFF", "HOLIDAY", "ON_LEAVE"])), name="attendance_day_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("break_minutes__gte", 0), ("early_exit_minutes__gte", 0), ("late_minutes__gte", 0), ("overtime_minutes__gte", 0), ("punch_count__gte", 0), ("working_minutes__gte", 0)
                ),
                name="attendance_day_counts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(condition=models.Q(("last_out__isnull", True), ("first_in__isnull", False), _connector="OR"), name="attendance_day_out_needs_in"),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(condition=models.Q(("last_out__isnull", True), ("last_out__gte", models.F("first_in")), _connector="OR"), name="attendance_day_out_after_in"),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("first_in__isnull", False), ("last_out__isnull", True), ("missing_out", True)),
                    models.Q(("missing_out", False), models.Q(("first_in__isnull", True), ("last_out__isnull", False), _connector="OR")),
                    _connector="OR",
                ),
                name="attendance_day_missing_out_derived",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancecorrection",
            index=models.Index(fields=["day", "created_at"], name="attendance_correction_day_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancecorrection",
            index=models.Index(fields=["revoked_by"], name="attendance_correction_rev_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("field__in", ["status", "first_in", "last_out", "working_minutes", "break_minutes", "late_minutes", "early_exit_minutes", "overtime_minutes", "is_late", "is_early_exit"])
                ),
                name="attendance_correction_field_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrection",
            constraint=models.CheckConstraint(condition=models.Q(("reason", ""), _negated=True), name="attendance_correction_reason_not_blank"),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrection",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("revoked_at__isnull", True)), fields=("day", "field"), name="attendance_correction_active_field_uniq"),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(("revoked_at__isnull", True), models.Q(("revoke_reason", ""), _negated=True), _connector="OR"), name="attendance_correction_revoke_reason"
            ),
        ),
        migrations.AddIndex(
            model_name="recomputerequest",
            index=models.Index(fields=["due_at"], name="attendance_recompute_due_idx"),
        ),
        migrations.AddIndex(
            model_name="recomputerequest",
            index=models.Index(fields=["employee"], name="attendance_recompute_emp_idx"),
        ),
        migrations.AddIndex(
            model_name="recomputerequest",
            index=models.Index(fields=["office"], name="attendance_recomp_office_idx"),
        ),
        migrations.AddConstraint(
            model_name="recomputerequest",
            constraint=models.CheckConstraint(condition=models.Q(("date_to__gte", models.F("date_from"))), name="attendance_recompute_dates_ordered"),
        ),
        migrations.AddConstraint(
            model_name="recomputerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("all_employees", False), ("employee__isnull", False), ("office__isnull", True)),
                    models.Q(("all_employees", False), ("employee__isnull", True), ("office__isnull", False)),
                    models.Q(("all_employees", True), ("employee__isnull", True), ("office__isnull", True)),
                    _connector="OR",
                ),
                name="attendance_recompute_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="recomputerequest",
            constraint=models.CheckConstraint(condition=models.Q(("reason", ""), _negated=True), name="attendance_recompute_reason_not_blank"),
        ),
            migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RawPunch",
                    fields=[
                        ("pk", models.CompositePrimaryKey("id", "device_time", blank=True, editable=False, primary_key=True, serialize=False)),
                        ("id", models.BigIntegerField(db_default=models.Func(models.Value("attendance_raw_punch_id_seq"), function="nextval", output_field=models.BigIntegerField()), editable=False)),
                        ("device_serial", models.CharField(blank=True, default="", max_length=80)),
                        ("device_record_uid", models.IntegerField(blank=True, help_text="The terminal's record uid (data, not identity: A11).", null=True)),
                        ("pin", models.CharField(max_length=80)),
                        ("device_time", attendance.models.fields.WallClockDateTimeField(help_text="The terminal's wall clock as reported (never corrected).")),
                        ("punch_at", models.DateTimeField(help_text="device_time in the office's time zone (A10).")),
                        ("status_code", models.SmallIntegerField(blank=True, null=True)),
                        ("punch_code", models.SmallIntegerField(blank=True, null=True)),
                        ("source", models.CharField(choices=[("AGENT_PUSH", "Office agent"), ("ADMS_PUSH", "ADMS push"), ("IMPORT", "Imported from eSSL")], max_length=12)),
                        ("adms_request_id", models.BigIntegerField(blank=True, null=True)),
                        ("dedup_key", models.CharField(max_length=64)),
                        ("raw_payload", models.JSONField(blank=True, default=dict)),
                        ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                        ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="devices.agent")),
                        ("device", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="raw_punches", to="devices.device")),
                    ],
                    options={
                        "db_table": "attendance_raw_punch",
                        "ordering": ["-punch_at", "-id"],
                        "default_permissions": (),
                    },
                ),
                migrations.AddIndex(
                    model_name="rawpunch",
                    index=models.Index(fields=["device", "pin", "device_time"], name="attendance_raw_punch_pin_idx"),
                ),
                migrations.AddIndex(
                    model_name="rawpunch",
                    index=models.Index(fields=["punch_at"], name="attendance_raw_punch_at_idx"),
                ),
                migrations.AddIndex(
                    model_name="rawpunch",
                    index=models.Index(fields=["agent"], name="attendance_raw_punch_agent_idx"),
                ),
                migrations.AddConstraint(
                    model_name="rawpunch",
                    constraint=models.UniqueConstraint(fields=("dedup_key", "device_time"), name="attendance_raw_punch_dedup_uniq"),
                ),
                migrations.AddConstraint(
                    model_name="rawpunch",
                    constraint=models.CheckConstraint(condition=models.Q(("source__in", ["AGENT_PUSH", "ADMS_PUSH", "IMPORT"])), name="attendance_raw_punch_source_valid"),
                ),
                migrations.AddConstraint(
                    model_name="rawpunch",
                    constraint=models.CheckConstraint(condition=models.Q(("pin", ""), _negated=True), name="attendance_raw_punch_pin_not_blank"),
                ),
                migrations.AddConstraint(
                    model_name="rawpunch",
                    constraint=models.CheckConstraint(condition=models.Q(("dedup_key__regex", "^[0-9a-f]{64}$")), name="attendance_raw_punch_dedup_key_format"),
                ),
            ],
            database_operations=[
                migrations.RunSQL(RAW_PUNCH_SQL, RAW_PUNCH_DROP_SQL),
                migrations.RunPython(create_initial_partitions, migrations.RunPython.noop),
                migrations.RunPython(apply_append_only, migrations.RunPython.noop),
            ],
        ),
    ]
